import { Exercise } from '@/types/curriculum';

export const earthLevel3Questions: Exercise[] = [
  {
    id: 'earth-3-1',
    type: 'multiple-choice',
    content: 'Which word is a pronoun?',
    correctAnswer: 'he',
    options: ['he', 'run', 'beautiful', 'table'],
    explanation: 'He is a pronoun because it replaces a noun (a person\'s name).',
    planet: 'earth',
    level: 3,
    questionNumber: 1,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-2',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ is my best friend."',
    correctAnswer: 'She',
    options: ['She', 'Her', 'Hers', 'Herself'],
    explanation: 'She is the subject pronoun used at the beginning of a sentence.',
    planet: 'earth',
    level: 3,
    questionNumber: 2,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-3',
    type: 'multiple-choice',
    content: 'What pronoun replaces "the dog"?',
    correctAnswer: 'it',
    options: ['he', 'she', 'it', 'they'],
    explanation: 'It is used for animals and things.',
    planet: 'earth',
    level: 3,
    questionNumber: 3,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-4',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "I gave the book to _____."',
    correctAnswer: 'him',
    options: ['he', 'him', 'his', 'himself'],
    explanation: 'Him is the object pronoun used after prepositions like "to".',
    planet: 'earth',
    level: 3,
    questionNumber: 4,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-5',
    type: 'multiple-choice',
    content: 'What is the possessive pronoun for "I"?',
    correctAnswer: 'my',
    options: ['me', 'my', 'mine', 'myself'],
    explanation: 'My is the possessive pronoun that shows ownership.',
    planet: 'earth',
    level: 3,
    questionNumber: 5,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-6',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ are going to the park."',
    correctAnswer: 'We',
    options: ['Us', 'We', 'Our', 'Ours'],
    explanation: 'We is the subject pronoun for a group including yourself.',
    planet: 'earth',
    level: 3,
    questionNumber: 6,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-7',
    type: 'multiple-choice',
    content: 'What pronoun replaces "Tom and Sarah"?',
    correctAnswer: 'they',
    options: ['he', 'she', 'it', 'they'],
    explanation: 'They is used for more than one person.',
    planet: 'earth',
    level: 3,
    questionNumber: 7,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-8',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "The teacher called _____."',
    correctAnswer: 'me',
    options: ['I', 'me', 'my', 'mine'],
    explanation: 'Me is the object pronoun used after verbs.',
    planet: 'earth',
    level: 3,
    questionNumber: 8,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-9',
    type: 'multiple-choice',
    content: 'What is the possessive pronoun for "you"?',
    correctAnswer: 'your',
    options: ['you', 'your', 'yours', 'yourself'],
    explanation: 'Your is the possessive pronoun that shows ownership.',
    planet: 'earth',
    level: 3,
    questionNumber: 9,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-10',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ car is red."',
    correctAnswer: 'Their',
    options: ['They', 'Them', 'Their', 'Theirs'],
    explanation: 'Their is the possessive pronoun showing ownership by more than one person.',
    planet: 'earth',
    level: 3,
    questionNumber: 10,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-11',
    type: 'multiple-choice',
    content: 'What pronoun can replace "the books"?',
    correctAnswer: 'they',
    options: ['it', 'they', 'them', 'their'],
    explanation: 'They is used for plural things when they are the subject.',
    planet: 'earth',
    level: 3,
    questionNumber: 11,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-12',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "Please help _____."',
    correctAnswer: 'us',
    options: ['we', 'us', 'our', 'ours'],
    explanation: 'Us is the object pronoun for a group including yourself.',
    planet: 'earth',
    level: 3,
    questionNumber: 12,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-13',
    type: 'multiple-choice',
    content: 'What is the object pronoun for "she"?',
    correctAnswer: 'her',
    options: ['she', 'her', 'hers', 'herself'],
    explanation: 'Her is the object pronoun used after verbs and prepositions.',
    planet: 'earth',
    level: 3,
    questionNumber: 13,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-14',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ homework is finished."',
    correctAnswer: 'My',
    options: ['I', 'Me', 'My', 'Mine'],
    explanation: 'My is the possessive pronoun showing ownership.',
    planet: 'earth',
    level: 3,
    questionNumber: 14,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-15',
    type: 'multiple-choice',
    content: 'What pronoun replaces "the children"?',
    correctAnswer: 'they',
    options: ['he', 'she', 'it', 'they'],
    explanation: 'They is used for more than one person.',
    planet: 'earth',
    level: 3,
    questionNumber: 15,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-16',
    type: 'fill-in-blank',
    content: 'Complete: "_____ (I) am going to school."',
    correctAnswer: 'I',
    explanation: 'I is the subject pronoun used at the beginning of a sentence.',
    planet: 'earth',
    level: 3,
    questionNumber: 16,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-17',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "The ball belongs to _____."',
    correctAnswer: 'them',
    options: ['they', 'them', 'their', 'theirs'],
    explanation: 'Them is the object pronoun used after prepositions like "to".',
    planet: 'earth',
    level: 3,
    questionNumber: 17,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-18',
    type: 'multiple-choice',
    content: 'What is the possessive pronoun for "we"?',
    correctAnswer: 'our',
    options: ['we', 'us', 'our', 'ours'],
    explanation: 'Our is the possessive pronoun showing ownership by a group.',
    planet: 'earth',
    level: 3,
    questionNumber: 18,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-19',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ likes ice cream."',
    correctAnswer: 'He',
    options: ['He', 'Him', 'His', 'Himself'],
    explanation: 'He is the subject pronoun for a male person.',
    planet: 'earth',
    level: 3,
    questionNumber: 19,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-20',
    type: 'multiple-choice',
    content: 'What pronoun can replace "the cat"?',
    correctAnswer: 'it',
    options: ['he', 'she', 'it', 'they'],
    explanation: 'It is used for animals and things.',
    planet: 'earth',
    level: 3,
    questionNumber: 20,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-21',
    type: 'fill-in-blank',
    content: 'Complete: "Can you see _____ (they)?"',
    correctAnswer: 'them',
    explanation: 'Them is the object pronoun used after verbs like "see".',
    planet: 'earth',
    level: 3,
    questionNumber: 21,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-22',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "This book is _____."',
    correctAnswer: 'mine',
    options: ['I', 'me', 'my', 'mine'],
    explanation: 'Mine is the possessive pronoun used without a noun following it.',
    planet: 'earth',
    level: 3,
    questionNumber: 22,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-23',
    type: 'multiple-choice',
    content: 'What is the object pronoun for "they"?',
    correctAnswer: 'them',
    options: ['they', 'them', 'their', 'theirs'],
    explanation: 'Them is the object pronoun used after verbs and prepositions.',
    planet: 'earth',
    level: 3,
    questionNumber: 23,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-24',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ dog is very friendly."',
    correctAnswer: 'Her',
    options: ['She', 'Her', 'Hers', 'Herself'],
    explanation: 'Her is the possessive pronoun showing ownership by a female.',
    planet: 'earth',
    level: 3,
    questionNumber: 24,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-25',
    type: 'multiple-choice',
    content: 'What pronoun replaces "my sister and I"?',
    correctAnswer: 'we',
    options: ['I', 'she', 'we', 'they'],
    explanation: 'We is used when you include yourself in a group.',
    planet: 'earth',
    level: 3,
    questionNumber: 25,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-26',
    type: 'fill-in-blank',
    content: 'Complete: "_____ (you) are my friend."',
    correctAnswer: 'You',
    explanation: 'You is both the subject and object pronoun for the second person.',
    planet: 'earth',
    level: 3,
    questionNumber: 26,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-27',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "The pencil belongs to _____."',
    correctAnswer: 'her',
    options: ['she', 'her', 'hers', 'herself'],
    explanation: 'Her is the object pronoun used after prepositions like "to".',
    planet: 'earth',
    level: 3,
    questionNumber: 27,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-28',
    type: 'multiple-choice',
    content: 'What is the possessive pronoun for "he"?',
    correctAnswer: 'his',
    options: ['he', 'him', 'his', 'himself'],
    explanation: 'His is the possessive pronoun showing ownership by a male.',
    planet: 'earth',
    level: 3,
    questionNumber: 28,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-29',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ are playing soccer."',
    correctAnswer: 'They',
    options: ['They', 'Them', 'Their', 'Theirs'],
    explanation: 'They is the subject pronoun for more than one person.',
    planet: 'earth',
    level: 3,
    questionNumber: 29,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-30',
    type: 'multiple-choice',
    content: 'What pronoun can replace "the flowers"?',
    correctAnswer: 'they',
    options: ['it', 'they', 'them', 'their'],
    explanation: 'They is used for plural things when they are the subject.',
    planet: 'earth',
    level: 3,
    questionNumber: 30,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-31',
    type: 'correction',
    content: 'Correct the sentence: "Me and John are friends."',
    correctAnswer: 'John and I are friends.',
    explanation: 'Use "I" as the subject pronoun, and put the other person first.',
    planet: 'earth',
    level: 3,
    questionNumber: 31,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-32',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "The toys are _____."',
    correctAnswer: 'theirs',
    options: ['they', 'them', 'their', 'theirs'],
    explanation: 'Theirs is the possessive pronoun used without a noun following it.',
    planet: 'earth',
    level: 3,
    questionNumber: 32,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-33',
    type: 'fill-in-blank',
    content: 'Complete: "_____ (we) house is big."',
    correctAnswer: 'Our',
    explanation: 'Our is the possessive pronoun showing ownership by a group.',
    planet: 'earth',
    level: 3,
    questionNumber: 33,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-34',
    type: 'multiple-choice',
    content: 'What is the object pronoun for "I"?',
    correctAnswer: 'me',
    options: ['I', 'me', 'my', 'mine'],
    explanation: 'Me is the object pronoun used after verbs and prepositions.',
    planet: 'earth',
    level: 3,
    questionNumber: 34,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-35',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ backpack is heavy."',
    correctAnswer: 'His',
    options: ['He', 'Him', 'His', 'Himself'],
    explanation: 'His is the possessive pronoun showing ownership by a male.',
    planet: 'earth',
    level: 3,
    questionNumber: 35,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-36',
    type: 'multiple-choice',
    content: 'What pronoun replaces "the teacher"?',
    correctAnswer: 'she or he',
    options: ['it', 'they', 'she or he', 'them'],
    explanation: 'Use she or he for a person, depending on their gender.',
    planet: 'earth',
    level: 3,
    questionNumber: 36,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-37',
    type: 'fill-in-blank',
    content: 'Complete: "I saw _____ (she) at the store."',
    correctAnswer: 'her',
    explanation: 'Her is the object pronoun used after verbs like "saw".',
    planet: 'earth',
    level: 3,
    questionNumber: 37,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-38',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "The bike is _____."',
    correctAnswer: 'yours',
    options: ['you', 'your', 'yours', 'yourself'],
    explanation: 'Yours is the possessive pronoun used without a noun following it.',
    planet: 'earth',
    level: 3,
    questionNumber: 38,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-39',
    type: 'multiple-choice',
    content: 'What is the possessive pronoun for "it"?',
    correctAnswer: 'its',
    options: ['it', 'its', 'it\'s', 'itself'],
    explanation: 'Its is the possessive pronoun (without an apostrophe).',
    planet: 'earth',
    level: 3,
    questionNumber: 39,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-40',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ went to the movies."',
    correctAnswer: 'We',
    options: ['Us', 'We', 'Our', 'Ours'],
    explanation: 'We is the subject pronoun for a group including yourself.',
    planet: 'earth',
    level: 3,
    questionNumber: 40,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-41',
    type: 'correction',
    content: 'Correct the sentence: "Him and I are going."',
    correctAnswer: 'He and I are going.',
    explanation: 'Use "He" as the subject pronoun, not "Him".',
    planet: 'earth',
    level: 3,
    questionNumber: 41,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-42',
    type: 'fill-in-blank',
    content: 'Complete: "_____ (he) is my brother."',
    correctAnswer: 'He',
    explanation: 'He is the subject pronoun for a male person.',
    planet: 'earth',
    level: 3,
    questionNumber: 42,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-43',
    type: 'multiple-choice',
    content: 'What pronoun can replace "the students"?',
    correctAnswer: 'they',
    options: ['he', 'she', 'it', 'they'],
    explanation: 'They is used for more than one person.',
    planet: 'earth',
    level: 3,
    questionNumber: 43,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-44',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "Give the book to _____."',
    correctAnswer: 'me',
    options: ['I', 'me', 'my', 'mine'],
    explanation: 'Me is the object pronoun used after prepositions like "to".',
    planet: 'earth',
    level: 3,
    questionNumber: 44,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-45',
    type: 'multiple-choice',
    content: 'What is the possessive pronoun for "she"?',
    correctAnswer: 'her',
    options: ['she', 'her', 'hers', 'herself'],
    explanation: 'Her is the possessive pronoun showing ownership by a female.',
    planet: 'earth',
    level: 3,
    questionNumber: 45,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-46',
    type: 'correction',
    content: 'Correct the sentence: "The cat licked it\'s paw."',
    correctAnswer: 'The cat licked its paw.',
    explanation: 'Its (without apostrophe) is possessive; it\'s means "it is".',
    planet: 'earth',
    level: 3,
    questionNumber: 46,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-47',
    type: 'fill-in-blank',
    content: 'Complete: "_____ (they) friends are nice."',
    correctAnswer: 'Their',
    explanation: 'Their is the possessive pronoun showing ownership by more than one person.',
    planet: 'earth',
    level: 3,
    questionNumber: 47,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-48',
    type: 'multiple-choice',
    content: 'Choose the correct pronoun: "_____ loves to read."',
    correctAnswer: 'She',
    options: ['She', 'Her', 'Hers', 'Herself'],
    explanation: 'She is the subject pronoun for a female person.',
    planet: 'earth',
    level: 3,
    questionNumber: 48,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-49',
    type: 'multiple-choice',
    content: 'What pronoun can replace "my parents"?',
    correctAnswer: 'they',
    options: ['he', 'she', 'it', 'they'],
    explanation: 'They is used for more than one person.',
    planet: 'earth',
    level: 3,
    questionNumber: 49,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-3-50',
    type: 'correction',
    content: 'Correct the sentence: "Between you and I, this is a secret."',
    correctAnswer: 'Between you and me, this is a secret.',
    explanation: 'Use "me" as the object pronoun after prepositions like "between".',
    planet: 'earth',
    level: 3,
    questionNumber: 50,
    points: 10,
    difficulty: 'beginner'
  }
]; 