import { Exercise } from '@/types/curriculum';

export const earthLevel7Questions: Exercise[] = [
  {
    id: 'earth-7-1',
    type: 'multiple-choice',
    content: 'Choose the correct passive form: "The house _____ by a famous architect in 1920."',
    correctAnswer: 'was designed',
    options: ['designed', 'was designed', 'had designed', 'was designing'],
    explanation: 'Passive voice in simple past: was/were + past participle.',
    planet: 'earth',
    level: 7,
    questionNumber: 1,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-2',
    type: 'multiple-choice',
    content: 'Select the correct form: "The documents _____ before the meeting started."',
    correctAnswer: 'had been prepared',
    options: ['were prepared', 'had been prepared', 'were preparing', 'had prepared'],
    explanation: 'Past perfect passive for action completed before another past action.',
    planet: 'earth',
    level: 7,
    questionNumber: 2,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-3',
    type: 'fill-in-blank',
    content: 'Complete: "The bridge _____ (build) while the river _____ (be) diverted."',
    correctAnswer: 'was being built, was being',
    explanation: 'Past continuous passive for ongoing action in the past.',
    planet: 'earth',
    level: 7,
    questionNumber: 3,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-4',
    type: 'multiple-choice',
    content: 'Choose the correct form: "If I _____ earlier, I would have caught the train."',
    correctAnswer: 'had left',
    options: ['left', 'would leave', 'had left', 'was leaving'],
    explanation: 'Third conditional uses past perfect in the if-clause.',
    planet: 'earth',
    level: 7,
    questionNumber: 4,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-5',
    type: 'multiple-choice',
    content: 'Select the correct passive form: "The painting _____ stolen from the museum last night."',
    correctAnswer: 'was',
    options: ['was', 'had been', 'was being', 'has been'],
    explanation: 'Simple past passive for completed action at a specific time.',
    planet: 'earth',
    level: 7,
    questionNumber: 5,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-6',
    type: 'correction',
    content: 'Correct the sentence: "The book was being read by me when you called."',
    correctAnswer: 'I was reading the book when you called.',
    explanation: 'Active voice is often more natural than passive voice.',
    planet: 'earth',
    level: 7,
    questionNumber: 6,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-7',
    type: 'multiple-choice',
    content: 'Choose the correct form: "She wished she _____ more time to finish the project."',
    correctAnswer: 'had had',
    options: ['had', 'had had', 'would have', 'has had'],
    explanation: 'Past perfect after "wish" for regret about the past.',
    planet: 'earth',
    level: 7,
    questionNumber: 7,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-8',
    type: 'fill-in-blank',
    content: 'Complete: "The report _____ (complete) by the time the deadline _____ (arrive)."',
    correctAnswer: 'had been completed, arrived',
    explanation: 'Past perfect passive for action completed before another past action.',
    planet: 'earth',
    level: 7,
    questionNumber: 8,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-9',
    type: 'multiple-choice',
    content: 'Select the correct form: "The children _____ to bed after they _____ their homework."',
    correctAnswer: 'went, had finished',
    options: ['went, finished', 'went, had finished', 'had gone, finished', 'were going, finished'],
    explanation: 'Past perfect for the earlier action, simple past for the later action.',
    planet: 'earth',
    level: 7,
    questionNumber: 9,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-10',
    type: 'multiple-choice',
    content: 'Choose the correct passive form: "The letters _____ delivered when I got home."',
    correctAnswer: 'were being',
    options: ['were', 'were being', 'had been', 'was being'],
    explanation: 'Past continuous passive for ongoing action at a specific time.',
    planet: 'earth',
    level: 7,
    questionNumber: 10,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-11',
    type: 'multiple-choice',
    content: 'Select the correct form: "He acted as if he _____ the answer all along."',
    correctAnswer: 'had known',
    options: ['knew', 'had known', 'knows', 'would know'],
    explanation: 'Past perfect after "as if" for hypothetical past situations.',
    planet: 'earth',
    level: 7,
    questionNumber: 11,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-12',
    type: 'fill-in-blank',
    content: 'Complete: "The cake _____ (bake) when the guests _____ (arrive)."',
    correctAnswer: 'was being baked, arrived',
    explanation: 'Past continuous passive for ongoing action interrupted by another action.',
    planet: 'earth',
    level: 7,
    questionNumber: 12,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-13',
    type: 'multiple-choice',
    content: 'Choose the correct form: "Had I known about the traffic, I _____ earlier."',
    correctAnswer: 'would have left',
    options: ['would leave', 'would have left', 'left', 'had left'],
    explanation: 'Inverted conditional with "would have" in the main clause.',
    planet: 'earth',
    level: 7,
    questionNumber: 13,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-14',
    type: 'multiple-choice',
    content: 'Select the correct passive form: "The windows _____ cleaned every week last year."',
    correctAnswer: 'were',
    options: ['were', 'were being', 'had been', 'was'],
    explanation: 'Simple past passive for repeated actions in the past.',
    planet: 'earth',
    level: 7,
    questionNumber: 14,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-15',
    type: 'correction',
    content: 'Correct the sentence: "The meeting was held by the manager in the conference room."',
    correctAnswer: 'The manager held the meeting in the conference room.',
    explanation: 'Active voice is clearer when the agent is important.',
    planet: 'earth',
    level: 7,
    questionNumber: 15,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-16',
    type: 'multiple-choice',
    content: 'Choose the correct form: "She spoke as though she _____ a native speaker."',
    correctAnswer: 'were',
    options: ['was', 'were', 'had been', 'would be'],
    explanation: 'Subjunctive "were" after "as though" for hypothetical situations.',
    planet: 'earth',
    level: 7,
    questionNumber: 16,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-17',
    type: 'fill-in-blank',
    content: 'Complete: "The building _____ (construct) for two years before it _____ (complete)."',
    correctAnswer: 'had been being constructed, was completed',
    explanation: 'Past perfect continuous passive for duration before completion.',
    planet: 'earth',
    level: 7,
    questionNumber: 17,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-18',
    type: 'multiple-choice',
    content: 'Select the correct form: "It\'s time we _____ home."',
    correctAnswer: 'went',
    options: ['go', 'went', 'had gone', 'would go'],
    explanation: 'Past tense after "It\'s time" for present necessity.',
    planet: 'earth',
    level: 7,
    questionNumber: 18,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-19',
    type: 'multiple-choice',
    content: 'Choose the correct passive form: "The problem _____ solved by the time the meeting ended."',
    correctAnswer: 'had been',
    options: ['was', 'had been', 'was being', 'has been'],
    explanation: 'Past perfect passive for action completed before another past action.',
    planet: 'earth',
    level: 7,
    questionNumber: 19,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-20',
    type: 'multiple-choice',
    content: 'Select the correct form: "I\'d rather you _____ me the truth yesterday."',
    correctAnswer: 'had told',
    options: ['told', 'had told', 'tell', 'would tell'],
    explanation: 'Past perfect after "I\'d rather" for regret about the past.',
    planet: 'earth',
    level: 7,
    questionNumber: 20,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-21',
    type: 'fill-in-blank',
    content: 'Complete: "The news _____ (broadcast) when the power _____ (go) out."',
    correctAnswer: 'was being broadcast, went',
    explanation: 'Past continuous passive interrupted by simple past.',
    planet: 'earth',
    level: 7,
    questionNumber: 21,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-22',
    type: 'multiple-choice',
    content: 'Choose the correct form: "Hardly _____ the door when the phone rang."',
    correctAnswer: 'had I opened',
    options: ['I opened', 'had I opened', 'I had opened', 'did I open'],
    explanation: 'Inverted word order after "Hardly" with past perfect.',
    planet: 'earth',
    level: 7,
    questionNumber: 22,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-23',
    type: 'multiple-choice',
    content: 'Select the correct passive form: "The car _____ repaired when I went to pick it up."',
    correctAnswer: 'was being',
    options: ['was', 'was being', 'had been', 'has been'],
    explanation: 'Past continuous passive for ongoing action at a specific time.',
    planet: 'earth',
    level: 7,
    questionNumber: 23,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-24',
    type: 'correction',
    content: 'Correct the sentence: "If I would have known, I would have come earlier."',
    correctAnswer: 'If I had known, I would have come earlier.',
    explanation: 'Use past perfect, not "would have," in the if-clause of third conditional.',
    planet: 'earth',
    level: 7,
    questionNumber: 24,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-25',
    type: 'multiple-choice',
    content: 'Choose the correct form: "She looked as if she _____ crying."',
    correctAnswer: 'had been',
    options: ['was', 'had been', 'has been', 'would be'],
    explanation: 'Past perfect continuous after "as if" for recent past activity.',
    planet: 'earth',
    level: 7,
    questionNumber: 25,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-26',
    type: 'fill-in-blank',
    content: 'Complete: "The message _____ (deliver) before the recipient _____ (leave) the office."',
    correctAnswer: 'had been delivered, left',
    explanation: 'Past perfect passive for action completed before another past action.',
    planet: 'earth',
    level: 7,
    questionNumber: 26,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-27',
    type: 'multiple-choice',
    content: 'Select the correct form: "Never _____ such a beautiful sunset before."',
    correctAnswer: 'had I seen',
    options: ['I saw', 'had I seen', 'I had seen', 'did I see'],
    explanation: 'Inverted word order after "Never" with past perfect.',
    planet: 'earth',
    level: 7,
    questionNumber: 27,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-28',
    type: 'multiple-choice',
    content: 'Choose the correct passive form: "The decision _____ made after careful consideration."',
    correctAnswer: 'was',
    options: ['was', 'had been', 'was being', 'has been'],
    explanation: 'Simple past passive for completed action.',
    planet: 'earth',
    level: 7,
    questionNumber: 28,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-29',
    type: 'multiple-choice',
    content: 'Select the correct form: "I wish I _____ more attention in class."',
    correctAnswer: 'had paid',
    options: ['paid', 'had paid', 'would pay', 'pay'],
    explanation: 'Past perfect after "wish" for regret about the past.',
    planet: 'earth',
    level: 7,
    questionNumber: 29,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-30',
    type: 'fill-in-blank',
    content: 'Complete: "The play _____ (perform) when the lights _____ (go) out."',
    correctAnswer: 'was being performed, went',
    explanation: 'Past continuous passive interrupted by simple past.',
    planet: 'earth',
    level: 7,
    questionNumber: 30,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-31',
    type: 'multiple-choice',
    content: 'Choose the correct form: "Scarcely _____ when it started to rain."',
    correctAnswer: 'had we arrived',
    options: ['we arrived', 'had we arrived', 'we had arrived', 'did we arrive'],
    explanation: 'Inverted word order after "Scarcely" with past perfect.',
    planet: 'earth',
    level: 7,
    questionNumber: 31,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-32',
    type: 'correction',
    content: 'Correct the sentence: "The book was written by the author in 1995."',
    correctAnswer: 'The author wrote the book in 1995.',
    explanation: 'Active voice is often clearer and more direct.',
    planet: 'earth',
    level: 7,
    questionNumber: 32,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-33',
    type: 'multiple-choice',
    content: 'Select the correct passive form: "The results _____ announced by the time we arrived."',
    correctAnswer: 'had been',
    options: ['were', 'had been', 'were being', 'have been'],
    explanation: 'Past perfect passive for action completed before another past action.',
    planet: 'earth',
    level: 7,
    questionNumber: 33,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-34',
    type: 'multiple-choice',
    content: 'Choose the correct form: "He treated me as if I _____ a child."',
    correctAnswer: 'were',
    options: ['was', 'were', 'am', 'would be'],
    explanation: 'Subjunctive "were" after "as if" for hypothetical situations.',
    planet: 'earth',
    level: 7,
    questionNumber: 34,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-35',
    type: 'fill-in-blank',
    content: 'Complete: "The project _____ (discuss) for hours before a decision _____ (make)."',
    correctAnswer: 'had been being discussed, was made',
    explanation: 'Past perfect continuous passive for duration before a decision.',
    planet: 'earth',
    level: 7,
    questionNumber: 35,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-36',
    type: 'multiple-choice',
    content: 'Select the correct form: "Only after the exam _____ that I had made a mistake."',
    correctAnswer: 'did I realize',
    options: ['I realized', 'did I realize', 'I did realize', 'had I realized'],
    explanation: 'Inverted word order after "Only after" with simple past.',
    planet: 'earth',
    level: 7,
    questionNumber: 36,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-37',
    type: 'multiple-choice',
    content: 'Choose the correct passive form: "The song _____ recorded in a famous studio."',
    correctAnswer: 'was',
    options: ['was', 'had been', 'was being', 'has been'],
    explanation: 'Simple past passive for completed action.',
    planet: 'earth',
    level: 7,
    questionNumber: 37,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-38',
    type: 'multiple-choice',
    content: 'Select the correct form: "If only I _____ harder for the test."',
    correctAnswer: 'had studied',
    options: ['studied', 'had studied', 'would study', 'study'],
    explanation: 'Past perfect after "If only" for regret about the past.',
    planet: 'earth',
    level: 7,
    questionNumber: 38,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-39',
    type: 'correction',
    content: 'Correct the sentence: "The dinner was being cooked by my mother when we arrived."',
    correctAnswer: 'My mother was cooking dinner when we arrived.',
    explanation: 'Active voice is more natural and direct.',
    planet: 'earth',
    level: 7,
    questionNumber: 39,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-40',
    type: 'fill-in-blank',
    content: 'Complete: "The speech _____ (write) before the event _____ (begin)."',
    correctAnswer: 'had been written, began',
    explanation: 'Past perfect passive for action completed before another past action.',
    planet: 'earth',
    level: 7,
    questionNumber: 40,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-41',
    type: 'multiple-choice',
    content: 'Choose the correct form: "Little _____ that this would be our last meeting."',
    correctAnswer: 'did we know',
    options: ['we knew', 'did we know', 'we did know', 'had we known'],
    explanation: 'Inverted word order after "Little" with simple past.',
    planet: 'earth',
    level: 7,
    questionNumber: 41,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-42',
    type: 'multiple-choice',
    content: 'Select the correct passive form: "The package _____ delivered while I was out."',
    correctAnswer: 'was',
    options: ['was', 'was being', 'had been', 'has been'],
    explanation: 'Simple past passive for completed action during a time period.',
    planet: 'earth',
    level: 7,
    questionNumber: 42,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-43',
    type: 'multiple-choice',
    content: 'Choose the correct form: "She behaved as though nothing _____ happened."',
    correctAnswer: 'had',
    options: ['has', 'had', 'would have', 'was'],
    explanation: 'Past perfect after "as though" for hypothetical past situations.',
    planet: 'earth',
    level: 7,
    questionNumber: 43,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-44',
    type: 'fill-in-blank',
    content: 'Complete: "The film _____ (edit) when the director _____ (change) his mind."',
    correctAnswer: 'was being edited, changed',
    explanation: 'Past continuous passive interrupted by simple past.',
    planet: 'earth',
    level: 7,
    questionNumber: 44,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-45',
    type: 'multiple-choice',
    content: 'Select the correct form: "Not until midnight _____ the party end."',
    correctAnswer: 'did',
    options: ['did', 'was', 'had', 'would'],
    explanation: 'Inverted word order after "Not until" with simple past.',
    planet: 'earth',
    level: 7,
    questionNumber: 45,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-46',
    type: 'correction',
    content: 'Correct the sentence: "The mistake was made by me accidentally."',
    correctAnswer: 'I made the mistake accidentally.',
    explanation: 'Active voice is clearer when taking responsibility.',
    planet: 'earth',
    level: 7,
    questionNumber: 46,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-47',
    type: 'multiple-choice',
    content: 'Choose the correct passive form: "The contract _____ signed before the deadline."',
    correctAnswer: 'had been',
    options: ['was', 'had been', 'was being', 'has been'],
    explanation: 'Past perfect passive for action completed before a past deadline.',
    planet: 'earth',
    level: 7,
    questionNumber: 47,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-48',
    type: 'multiple-choice',
    content: 'Select the correct form: "Suppose you _____ a million dollars, what would you do?"',
    correctAnswer: 'had',
    options: ['have', 'had', 'would have', 'has'],
    explanation: 'Past tense after "Suppose" for hypothetical situations.',
    planet: 'earth',
    level: 7,
    questionNumber: 48,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-49',
    type: 'fill-in-blank',
    content: 'Complete: "The exhibition _____ (prepare) for months before it _____ (open)."',
    correctAnswer: 'had been being prepared, opened',
    explanation: 'Past perfect continuous passive for duration before opening.',
    planet: 'earth',
    level: 7,
    questionNumber: 49,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-7-50',
    type: 'multiple-choice',
    content: 'Choose the correct form: "Rarely _____ such dedication in a student."',
    correctAnswer: 'have I seen',
    options: ['I have seen', 'have I seen', 'I saw', 'did I see'],
    explanation: 'Inverted word order after "Rarely" with present perfect for experience.',
    planet: 'earth',
    level: 7,
    questionNumber: 50,
    points: 10,
    difficulty: 'advanced'
  }
]; 