import { Exercise } from '@/types/curriculum';

export const earthLevel9Questions: Exercise[] = [
  {
    id: 'earth-9-1',
    type: 'multiple-choice',
    content: 'Choose the correct complex tense: "By the time the project _____, we will have been working on it for two years."',
    correctAnswer: 'is completed',
    options: ['completes', 'is completed', 'will be completed', 'has been completed'],
    explanation: 'Present passive in time clauses for future reference.',
    planet: 'earth',
    level: 9,
    questionNumber: 1,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-2',
    type: 'fill-in-blank',
    content: 'Complete: "Had it not been for your intervention, the situation _____ (become) much worse."',
    correctAnswer: 'would have become',
    explanation: 'Inverted third conditional with "had it not been for".',
    planet: 'earth',
    level: 9,
    questionNumber: 2,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-3',
    type: 'multiple-choice',
    content: 'Select the correct form: "The research _____ for publication when new evidence emerged."',
    correctAnswer: 'was being prepared',
    options: ['was preparing', 'was being prepared', 'had been prepared', 'would be prepared'],
    explanation: 'Past continuous passive shows ongoing action interrupted by another event.',
    planet: 'earth',
    level: 9,
    questionNumber: 3,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-4',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "I would rather _____ informed earlier about the changes."',
    correctAnswer: 'have been',
    options: ['be', 'have been', 'had been', 'being'],
    explanation: '"Would rather" + perfect infinitive for past regret.',
    planet: 'earth',
    level: 9,
    questionNumber: 4,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-5',
    type: 'multiple-choice',
    content: 'Select the correct form: "The building _____ demolished next month, but plans have changed."',
    correctAnswer: 'was to have been',
    options: ['was to be', 'was to have been', 'would have been', 'should have been'],
    explanation: '"Was to have been" indicates a past arrangement that didn\'t happen.',
    planet: 'earth',
    level: 9,
    questionNumber: 5,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-6',
    type: 'fill-in-blank',
    content: 'Complete: "Not only _____ (the company/lose) money, but it also lost credibility."',
    correctAnswer: 'did the company lose',
    explanation: 'Inversion after "not only" requires auxiliary verb.',
    planet: 'earth',
    level: 9,
    questionNumber: 6,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-7',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The proposal _____ consideration for months before being rejected."',
    correctAnswer: 'had been under',
    options: ['was under', 'had been under', 'has been under', 'would be under'],
    explanation: 'Past perfect shows duration before another past event.',
    planet: 'earth',
    level: 9,
    questionNumber: 7,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-8',
    type: 'multiple-choice',
    content: 'Select the correct form: "Were the circumstances different, I _____ a different decision."',
    correctAnswer: 'would make',
    options: ['will make', 'would make', 'would have made', 'had made'],
    explanation: 'Inverted second conditional for present hypothetical situation.',
    planet: 'earth',
    level: 9,
    questionNumber: 8,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-9',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The data _____ analyzed when the computer crashed."',
    correctAnswer: 'was being',
    options: ['was', 'was being', 'had been', 'would be'],
    explanation: 'Past continuous passive for interrupted ongoing action.',
    planet: 'earth',
    level: 9,
    questionNumber: 9,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-10',
    type: 'fill-in-blank',
    content: 'Complete: "Should the weather _____ (improve), we will proceed with the outdoor event."',
    correctAnswer: 'improve',
    explanation: 'Inverted conditional uses base form after "should".',
    planet: 'earth',
    level: 9,
    questionNumber: 10,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-11',
    type: 'multiple-choice',
    content: 'Select the correct form: "The manuscript _____ to the publisher by the deadline."',
    correctAnswer: 'will have been submitted',
    options: ['will submit', 'will be submitted', 'will have been submitted', 'would be submitted'],
    explanation: 'Future perfect passive shows completion before a future point.',
    planet: 'earth',
    level: 9,
    questionNumber: 11,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-12',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "I wish the meeting _____ postponed yesterday."',
    correctAnswer: 'had been',
    options: ['was', 'had been', 'would be', 'could be'],
    explanation: 'Wish + past perfect passive for regret about past events.',
    planet: 'earth',
    level: 9,
    questionNumber: 12,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-13',
    type: 'correction',
    content: 'Correct the sentence: "If the report would have been completed on time, we could have proceeded."',
    correctAnswer: 'If the report had been completed on time, we could have proceeded.',
    explanation: 'Third conditional uses past perfect, not "would have" in the if-clause.',
    planet: 'earth',
    level: 9,
    questionNumber: 13,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-14',
    type: 'multiple-choice',
    content: 'Select the correct form: "The evidence suggests that the crime _____ committed between 10 and 11 PM."',
    correctAnswer: 'was',
    options: ['is', 'was', 'has been', 'had been'],
    explanation: 'Past tense in reported speech when the reporting verb is present.',
    planet: 'earth',
    level: 9,
    questionNumber: 14,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-15',
    type: 'fill-in-blank',
    content: 'Complete: "Seldom _____ (such dedication/be) seen in young employees."',
    correctAnswer: 'has such dedication been',
    explanation: 'Inversion with "seldom" uses present perfect passive.',
    planet: 'earth',
    level: 9,
    questionNumber: 15,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-16',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The committee insisted that the proposal _____ reviewed again."',
    correctAnswer: 'be',
    options: ['is', 'was', 'be', 'would be'],
    explanation: 'Subjunctive mood uses base form after "insist that".',
    planet: 'earth',
    level: 9,
    questionNumber: 16,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-17',
    type: 'multiple-choice',
    content: 'Select the correct form: "The project _____ completion when funding was withdrawn."',
    correctAnswer: 'was nearing',
    options: ['neared', 'was nearing', 'had neared', 'would near'],
    explanation: 'Past continuous shows ongoing action interrupted by another event.',
    planet: 'earth',
    level: 9,
    questionNumber: 17,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-18',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "It is essential that every participant _____ the safety guidelines."',
    correctAnswer: 'follow',
    options: ['follows', 'followed', 'follow', 'will follow'],
    explanation: 'Subjunctive mood uses base form after "essential that".',
    planet: 'earth',
    level: 9,
    questionNumber: 18,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-19',
    type: 'fill-in-blank',
    content: 'Complete: "Little _____ (we/know) that this decision would change everything."',
    correctAnswer: 'did we know',
    explanation: 'Inversion with "little" requires auxiliary "did" for past tense.',
    planet: 'earth',
    level: 9,
    questionNumber: 19,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-20',
    type: 'multiple-choice',
    content: 'Select the correct form: "The results _____ published if the peer review had been favorable."',
    correctAnswer: 'would have been',
    options: ['would be', 'would have been', 'will be', 'had been'],
    explanation: 'Third conditional passive: would have been + past participle.',
    planet: 'earth',
    level: 9,
    questionNumber: 20,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-21',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The software _____ updated regularly to ensure security."',
    correctAnswer: 'needs to be',
    options: ['needs updating', 'needs to be', 'needs being', 'needs to have been'],
    explanation: '"Needs to be" + past participle for passive necessity.',
    planet: 'earth',
    level: 9,
    questionNumber: 21,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-22',
    type: 'multiple-choice',
    content: 'Select the correct form: "The contract _____ signed by all parties before implementation."',
    correctAnswer: 'must be',
    options: ['must', 'must be', 'must have', 'must have been'],
    explanation: 'Modal passive for present necessity.',
    planet: 'earth',
    level: 9,
    questionNumber: 22,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-23',
    type: 'correction',
    content: 'Correct the sentence: "The problem should have been being addressed earlier."',
    correctAnswer: 'The problem should have been addressed earlier.',
    explanation: 'Modal perfect passive: should have been + past participle.',
    planet: 'earth',
    level: 9,
    questionNumber: 23,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-24',
    type: 'fill-in-blank',
    content: 'Complete: "Never before _____ (such a comprehensive study/be) conducted on this topic."',
    correctAnswer: 'has such a comprehensive study been',
    explanation: 'Inversion with "never before" uses present perfect passive.',
    planet: 'earth',
    level: 9,
    questionNumber: 24,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-25',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The regulations require that all documents _____ in triplicate."',
    correctAnswer: 'be submitted',
    options: ['are submitted', 'be submitted', 'will be submitted', 'should submit'],
    explanation: 'Subjunctive passive: base form "be" + past participle.',
    planet: 'earth',
    level: 9,
    questionNumber: 25,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-26',
    type: 'multiple-choice',
    content: 'Select the correct form: "The experiment _____ when the equipment malfunctioned."',
    correctAnswer: 'was being conducted',
    options: ['was conducting', 'was being conducted', 'had been conducted', 'would be conducted'],
    explanation: 'Past continuous passive for interrupted ongoing action.',
    planet: 'earth',
    level: 9,
    questionNumber: 26,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-27',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "It is imperative that the issue _____ immediately."',
    correctAnswer: 'be addressed',
    options: ['is addressed', 'be addressed', 'will be addressed', 'should address'],
    explanation: 'Subjunctive passive after "imperative that".',
    planet: 'earth',
    level: 9,
    questionNumber: 27,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-28',
    type: 'fill-in-blank',
    content: 'Complete: "Only after the investigation _____ (complete) will the results be announced."',
    correctAnswer: 'is completed',
    explanation: 'Present passive in time clauses for future reference.',
    planet: 'earth',
    level: 9,
    questionNumber: 28,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-29',
    type: 'multiple-choice',
    content: 'Select the correct form: "The policy _____ implemented gradually over the next year."',
    correctAnswer: 'is to be',
    options: ['will', 'is to be', 'is being', 'will have been'],
    explanation: '"Is to be" indicates planned future passive action.',
    planet: 'earth',
    level: 9,
    questionNumber: 29,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-30',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The documents _____ destroyed if they had contained sensitive information."',
    correctAnswer: 'would have been',
    options: ['would be', 'would have been', 'will be', 'had been'],
    explanation: 'Third conditional passive for hypothetical past situation.',
    planet: 'earth',
    level: 9,
    questionNumber: 30,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-31',
    type: 'multiple-choice',
    content: 'Select the correct form: "The meeting _____ postponed until further notice."',
    correctAnswer: 'has been',
    options: ['has', 'has been', 'was', 'will be'],
    explanation: 'Present perfect passive for recent action with present relevance.',
    planet: 'earth',
    level: 9,
    questionNumber: 31,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-32',
    type: 'correction',
    content: 'Correct the sentence: "The report is being written by the team since last week."',
    correctAnswer: 'The report has been being written by the team since last week.',
    explanation: 'Present perfect continuous passive for ongoing action with duration.',
    planet: 'earth',
    level: 9,
    questionNumber: 32,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-33',
    type: 'fill-in-blank',
    content: 'Complete: "Hardly _____ (the announcement/make) when protests began."',
    correctAnswer: 'had the announcement been made',
    explanation: 'Inversion with "hardly" uses past perfect passive.',
    planet: 'earth',
    level: 9,
    questionNumber: 33,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-34',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The proposal _____ consideration by the board next week."',
    correctAnswer: 'will be given',
    options: ['will give', 'will be given', 'will have given', 'will be giving'],
    explanation: 'Future passive for planned action.',
    planet: 'earth',
    level: 9,
    questionNumber: 34,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-35',
    type: 'multiple-choice',
    content: 'Select the correct form: "The system _____ upgraded when the power failure occurred."',
    correctAnswer: 'was being',
    options: ['was', 'was being', 'had been', 'would be'],
    explanation: 'Past continuous passive for interrupted ongoing action.',
    planet: 'earth',
    level: 9,
    questionNumber: 35,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-36',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "It is crucial that the data _____ verified before publication."',
    correctAnswer: 'be',
    options: ['is', 'be', 'will be', 'should be'],
    explanation: 'Subjunctive passive uses base form "be".',
    planet: 'earth',
    level: 9,
    questionNumber: 36,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-37',
    type: 'fill-in-blank',
    content: 'Complete: "Not until the evidence _____ (examine) thoroughly will we reach a conclusion."',
    correctAnswer: 'has been examined',
    explanation: 'Present perfect passive in time clauses for future reference.',
    planet: 'earth',
    level: 9,
    questionNumber: 37,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-38',
    type: 'multiple-choice',
    content: 'Select the correct form: "The building _____ renovated for six months when the fire occurred."',
    correctAnswer: 'had been being',
    options: ['was being', 'had been being', 'has been being', 'would be being'],
    explanation: 'Past perfect continuous passive for duration before a past event.',
    planet: 'earth',
    level: 9,
    questionNumber: 38,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-39',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The medication _____ taken with food to avoid side effects."',
    correctAnswer: 'should be',
    options: ['should', 'should be', 'should have', 'should have been'],
    explanation: 'Modal passive for recommendation.',
    planet: 'earth',
    level: 9,
    questionNumber: 39,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-40',
    type: 'multiple-choice',
    content: 'Select the correct form: "The conference _____ attended by experts from around the world."',
    correctAnswer: 'was',
    options: ['was', 'was being', 'had been', 'would be'],
    explanation: 'Simple past passive for completed action.',
    planet: 'earth',
    level: 9,
    questionNumber: 40,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-41',
    type: 'correction',
    content: 'Correct the sentence: "The problem could have been being solved earlier."',
    correctAnswer: 'The problem could have been solved earlier.',
    explanation: 'Modal perfect passive: could have been + past participle.',
    planet: 'earth',
    level: 9,
    questionNumber: 41,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-42',
    type: 'fill-in-blank',
    content: 'Complete: "Scarcely _____ (the project/begin) when complications arose."',
    correctAnswer: 'had the project begun',
    explanation: 'Inversion with "scarcely" uses past perfect.',
    planet: 'earth',
    level: 9,
    questionNumber: 42,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-43',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The results _____ published by the time you read this."',
    correctAnswer: 'will have been',
    options: ['will be', 'will have been', 'would be', 'would have been'],
    explanation: 'Future perfect passive for completion before a future point.',
    planet: 'earth',
    level: 9,
    questionNumber: 43,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-44',
    type: 'multiple-choice',
    content: 'Select the correct form: "The law requires that all vehicles _____ inspected annually."',
    correctAnswer: 'be',
    options: ['are', 'be', 'will be', 'should be'],
    explanation: 'Subjunctive passive after "requires that".',
    planet: 'earth',
    level: 9,
    questionNumber: 44,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-45',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The manuscript _____ reviewed by three experts before acceptance."',
    correctAnswer: 'must be',
    options: ['must', 'must be', 'must have', 'must have been'],
    explanation: 'Modal passive for necessity.',
    planet: 'earth',
    level: 9,
    questionNumber: 45,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-46',
    type: 'fill-in-blank',
    content: 'Complete: "Only when all conditions _____ (meet) will the contract be valid."',
    correctAnswer: 'are met',
    explanation: 'Present passive in conditional clauses for future reference.',
    planet: 'earth',
    level: 9,
    questionNumber: 46,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-47',
    type: 'multiple-choice',
    content: 'Select the correct form: "The decision _____ made if more information had been available."',
    correctAnswer: 'might have been',
    options: ['might be', 'might have been', 'could be', 'would be'],
    explanation: 'Modal perfect passive for past possibility.',
    planet: 'earth',
    level: 9,
    questionNumber: 47,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-48',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The equipment _____ maintained regularly to ensure optimal performance."',
    correctAnswer: 'needs to be',
    options: ['needs', 'needs to be', 'needs being', 'needs to have been'],
    explanation: '"Needs to be" + past participle for passive necessity.',
    planet: 'earth',
    level: 9,
    questionNumber: 48,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-49',
    type: 'correction',
    content: 'Correct the sentence: "The issue should be being addressed by the management."',
    correctAnswer: 'The issue should be addressed by the management.',
    explanation: 'Modal passive: should be + past participle.',
    planet: 'earth',
    level: 9,
    questionNumber: 49,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-9-50',
    type: 'fill-in-blank',
    content: 'Complete: "Under no circumstances _____ (confidential information/share) with unauthorized personnel."',
    correctAnswer: 'should confidential information be shared',
    explanation: 'Negative inversion with modal passive.',
    planet: 'earth',
    level: 9,
    questionNumber: 50,
    points: 10,
    difficulty: 'advanced'
  }
]; 