import { Exercise } from '@/types/curriculum';

export const earthLevel2Questions: Exercise[] = [
  {
    id: 'earth-2-1',
    type: 'multiple-choice',
    content: 'Which word is an adjective?',
    correctAnswer: 'beautiful',
    options: ['beautiful', 'run', 'quickly', 'table'],
    explanation: 'Beautiful is an adjective because it describes a noun.',
    planet: 'earth',
    level: 2,
    questionNumber: 1,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-2',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "The _____ dog barked loudly."',
    correctAnswer: 'big',
    options: ['big', 'run', 'loudly', 'barked'],
    explanation: 'Big is an adjective that describes the size of the dog.',
    planet: 'earth',
    level: 2,
    questionNumber: 2,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-3',
    type: 'multiple-choice',
    content: 'What is the comparative form of "tall"?',
    correctAnswer: 'taller',
    options: ['tall', 'taller', 'tallest', 'more tall'],
    explanation: 'Taller is the comparative form used to compare two things.',
    planet: 'earth',
    level: 2,
    questionNumber: 3,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-4',
    type: 'multiple-choice',
    content: 'What is the superlative form of "small"?',
    correctAnswer: 'smallest',
    options: ['small', 'smaller', 'smallest', 'more small'],
    explanation: 'Smallest is the superlative form used to compare three or more things.',
    planet: 'earth',
    level: 2,
    questionNumber: 4,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-5',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "She wore a _____ dress."',
    correctAnswer: 'red',
    options: ['red', 'quickly', 'running', 'happily'],
    explanation: 'Red is an adjective that describes the color of the dress.',
    planet: 'earth',
    level: 2,
    questionNumber: 5,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-6',
    type: 'multiple-choice',
    content: 'Which word describes how something feels?',
    correctAnswer: 'soft',
    options: ['soft', 'jump', 'yesterday', 'under'],
    explanation: 'Soft is a tactile adjective that describes texture.',
    planet: 'earth',
    level: 2,
    questionNumber: 6,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-7',
    type: 'multiple-choice',
    content: 'What is the comparative form of "good"?',
    correctAnswer: 'better',
    options: ['good', 'better', 'best', 'gooder'],
    explanation: 'Better is the irregular comparative form of good.',
    planet: 'earth',
    level: 2,
    questionNumber: 7,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-8',
    type: 'multiple-choice',
    content: 'What is the superlative form of "bad"?',
    correctAnswer: 'worst',
    options: ['bad', 'worse', 'worst', 'baddest'],
    explanation: 'Worst is the irregular superlative form of bad.',
    planet: 'earth',
    level: 2,
    questionNumber: 8,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-9',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "The _____ cat slept peacefully."',
    correctAnswer: 'lazy',
    options: ['lazy', 'sleep', 'peacefully', 'slept'],
    explanation: 'Lazy is an adjective that describes the cat\'s behavior.',
    planet: 'earth',
    level: 2,
    questionNumber: 9,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-10',
    type: 'multiple-choice',
    content: 'Which adjective describes temperature?',
    correctAnswer: 'hot',
    options: ['hot', 'run', 'quickly', 'table'],
    explanation: 'Hot is an adjective that describes temperature.',
    planet: 'earth',
    level: 2,
    questionNumber: 10,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-11',
    type: 'multiple-choice',
    content: 'What is the comparative form of "happy"?',
    correctAnswer: 'happier',
    options: ['happy', 'happier', 'happiest', 'more happy'],
    explanation: 'Happier is the comparative form (y changes to i + er).',
    planet: 'earth',
    level: 2,
    questionNumber: 11,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-12',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "We live in a _____ house."',
    correctAnswer: 'old',
    options: ['old', 'living', 'quickly', 'house'],
    explanation: 'Old is an adjective that describes the age of the house.',
    planet: 'earth',
    level: 2,
    questionNumber: 12,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-13',
    type: 'multiple-choice',
    content: 'Which adjective describes shape?',
    correctAnswer: 'round',
    options: ['round', 'running', 'loudly', 'yesterday'],
    explanation: 'Round is an adjective that describes shape.',
    planet: 'earth',
    level: 2,
    questionNumber: 13,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-14',
    type: 'multiple-choice',
    content: 'What is the superlative form of "funny"?',
    correctAnswer: 'funniest',
    options: ['funny', 'funnier', 'funniest', 'most funny'],
    explanation: 'Funniest is the superlative form (y changes to i + est).',
    planet: 'earth',
    level: 2,
    questionNumber: 14,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-15',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "The _____ flowers smell wonderful."',
    correctAnswer: 'fresh',
    options: ['fresh', 'smell', 'wonderful', 'flowers'],
    explanation: 'Fresh is an adjective that describes the condition of the flowers.',
    planet: 'earth',
    level: 2,
    questionNumber: 15,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-16',
    type: 'multiple-choice',
    content: 'Which word describes personality?',
    correctAnswer: 'kind',
    options: ['kind', 'running', 'table', 'quickly'],
    explanation: 'Kind is an adjective that describes someone\'s personality.',
    planet: 'earth',
    level: 2,
    questionNumber: 16,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-17',
    type: 'multiple-choice',
    content: 'What is the comparative form of "fast"?',
    correctAnswer: 'faster',
    options: ['fast', 'faster', 'fastest', 'more fast'],
    explanation: 'Faster is the comparative form of fast.',
    planet: 'earth',
    level: 2,
    questionNumber: 17,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-18',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "I need a _____ pencil."',
    correctAnswer: 'sharp',
    options: ['sharp', 'writing', 'need', 'pencil'],
    explanation: 'Sharp is an adjective that describes the condition of the pencil.',
    planet: 'earth',
    level: 2,
    questionNumber: 18,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-19',
    type: 'multiple-choice',
    content: 'Which adjective describes sound?',
    correctAnswer: 'loud',
    options: ['loud', 'hearing', 'quickly', 'yesterday'],
    explanation: 'Loud is an adjective that describes the volume of sound.',
    planet: 'earth',
    level: 2,
    questionNumber: 19,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-20',
    type: 'multiple-choice',
    content: 'What is the superlative form of "big"?',
    correctAnswer: 'biggest',
    options: ['big', 'bigger', 'biggest', 'most big'],
    explanation: 'Biggest is the superlative form (double the consonant + est).',
    planet: 'earth',
    level: 2,
    questionNumber: 20,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-21',
    type: 'multiple-choice',
    content: 'Choose the correct comparative: "This book is _____ than that one."',
    correctAnswer: 'more interesting',
    options: ['interesting', 'more interesting', 'most interesting', 'interestinger'],
    explanation: 'Long adjectives use "more" for comparative form.',
    planet: 'earth',
    level: 2,
    questionNumber: 21,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-22',
    type: 'multiple-choice',
    content: 'Which adjective describes taste?',
    correctAnswer: 'sweet',
    options: ['sweet', 'eating', 'quickly', 'food'],
    explanation: 'Sweet is an adjective that describes taste.',
    planet: 'earth',
    level: 2,
    questionNumber: 22,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-23',
    type: 'multiple-choice',
    content: 'What is the comparative form of "easy"?',
    correctAnswer: 'easier',
    options: ['easy', 'easier', 'easiest', 'more easy'],
    explanation: 'Easier is the comparative form (y changes to i + er).',
    planet: 'earth',
    level: 2,
    questionNumber: 23,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-24',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "She has _____ hair."',
    correctAnswer: 'long',
    options: ['long', 'having', 'hair', 'she'],
    explanation: 'Long is an adjective that describes the length of hair.',
    planet: 'earth',
    level: 2,
    questionNumber: 24,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-25',
    type: 'multiple-choice',
    content: 'Which word describes weather?',
    correctAnswer: 'sunny',
    options: ['sunny', 'weather', 'outside', 'walking'],
    explanation: 'Sunny is an adjective that describes weather conditions.',
    planet: 'earth',
    level: 2,
    questionNumber: 25,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-26',
    type: 'fill-in-blank',
    content: 'Complete: "The elephant is _____ (big) than the mouse."',
    correctAnswer: 'bigger',
    explanation: 'Use the comparative form "bigger" to compare two animals.',
    planet: 'earth',
    level: 2,
    questionNumber: 26,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-27',
    type: 'fill-in-blank',
    content: 'Complete: "This is the _____ (tall) building in the city."',
    correctAnswer: 'tallest',
    explanation: 'Use the superlative form "tallest" when comparing more than two things.',
    planet: 'earth',
    level: 2,
    questionNumber: 27,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-28',
    type: 'multiple-choice',
    content: 'What is the superlative form of "beautiful"?',
    correctAnswer: 'most beautiful',
    options: ['beautiful', 'more beautiful', 'most beautiful', 'beautifulest'],
    explanation: 'Long adjectives use "most" for superlative form.',
    planet: 'earth',
    level: 2,
    questionNumber: 28,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-29',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "We had a _____ time at the party."',
    correctAnswer: 'wonderful',
    options: ['wonderful', 'having', 'party', 'time'],
    explanation: 'Wonderful is an adjective that describes the quality of time.',
    planet: 'earth',
    level: 2,
    questionNumber: 29,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-30',
    type: 'multiple-choice',
    content: 'Which adjective describes age?',
    correctAnswer: 'young',
    options: ['young', 'running', 'quickly', 'person'],
    explanation: 'Young is an adjective that describes age.',
    planet: 'earth',
    level: 2,
    questionNumber: 30,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-31',
    type: 'fill-in-blank',
    content: 'Complete: "Today is _____ (cold) than yesterday."',
    correctAnswer: 'colder',
    explanation: 'Use the comparative form "colder" to compare two days.',
    planet: 'earth',
    level: 2,
    questionNumber: 31,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-32',
    type: 'multiple-choice',
    content: 'What is the comparative form of "little"?',
    correctAnswer: 'less',
    options: ['little', 'less', 'least', 'littler'],
    explanation: 'Less is the irregular comparative form of little.',
    planet: 'earth',
    level: 2,
    questionNumber: 32,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-33',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "The _____ baby is sleeping."',
    correctAnswer: 'tiny',
    options: ['tiny', 'sleeping', 'baby', 'is'],
    explanation: 'Tiny is an adjective that describes the size of the baby.',
    planet: 'earth',
    level: 2,
    questionNumber: 33,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-34',
    type: 'multiple-choice',
    content: 'Which word describes emotion?',
    correctAnswer: 'excited',
    options: ['excited', 'running', 'table', 'quickly'],
    explanation: 'Excited is an adjective that describes an emotional state.',
    planet: 'earth',
    level: 2,
    questionNumber: 34,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-35',
    type: 'fill-in-blank',
    content: 'Complete: "She is the _____ (smart) student in class."',
    correctAnswer: 'smartest',
    explanation: 'Use the superlative form "smartest" when comparing more than two students.',
    planet: 'earth',
    level: 2,
    questionNumber: 35,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-36',
    type: 'multiple-choice',
    content: 'What is the superlative form of "far"?',
    correctAnswer: 'farthest',
    options: ['far', 'farther', 'farthest', 'most far'],
    explanation: 'Farthest is the irregular superlative form of far.',
    planet: 'earth',
    level: 2,
    questionNumber: 36,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-37',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "I bought some _____ apples."',
    correctAnswer: 'delicious',
    options: ['delicious', 'bought', 'apples', 'some'],
    explanation: 'Delicious is an adjective that describes the taste of apples.',
    planet: 'earth',
    level: 2,
    questionNumber: 37,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-38',
    type: 'multiple-choice',
    content: 'Which adjective describes texture?',
    correctAnswer: 'smooth',
    options: ['smooth', 'touching', 'quickly', 'surface'],
    explanation: 'Smooth is an adjective that describes how something feels.',
    planet: 'earth',
    level: 2,
    questionNumber: 38,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-39',
    type: 'fill-in-blank',
    content: 'Complete: "This puzzle is _____ (difficult) than the last one."',
    correctAnswer: 'more difficult',
    explanation: 'Long adjectives use "more" for comparative form.',
    planet: 'earth',
    level: 2,
    questionNumber: 39,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-40',
    type: 'multiple-choice',
    content: 'What is the comparative form of "many"?',
    correctAnswer: 'more',
    options: ['many', 'more', 'most', 'morer'],
    explanation: 'More is the irregular comparative form of many.',
    planet: 'earth',
    level: 2,
    questionNumber: 40,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-41',
    type: 'correction',
    content: 'Correct the sentence: "She is the most tall girl in class."',
    correctAnswer: 'She is the tallest girl in class.',
    explanation: 'Short adjectives use -est for superlative, not "most".',
    planet: 'earth',
    level: 2,
    questionNumber: 41,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-42',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "We saw a _____ movie last night."',
    correctAnswer: 'scary',
    options: ['scary', 'saw', 'movie', 'night'],
    explanation: 'Scary is an adjective that describes the type of movie.',
    planet: 'earth',
    level: 2,
    questionNumber: 42,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-43',
    type: 'multiple-choice',
    content: 'Which word describes color?',
    correctAnswer: 'purple',
    options: ['purple', 'coloring', 'paint', 'quickly'],
    explanation: 'Purple is an adjective that describes color.',
    planet: 'earth',
    level: 2,
    questionNumber: 43,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-44',
    type: 'fill-in-blank',
    content: 'Complete: "This is the _____ (expensive) car in the lot."',
    correctAnswer: 'most expensive',
    explanation: 'Long adjectives use "most" for superlative form.',
    planet: 'earth',
    level: 2,
    questionNumber: 44,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-45',
    type: 'multiple-choice',
    content: 'What is the superlative form of "good"?',
    correctAnswer: 'best',
    options: ['good', 'better', 'best', 'goodest'],
    explanation: 'Best is the irregular superlative form of good.',
    planet: 'earth',
    level: 2,
    questionNumber: 45,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-46',
    type: 'multiple-choice',
    content: 'Choose the correct adjective: "The _____ children played outside."',
    correctAnswer: 'happy',
    options: ['happy', 'played', 'children', 'outside'],
    explanation: 'Happy is an adjective that describes the children\'s mood.',
    planet: 'earth',
    level: 2,
    questionNumber: 46,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-47',
    type: 'correction',
    content: 'Correct the sentence: "He is more faster than his brother."',
    correctAnswer: 'He is faster than his brother.',
    explanation: 'Don\'t use "more" with -er endings. Use either "more fast" or "faster".',
    planet: 'earth',
    level: 2,
    questionNumber: 47,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-48',
    type: 'fill-in-blank',
    content: 'Complete: "The weather is _____ (nice) today than yesterday."',
    correctAnswer: 'nicer',
    explanation: 'Use the comparative form "nicer" to compare two days.',
    planet: 'earth',
    level: 2,
    questionNumber: 48,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-49',
    type: 'multiple-choice',
    content: 'Which adjective describes size?',
    correctAnswer: 'huge',
    options: ['huge', 'running', 'quickly', 'yesterday'],
    explanation: 'Huge is an adjective that describes very large size.',
    planet: 'earth',
    level: 2,
    questionNumber: 49,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-50',
    type: 'correction',
    content: 'Correct the sentence: "This is the most good cake I\'ve ever eaten."',
    correctAnswer: 'This is the best cake I\'ve ever eaten.',
    explanation: 'The superlative of "good" is "best", not "most good".',
    planet: 'earth',
    level: 2,
    questionNumber: 50,
    points: 10,
    difficulty: 'beginner'
  }
]; 