import { Exercise } from '@/types/curriculum';

export const earthLevel4Questions: Exercise[] = [
  {
    id: 'earth-4-1',
    type: 'multiple-choice',
    content: 'Choose the correct past continuous form: "I _____ TV when you called."',
    correctAnswer: 'was watching',
    options: ['watched', 'was watching', 'am watching', 'watch'],
    explanation: 'Past continuous uses "was/were + -ing" for ongoing actions in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 1,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-2',
    type: 'multiple-choice',
    content: 'What is the past continuous form of "run"?',
    correctAnswer: 'was/were running',
    options: ['ran', 'was/were running', 'runs', 'will run'],
    explanation: 'Past continuous is formed with was/were + verb + -ing.',
    planet: 'earth',
    level: 4,
    questionNumber: 2,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-3',
    type: 'multiple-choice',
    content: 'Choose the correct form: "They _____ soccer when it started raining."',
    correctAnswer: 'were playing',
    options: ['played', 'were playing', 'are playing', 'play'],
    explanation: 'Use "were" with plural subjects in past continuous.',
    planet: 'earth',
    level: 4,
    questionNumber: 3,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-4',
    type: 'multiple-choice',
    content: 'Select the correct sentence:',
    correctAnswer: 'She was reading when I arrived.',
    options: ['She was reading when I arrived.', 'She was read when I arrived.', 'She reading when I arrived.', 'She were reading when I arrived.'],
    explanation: 'Past continuous uses "was" with singular subjects and -ing form.',
    planet: 'earth',
    level: 4,
    questionNumber: 4,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-5',
    type: 'fill-in-blank',
    content: 'Complete: "We _____ (walk) in the park yesterday afternoon."',
    correctAnswer: 'were walking',
    explanation: 'Use "were walking" for ongoing action in the past with plural subject.',
    planet: 'earth',
    level: 4,
    questionNumber: 5,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-6',
    type: 'multiple-choice',
    content: 'Choose the correct form: "He _____ his homework at 8 PM."',
    correctAnswer: 'was doing',
    options: ['did', 'was doing', 'does', 'is doing'],
    explanation: 'Past continuous shows what was happening at a specific time in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 6,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-7',
    type: 'multiple-choice',
    content: 'What is the negative form of "I was sleeping"?',
    correctAnswer: 'I was not sleeping',
    options: ['I was not sleeping', 'I did not sleeping', 'I not was sleeping', 'I was not sleep'],
    explanation: 'Negative past continuous: was/were + not + verb + -ing.',
    planet: 'earth',
    level: 4,
    questionNumber: 7,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-8',
    type: 'multiple-choice',
    content: 'Choose the correct form: "_____ you studying when I called?"',
    correctAnswer: 'Were',
    options: ['Was', 'Were', 'Did', 'Are'],
    explanation: 'Use "Were" for questions with "you" in past continuous.',
    planet: 'earth',
    level: 4,
    questionNumber: 8,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-9',
    type: 'fill-in-blank',
    content: 'Complete: "The children _____ (play) outside when their mother called them."',
    correctAnswer: 'were playing',
    explanation: 'Use "were playing" for ongoing action interrupted by another action.',
    planet: 'earth',
    level: 4,
    questionNumber: 9,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-10',
    type: 'multiple-choice',
    content: 'Select the correct sentence:',
    correctAnswer: 'It was raining heavily last night.',
    options: ['It was raining heavily last night.', 'It was rain heavily last night.', 'It were raining heavily last night.', 'It raining heavily last night.'],
    explanation: 'Past continuous with weather: "It was raining".',
    planet: 'earth',
    level: 4,
    questionNumber: 10,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-11',
    type: 'multiple-choice',
    content: 'Choose the correct form: "While I _____ dinner, the phone rang."',
    correctAnswer: 'was cooking',
    options: ['cooked', 'was cooking', 'cook', 'am cooking'],
    explanation: 'Use past continuous with "while" for ongoing background action.',
    planet: 'earth',
    level: 4,
    questionNumber: 11,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-12',
    type: 'multiple-choice',
    content: 'What is the question form of "She was writing a letter"?',
    correctAnswer: 'Was she writing a letter?',
    options: ['Was she writing a letter?', 'Did she writing a letter?', 'Was she write a letter?', 'Were she writing a letter?'],
    explanation: 'Question form: Was/Were + subject + verb + -ing?',
    planet: 'earth',
    level: 4,
    questionNumber: 12,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-13',
    type: 'fill-in-blank',
    content: 'Complete: "At 9 AM yesterday, I _____ (drive) to work."',
    correctAnswer: 'was driving',
    explanation: 'Use past continuous for actions happening at a specific time in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 13,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-14',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The dog _____ loudly all night."',
    correctAnswer: 'was barking',
    options: ['barked', 'was barking', 'bark', 'is barking'],
    explanation: 'Past continuous for continuous action over a period in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 14,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-15',
    type: 'multiple-choice',
    content: 'Select the correct sentence:',
    correctAnswer: 'They were not listening to the teacher.',
    options: ['They were not listening to the teacher.', 'They was not listening to the teacher.', 'They not were listening to the teacher.', 'They were not listen to the teacher.'],
    explanation: 'Negative past continuous with plural subject uses "were not".',
    planet: 'earth',
    level: 4,
    questionNumber: 15,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-16',
    type: 'correction',
    content: 'Correct the sentence: "I was watch TV when you called."',
    correctAnswer: 'I was watching TV when you called.',
    explanation: 'Past continuous needs the -ing form: was/were + verb + -ing.',
    planet: 'earth',
    level: 4,
    questionNumber: 16,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-17',
    type: 'multiple-choice',
    content: 'Choose the correct form: "_____ it snowing when you left?"',
    correctAnswer: 'Was',
    options: ['Was', 'Were', 'Did', 'Is'],
    explanation: 'Use "Was" with "it" in past continuous questions.',
    planet: 'earth',
    level: 4,
    questionNumber: 17,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-18',
    type: 'fill-in-blank',
    content: 'Complete: "My friends _____ (wait) for me at the station."',
    correctAnswer: 'were waiting',
    explanation: 'Use "were waiting" with plural subject for ongoing past action.',
    planet: 'earth',
    level: 4,
    questionNumber: 18,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-19',
    type: 'multiple-choice',
    content: 'Choose the correct form: "She _____ when I saw her."',
    correctAnswer: 'was crying',
    options: ['cried', 'was crying', 'cry', 'is crying'],
    explanation: 'Past continuous for ongoing action when another action occurred.',
    planet: 'earth',
    level: 4,
    questionNumber: 19,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-20',
    type: 'multiple-choice',
    content: 'What is the past continuous form of "swim"?',
    correctAnswer: 'was/were swimming',
    options: ['swam', 'was/were swimming', 'swims', 'will swim'],
    explanation: 'Past continuous: was/were + swimming.',
    planet: 'earth',
    level: 4,
    questionNumber: 20,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-21',
    type: 'multiple-choice',
    content: 'Choose the correct form: "We _____ about you yesterday."',
    correctAnswer: 'were talking',
    options: ['talked', 'were talking', 'talk', 'are talking'],
    explanation: 'Past continuous can show ongoing action in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 21,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-22',
    type: 'fill-in-blank',
    content: 'Complete: "The baby _____ (sleep) peacefully in the crib."',
    correctAnswer: 'was sleeping',
    explanation: 'Use "was sleeping" for ongoing state in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 22,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-23',
    type: 'multiple-choice',
    content: 'Select the correct sentence:',
    correctAnswer: 'The students were taking notes during the lecture.',
    options: ['The students were taking notes during the lecture.', 'The students was taking notes during the lecture.', 'The students were take notes during the lecture.', 'The students taking notes during the lecture.'],
    explanation: 'Plural subjects use "were" in past continuous.',
    planet: 'earth',
    level: 4,
    questionNumber: 23,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-24',
    type: 'multiple-choice',
    content: 'Choose the correct form: "I _____ my keys everywhere."',
    correctAnswer: 'was looking for',
    options: ['looked for', 'was looking for', 'look for', 'am looking for'],
    explanation: 'Past continuous for ongoing search action in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 24,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-25',
    type: 'correction',
    content: 'Correct the sentence: "They was playing football in the park."',
    correctAnswer: 'They were playing football in the park.',
    explanation: 'Use "were" with plural subjects, not "was".',
    planet: 'earth',
    level: 4,
    questionNumber: 25,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-26',
    type: 'multiple-choice',
    content: 'Choose the correct form: "_____ you working late last night?"',
    correctAnswer: 'Were',
    options: ['Was', 'Were', 'Did', 'Are'],
    explanation: 'Use "Were" with "you" in past continuous questions.',
    planet: 'earth',
    level: 4,
    questionNumber: 26,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-27',
    type: 'fill-in-blank',
    content: 'Complete: "The cat _____ (sit) by the window all morning."',
    correctAnswer: 'was sitting',
    explanation: 'Use past continuous for ongoing state over a period.',
    planet: 'earth',
    level: 4,
    questionNumber: 27,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-28',
    type: 'multiple-choice',
    content: 'What is the negative form of "We were dancing"?',
    correctAnswer: 'We were not dancing',
    options: ['We were not dancing', 'We did not dancing', 'We not were dancing', 'We were not dance'],
    explanation: 'Negative: were + not + verb + -ing.',
    planet: 'earth',
    level: 4,
    questionNumber: 28,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-29',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The birds _____ in the trees."',
    correctAnswer: 'were singing',
    options: ['sang', 'were singing', 'sing', 'are singing'],
    explanation: 'Past continuous for ongoing action in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 29,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-30',
    type: 'multiple-choice',
    content: 'Select the correct sentence:',
    correctAnswer: 'He was not feeling well yesterday.',
    options: ['He was not feeling well yesterday.', 'He was not feel well yesterday.', 'He not was feeling well yesterday.', 'He were not feeling well yesterday.'],
    explanation: 'Negative past continuous with singular subject.',
    planet: 'earth',
    level: 4,
    questionNumber: 30,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-31',
    type: 'fill-in-blank',
    content: 'Complete: "While she _____ (read), I was cooking dinner."',
    correctAnswer: 'was reading',
    explanation: 'Use past continuous for simultaneous actions in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 31,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-32',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The children _____ quietly in their room."',
    correctAnswer: 'were playing',
    options: ['played', 'were playing', 'play', 'are playing'],
    explanation: 'Past continuous for ongoing activity in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 32,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-33',
    type: 'multiple-choice',
    content: 'What is the question form of "You were studying"?',
    correctAnswer: 'Were you studying?',
    options: ['Were you studying?', 'Did you studying?', 'Was you studying?', 'Were you study?'],
    explanation: 'Question: Were + you + verb + -ing?',
    planet: 'earth',
    level: 4,
    questionNumber: 33,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-34',
    type: 'correction',
    content: 'Correct the sentence: "She were writing a letter when I arrived."',
    correctAnswer: 'She was writing a letter when I arrived.',
    explanation: 'Use "was" with singular subjects like "she".',
    planet: 'earth',
    level: 4,
    questionNumber: 34,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-35',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The phone _____ while I was in the shower."',
    correctAnswer: 'was ringing',
    options: ['rang', 'was ringing', 'rings', 'is ringing'],
    explanation: 'Past continuous for ongoing action interrupted by another.',
    planet: 'earth',
    level: 4,
    questionNumber: 35,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-36',
    type: 'fill-in-blank',
    content: 'Complete: "They _____ (not/listen) to the music."',
    correctAnswer: 'were not listening',
    explanation: 'Negative past continuous: were not + verb + -ing.',
    planet: 'earth',
    level: 4,
    questionNumber: 36,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-37',
    type: 'multiple-choice',
    content: 'Select the correct sentence:',
    correctAnswer: 'I was thinking about the problem all day.',
    options: ['I was thinking about the problem all day.', 'I was think about the problem all day.', 'I were thinking about the problem all day.', 'I thinking about the problem all day.'],
    explanation: 'Past continuous for mental activity over time.',
    planet: 'earth',
    level: 4,
    questionNumber: 37,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-38',
    type: 'multiple-choice',
    content: 'Choose the correct form: "_____ the sun shining when you woke up?"',
    correctAnswer: 'Was',
    options: ['Was', 'Were', 'Did', 'Is'],
    explanation: 'Use "Was" with "the sun" in past continuous questions.',
    planet: 'earth',
    level: 4,
    questionNumber: 38,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-39',
    type: 'multiple-choice',
    content: 'What is the past continuous form of "eat"?',
    correctAnswer: 'was/were eating',
    options: ['ate', 'was/were eating', 'eats', 'will eat'],
    explanation: 'Past continuous: was/were + eating.',
    planet: 'earth',
    level: 4,
    questionNumber: 39,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-40',
    type: 'fill-in-blank',
    content: 'Complete: "The wind _____ (blow) strongly last night."',
    correctAnswer: 'was blowing',
    explanation: 'Use past continuous for weather conditions in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 40,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-41',
    type: 'multiple-choice',
    content: 'Choose the correct form: "We _____ TV when the power went out."',
    correctAnswer: 'were watching',
    options: ['watched', 'were watching', 'watch', 'are watching'],
    explanation: 'Past continuous for interrupted action.',
    planet: 'earth',
    level: 4,
    questionNumber: 41,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-42',
    type: 'correction',
    content: 'Correct the sentence: "The dogs was barking all night."',
    correctAnswer: 'The dogs were barking all night.',
    explanation: 'Use "were" with plural subjects like "dogs".',
    planet: 'earth',
    level: 4,
    questionNumber: 42,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-43',
    type: 'multiple-choice',
    content: 'Select the correct sentence:',
    correctAnswer: 'The teacher was explaining the lesson when the bell rang.',
    options: ['The teacher was explaining the lesson when the bell rang.', 'The teacher was explain the lesson when the bell rang.', 'The teacher were explaining the lesson when the bell rang.', 'The teacher explaining the lesson when the bell rang.'],
    explanation: 'Past continuous for ongoing action interrupted by simple past.',
    planet: 'earth',
    level: 4,
    questionNumber: 43,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-44',
    type: 'fill-in-blank',
    content: 'Complete: "At midnight, everyone _____ (sleep)."',
    correctAnswer: 'was sleeping',
    explanation: 'Use past continuous for ongoing state at a specific time.',
    planet: 'earth',
    level: 4,
    questionNumber: 44,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-45',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The car _____ strange noises."',
    correctAnswer: 'was making',
    options: ['made', 'was making', 'makes', 'is making'],
    explanation: 'Past continuous for ongoing action in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 45,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-46',
    type: 'multiple-choice',
    content: 'What is the negative form of "He was running"?',
    correctAnswer: 'He was not running',
    options: ['He was not running', 'He did not running', 'He not was running', 'He was not run'],
    explanation: 'Negative: was + not + verb + -ing.',
    planet: 'earth',
    level: 4,
    questionNumber: 46,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-47',
    type: 'multiple-choice',
    content: 'Choose the correct form: "_____ they working on the project?"',
    correctAnswer: 'Were',
    options: ['Was', 'Were', 'Did', 'Are'],
    explanation: 'Use "Were" with "they" in past continuous questions.',
    planet: 'earth',
    level: 4,
    questionNumber: 47,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-48',
    type: 'fill-in-blank',
    content: 'Complete: "The flowers _____ (grow) beautifully in the garden."',
    correctAnswer: 'were growing',
    explanation: 'Use past continuous for ongoing process in the past.',
    planet: 'earth',
    level: 4,
    questionNumber: 48,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-49',
    type: 'correction',
    content: 'Correct the sentence: "I was not understand the lesson."',
    correctAnswer: 'I was not understanding the lesson.',
    explanation: 'Past continuous needs the -ing form after was/were.',
    planet: 'earth',
    level: 4,
    questionNumber: 49,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-4-50',
    type: 'multiple-choice',
    content: 'Select the correct sentence:',
    correctAnswer: 'The stars were shining brightly in the sky.',
    options: ['The stars were shining brightly in the sky.', 'The stars was shining brightly in the sky.', 'The stars were shine brightly in the sky.', 'The stars shining brightly in the sky.'],
    explanation: 'Past continuous with plural subject uses "were".',
    planet: 'earth',
    level: 4,
    questionNumber: 50,
    points: 10,
    difficulty: 'intermediate'
  }
]; 