import { Exercise } from '@/types/curriculum';

export const earthLevel1Questions: Exercise[] = [
  {
    id: 'earth-1-1',
    type: 'multiple-choice',
    content: 'What is the past tense of "walk"?',
    correctAnswer: 'walked',
    options: ['walked', 'walken', 'walkt', 'walking'],
    explanation: 'When we talk about something that happened yesterday or in the past, we add "-ed" to most verbs. So "walk" becomes "walked". For example: "Yesterday, I walked to school." This is called the past tense!',
    planet: 'earth',
    level: 1,
    questionNumber: 1,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-2',
    type: 'multiple-choice',
    content: 'What is the past participle of "write"?',
    correctAnswer: 'written',
    options: ['wrote', 'written', 'writed', 'writing'],
    explanation: 'Some verbs are special! The word "write" has three forms: write (now), wrote (past), and written (past participle). We use "written" with helping words like "have" or "has". For example: "I have written a letter." Think of it like a magic word that changes!',
    planet: 'earth',
    level: 1,
    questionNumber: 2,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-3',
    type: 'multiple-choice',
    content: 'What is the past tense of "eat"?',
    correctAnswer: 'ate',
    options: ['eated', 'ate', 'eaten', 'eating'],
    explanation: 'The word "eat" is another special verb! When we talk about eating something yesterday, we say "ate" (sounds like the number "eight"). For example: "Yesterday, I ate pizza for lunch." We don\'t say "eated" - that\'s not a real word!',
    planet: 'earth',
    level: 1,
    questionNumber: 3,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-4',
    type: 'multiple-choice',
    content: 'What is the past participle of "go"?',
    correctAnswer: 'gone',
    options: ['went', 'gone', 'goed', 'going'],
    explanation: 'The verb "go" has three different forms: go (now), went (past), and gone (past participle). We use "gone" with helper words like "have" or "has". For example: "She has gone to the store." It\'s like saying someone left and isn\'t here right now!',
    planet: 'earth',
    level: 1,
    questionNumber: 4,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-5',
    type: 'multiple-choice',
    content: 'What is the past tense of "see"?',
    correctAnswer: 'saw',
    options: ['saw', 'seen', 'seed', 'seeing'],
    explanation: 'When we talk about looking at something yesterday, we use "saw" (like the tool that cuts wood!). For example: "Yesterday, I saw a beautiful rainbow." The word "see" becomes "saw" in the past tense. It\'s another one of those special verbs that changes completely!',
    planet: 'earth',
    level: 1,
    questionNumber: 5,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-6',
    type: 'multiple-choice',
    content: 'What is the past participle of "take"?',
    correctAnswer: 'taken',
    options: ['took', 'taken', 'taked', 'taking'],
    explanation: 'The verb "take" has three forms: take (now), took (past), and taken (past participle). We use "taken" with helper words like "have" or "has". For example: "I have taken my medicine." It means the action is completely finished!',
    planet: 'earth',
    level: 1,
    questionNumber: 6,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-7',
    type: 'multiple-choice',
    content: 'What is the past tense of "give"?',
    correctAnswer: 'gave',
    options: ['gived', 'gave', 'given', 'giving'],
    explanation: 'When we talk about giving something yesterday, we say "gave". For example: "Yesterday, I gave my friend a birthday present." The word "give" becomes "gave" in the past tense. We never say "gived" - that\'s not correct English!',
    planet: 'earth',
    level: 1,
    questionNumber: 7,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-8',
    type: 'multiple-choice',
    content: 'What is the past participle of "break"?',
    correctAnswer: 'broken',
    options: ['broke', 'broken', 'breaked', 'breaking'],
    explanation: 'The verb "break" has three forms: break (now), broke (past), and broken (past participle). We use "broken" with helper words like "have", "has", or "is". For example: "The toy is broken" or "I have broken my pencil." It describes something that got damaged!',
    planet: 'earth',
    level: 1,
    questionNumber: 8,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-9',
    type: 'multiple-choice',
    content: 'What is the past tense of "come"?',
    correctAnswer: 'came',
    options: ['comed', 'came', 'come', 'coming'],
    explanation: 'When we talk about someone arriving yesterday, we say "came". For example: "My grandma came to visit yesterday." The word "come" becomes "came" in the past tense. It\'s like saying someone arrived or showed up!',
    planet: 'earth',
    level: 1,
    questionNumber: 9,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-10',
    type: 'multiple-choice',
    content: 'What is the past participle of "know"?',
    correctAnswer: 'known',
    options: ['knew', 'known', 'knowed', 'knowing'],
    explanation: 'The verb "know" has three forms: know (now), knew (past), and known (past participle). We use "known" with helper words like "have" or "has". For example: "I have known my best friend for five years." It means you\'ve been familiar with something for a while!',
    planet: 'earth',
    level: 1,
    questionNumber: 10,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-11',
    type: 'multiple-choice',
    content: 'What is the past tense of "get"?',
    correctAnswer: 'got',
    options: ['getted', 'got', 'gotten', 'getting'],
    explanation: 'The past tense of "get" is "got".',
    planet: 'earth',
    level: 1,
    questionNumber: 11,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-12',
    type: 'multiple-choice',
    content: 'What is the past participle of "make"?',
    correctAnswer: 'made',
    options: ['maked', 'made', 'maken', 'making'],
    explanation: 'The past participle of "make" is "made".',
    planet: 'earth',
    level: 1,
    questionNumber: 12,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-13',
    type: 'multiple-choice',
    content: 'What is the past tense of "think"?',
    correctAnswer: 'thought',
    options: ['thinked', 'thought', 'thunk', 'thinking'],
    explanation: 'The past tense of "think" is "thought".',
    planet: 'earth',
    level: 1,
    questionNumber: 13,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-14',
    type: 'multiple-choice',
    content: 'What is the past participle of "find"?',
    correctAnswer: 'found',
    options: ['finded', 'found', 'fanden', 'finding'],
    explanation: 'The past participle of "find" is "found".',
    planet: 'earth',
    level: 1,
    questionNumber: 14,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-15',
    type: 'multiple-choice',
    content: 'What is the past tense of "tell"?',
    correctAnswer: 'told',
    options: ['telled', 'told', 'tellen', 'telling'],
    explanation: 'The past tense of "tell" is "told".',
    planet: 'earth',
    level: 1,
    questionNumber: 15,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-16',
    type: 'multiple-choice',
    content: 'What is the past participle of "feel"?',
    correctAnswer: 'felt',
    options: ['feeled', 'felt', 'felten', 'feeling'],
    explanation: 'The past participle of "feel" is "felt".',
    planet: 'earth',
    level: 1,
    questionNumber: 16,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-17',
    type: 'multiple-choice',
    content: 'What is the past tense of "become"?',
    correctAnswer: 'became',
    options: ['becomed', 'became', 'become', 'becoming'],
    explanation: 'The past tense of "become" is "became".',
    planet: 'earth',
    level: 1,
    questionNumber: 17,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-18',
    type: 'multiple-choice',
    content: 'What is the past participle of "leave"?',
    correctAnswer: 'left',
    options: ['leaved', 'left', 'leaven', 'leaving'],
    explanation: 'The past participle of "leave" is "left".',
    planet: 'earth',
    level: 1,
    questionNumber: 18,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-19',
    type: 'multiple-choice',
    content: 'What is the past tense of "put"?',
    correctAnswer: 'put',
    options: ['puted', 'put', 'putten', 'putting'],
    explanation: 'The past tense of "put" is "put" (it remains the same).',
    planet: 'earth',
    level: 1,
    questionNumber: 19,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-20',
    type: 'multiple-choice',
    content: 'What is the past participle of "mean"?',
    correctAnswer: 'meant',
    options: ['meaned', 'meant', 'meanten', 'meaning'],
    explanation: 'The past participle of "mean" is "meant".',
    planet: 'earth',
    level: 1,
    questionNumber: 20,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-21',
    type: 'multiple-choice',
    content: 'What is the past tense of "think"?',
    correctAnswer: 'thought',
    options: ['thinked', 'thought', 'thunk', 'thinking'],
    explanation: 'The past tense of "think" is "thought".',
    planet: 'earth',
    level: 1,
    questionNumber: 21,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-22',
    type: 'multiple-choice',
    content: 'What is the past participle of "bring"?',
    correctAnswer: 'brought',
    options: ['bringed', 'brought', 'brang', 'bringing'],
    explanation: 'The past participle of "bring" is "brought".',
    planet: 'earth',
    level: 1,
    questionNumber: 22,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-23',
    type: 'multiple-choice',
    content: 'What is the past tense of "buy"?',
    correctAnswer: 'bought',
    options: ['buyed', 'bought', 'buyen', 'buying'],
    explanation: 'The past tense of "buy" is "bought".',
    planet: 'earth',
    level: 1,
    questionNumber: 23,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-24',
    type: 'multiple-choice',
    content: 'What is the past participle of "catch"?',
    correctAnswer: 'caught',
    options: ['catched', 'caught', 'catchen', 'catching'],
    explanation: 'The past participle of "catch" is "caught".',
    planet: 'earth',
    level: 1,
    questionNumber: 24,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-25',
    type: 'multiple-choice',
    content: 'What is the past tense of "teach"?',
    correctAnswer: 'taught',
    options: ['teached', 'taught', 'teachen', 'teaching'],
    explanation: 'The past tense of "teach" is "taught".',
    planet: 'earth',
    level: 1,
    questionNumber: 25,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-26',
    type: 'multiple-choice',
    content: 'What is the past participle of "fight"?',
    correctAnswer: 'fought',
    options: ['fighted', 'fought', 'fighten', 'fighting'],
    explanation: 'The past participle of "fight" is "fought".',
    planet: 'earth',
    level: 1,
    questionNumber: 26,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-27',
    type: 'multiple-choice',
    content: 'What is the past tense of "find"?',
    correctAnswer: 'found',
    options: ['finded', 'found', 'fanden', 'finding'],
    explanation: 'The past tense of "find" is "found".',
    planet: 'earth',
    level: 1,
    questionNumber: 27,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-28',
    type: 'multiple-choice',
    content: 'What is the past participle of "lose"?',
    correctAnswer: 'lost',
    options: ['losed', 'lost', 'losen', 'losing'],
    explanation: 'The past participle of "lose" is "lost".',
    planet: 'earth',
    level: 1,
    questionNumber: 28,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-29',
    type: 'multiple-choice',
    content: 'What is the past tense of "keep"?',
    correctAnswer: 'kept',
    options: ['keeped', 'kept', 'keepen', 'keeping'],
    explanation: 'The past tense of "keep" is "kept".',
    planet: 'earth',
    level: 1,
    questionNumber: 29,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-30',
    type: 'multiple-choice',
    content: 'What is the past participle of "sleep"?',
    correctAnswer: 'slept',
    options: ['sleeped', 'slept', 'sleepen', 'sleeping'],
    explanation: 'The past participle of "sleep" is "slept".',
    planet: 'earth',
    level: 1,
    questionNumber: 30,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-31',
    type: 'multiple-choice',
    content: 'What is the past tense of "feel"?',
    correctAnswer: 'felt',
    options: ['feeled', 'felt', 'feelen', 'feeling'],
    explanation: 'The past tense of "feel" is "felt".',
    planet: 'earth',
    level: 1,
    questionNumber: 31,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-32',
    type: 'multiple-choice',
    content: 'What is the past participle of "meet"?',
    correctAnswer: 'met',
    options: ['meeted', 'met', 'meeten', 'meeting'],
    explanation: 'The past participle of "meet" is "met".',
    planet: 'earth',
    level: 1,
    questionNumber: 32,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-33',
    type: 'multiple-choice',
    content: 'What is the past tense of "send"?',
    correctAnswer: 'sent',
    options: ['sended', 'sent', 'senden', 'sending'],
    explanation: 'The past tense of "send" is "sent".',
    planet: 'earth',
    level: 1,
    questionNumber: 33,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-34',
    type: 'multiple-choice',
    content: 'What is the past participle of "spend"?',
    correctAnswer: 'spent',
    options: ['spended', 'spent', 'spenden', 'spending'],
    explanation: 'The past participle of "spend" is "spent".',
    planet: 'earth',
    level: 1,
    questionNumber: 34,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-35',
    type: 'multiple-choice',
    content: 'What is the past tense of "build"?',
    correctAnswer: 'built',
    options: ['builded', 'built', 'builden', 'building'],
    explanation: 'The past tense of "build" is "built".',
    planet: 'earth',
    level: 1,
    questionNumber: 35,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-36',
    type: 'multiple-choice',
    content: 'What is the past participle of "lend"?',
    correctAnswer: 'lent',
    options: ['lended', 'lent', 'lenden', 'lending'],
    explanation: 'The past participle of "lend" is "lent".',
    planet: 'earth',
    level: 1,
    questionNumber: 36,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-37',
    type: 'multiple-choice',
    content: 'What is the past tense of "stand"?',
    correctAnswer: 'stood',
    options: ['standed', 'stood', 'standen', 'standing'],
    explanation: 'The past tense of "stand" is "stood".',
    planet: 'earth',
    level: 1,
    questionNumber: 37,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-38',
    type: 'multiple-choice',
    content: 'What is the past participle of "understand"?',
    correctAnswer: 'understood',
    options: ['understanded', 'understood', 'understanden', 'understanding'],
    explanation: 'The past participle of "understand" is "understood".',
    planet: 'earth',
    level: 1,
    questionNumber: 38,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-39',
    type: 'multiple-choice',
    content: 'What is the past tense of "hear"?',
    correctAnswer: 'heard',
    options: ['heared', 'heard', 'hearen', 'hearing'],
    explanation: 'The past tense of "hear" is "heard".',
    planet: 'earth',
    level: 1,
    questionNumber: 39,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-40',
    type: 'multiple-choice',
    content: 'What is the past participle of "tell"?',
    correctAnswer: 'told',
    options: ['telled', 'told', 'tellen', 'telling'],
    explanation: 'The past participle of "tell" is "told".',
    planet: 'earth',
    level: 1,
    questionNumber: 40,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-41',
    type: 'multiple-choice',
    content: 'What is the past tense of "sell"?',
    correctAnswer: 'sold',
    options: ['selled', 'sold', 'sellen', 'selling'],
    explanation: 'The past tense of "sell" is "sold".',
    planet: 'earth',
    level: 1,
    questionNumber: 41,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-42',
    type: 'multiple-choice',
    content: 'What is the past participle of "hold"?',
    correctAnswer: 'held',
    options: ['holded', 'held', 'holden', 'holding'],
    explanation: 'The past participle of "hold" is "held".',
    planet: 'earth',
    level: 1,
    questionNumber: 42,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-43',
    type: 'multiple-choice',
    content: 'What is the past tense of "read"?',
    correctAnswer: 'read',
    options: ['readed', 'read', 'reden', 'reading'],
    explanation: 'The past tense of "read" is "read" (pronounced "red").',
    planet: 'earth',
    level: 1,
    questionNumber: 43,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-44',
    type: 'multiple-choice',
    content: 'What is the past participle of "lead"?',
    correctAnswer: 'led',
    options: ['leaded', 'led', 'leaden', 'leading'],
    explanation: 'The past participle of "lead" is "led".',
    planet: 'earth',
    level: 1,
    questionNumber: 44,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-45',
    type: 'multiple-choice',
    content: 'What is the past tense of "feed"?',
    correctAnswer: 'fed',
    options: ['feeded', 'fed', 'feden', 'feeding'],
    explanation: 'The past tense of "feed" is "fed".',
    planet: 'earth',
    level: 1,
    questionNumber: 45,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-46',
    type: 'multiple-choice',
    content: 'What is the past participle of "bleed"?',
    correctAnswer: 'bled',
    options: ['bleeded', 'bled', 'bleden', 'bleeding'],
    explanation: 'The past participle of "bleed" is "bled".',
    planet: 'earth',
    level: 1,
    questionNumber: 46,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-47',
    type: 'multiple-choice',
    content: 'What is the past tense of "speed"?',
    correctAnswer: 'sped',
    options: ['speeded', 'sped', 'speden', 'speeding'],
    explanation: 'The past tense of "speed" is "sped".',
    planet: 'earth',
    level: 1,
    questionNumber: 47,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-48',
    type: 'multiple-choice',
    content: 'What is the past participle of "breed"?',
    correctAnswer: 'bred',
    options: ['breeded', 'bred', 'breden', 'breeding'],
    explanation: 'The past participle of "breed" is "bred".',
    planet: 'earth',
    level: 1,
    questionNumber: 48,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-49',
    type: 'multiple-choice',
    content: 'What is the past tense of "strike"?',
    correctAnswer: 'struck',
    options: ['striked', 'struck', 'striken', 'striking'],
    explanation: 'The past tense of "strike" is "struck".',
    planet: 'earth',
    level: 1,
    questionNumber: 49,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-50',
    type: 'multiple-choice',
    content: 'What is the past participle of "strike"?',
    correctAnswer: 'struck',
    options: ['striked', 'struck', 'striken', 'striking'],
    explanation: 'The past participle of "strike" is "struck".',
    planet: 'earth',
    level: 1,
    questionNumber: 50,
    points: 10,
    difficulty: 'beginner'
  }
]; 