import { Exercise } from '@/types/curriculum';

export const earthLevel1Questions: Exercise[] = [
  {
    id: 'earth-1-1',
    type: 'multiple-choice',
    content: 'What is the past tense of "walk"?',
    correctAnswer: 'walked',
    options: ['walked', 'walken', 'walkt', 'walking'],
    explanation: 'Regular verbs in past tense add -ed to the base form.',
    planet: 'earth',
    level: 1,
    questionNumber: 1,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-2',
    type: 'multiple-choice',
    content: 'What is the past participle of "write"?',
    correctAnswer: 'written',
    options: ['wrote', 'written', 'writed', 'writing'],
    explanation: 'The past participle of "write" is "written".',
    planet: 'earth',
    level: 1,
    questionNumber: 2,
    points: 10,
    difficulty: 'beginner'
  },
  // ... (all other questions from earth-1-3 to earth-1-50) ...
  {
    id: 'earth-1-3',
    type: 'multiple-choice',
    content: 'What is the past tense of "eat"?',
    correctAnswer: 'ate',
    options: ['eated', 'ate', 'eaten', 'eating'],
    explanation: 'The past tense of "eat" is "ate".',
    planet: 'earth',
    level: 1,
    questionNumber: 3,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-4',
    type: 'multiple-choice',
    content: 'What is the past participle of "go"?',
    correctAnswer: 'gone',
    options: ['went', 'gone', 'goed', 'going'],
    explanation: 'The past participle of "go" is "gone".',
    planet: 'earth',
    level: 1,
    questionNumber: 4,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-5',
    type: 'multiple-choice',
    content: 'What is the past tense of "see"?',
    correctAnswer: 'saw',
    options: ['saw', 'seen', 'seed', 'seeing'],
    explanation: 'The past tense of "see" is "saw".',
    planet: 'earth',
    level: 1,
    questionNumber: 5,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-6',
    type: 'multiple-choice',
    content: 'What is the past participle of "take"?',
    correctAnswer: 'taken',
    options: ['took', 'taken', 'taked', 'taking'],
    explanation: 'The past participle of "take" is "taken".',
    planet: 'earth',
    level: 1,
    questionNumber: 6,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-7',
    type: 'multiple-choice',
    content: 'What is the past tense of "give"?',
    correctAnswer: 'gave',
    options: ['gived', 'gave', 'given', 'giving'],
    explanation: 'The past tense of "give" is "gave".',
    planet: 'earth',
    level: 1,
    questionNumber: 7,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-8',
    type: 'multiple-choice',
    content: 'What is the past participle of "break"?',
    correctAnswer: 'broken',
    options: ['broke', 'broken', 'breaked', 'breaking'],
    explanation: 'The past participle of "break" is "broken".',
    planet: 'earth',
    level: 1,
    questionNumber: 8,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-9',
    type: 'multiple-choice',
    content: 'What is the past tense of "come"?',
    correctAnswer: 'came',
    options: ['comed', 'came', 'come', 'coming'],
    explanation: 'The past tense of "come" is "came".',
    planet: 'earth',
    level: 1,
    questionNumber: 9,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-10',
    type: 'multiple-choice',
    content: 'What is the past participle of "know"?',
    correctAnswer: 'known',
    options: ['knew', 'known', 'knowed', 'knowing'],
    explanation: 'The past participle of "know" is "known".',
    planet: 'earth',
    level: 1,
    questionNumber: 10,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-11',
    type: 'multiple-choice',
    content: 'What is the past tense of "get"?',
    correctAnswer: 'got',
    options: ['getted', 'got', 'gotten', 'getting'],
    explanation: 'The past tense of "get" is "got".',
    planet: 'earth',
    level: 1,
    questionNumber: 11,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-12',
    type: 'multiple-choice',
    content: 'What is the past participle of "make"?',
    correctAnswer: 'made',
    options: ['maked', 'made', 'maden', 'making'],
    explanation: 'The past participle of "make" is "made".',
    planet: 'earth',
    level: 1,
    questionNumber: 12,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-13',
    type: 'multiple-choice',
    content: 'What is the past tense of "think"?',
    correctAnswer: 'thought',
    options: ['thinked', 'thought', 'thunk', 'thinking'],
    explanation: 'The past tense of "think" is "thought".',
    planet: 'earth',
    level: 1,
    questionNumber: 13,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-14',
    type: 'multiple-choice',
    content: 'What is the past participle of "find"?',
    correctAnswer: 'found',
    options: ['finded', 'found', 'founded', 'finding'],
    explanation: 'The past participle of "find" is "found".',
    planet: 'earth',
    level: 1,
    questionNumber: 14,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-15',
    type: 'multiple-choice',
    content: 'What is the past tense of "tell"?',
    correctAnswer: 'told',
    options: ['telled', 'told', 'tolden', 'telling'],
    explanation: 'The past tense of "tell" is "told".',
    planet: 'earth',
    level: 1,
    questionNumber: 15,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-16',
    type: 'multiple-choice',
    content: 'What is the past participle of "feel"?',
    correctAnswer: 'felt',
    options: ['feeled', 'felt', 'felten', 'feeling'],
    explanation: 'The past participle of "feel" is "felt".',
    planet: 'earth',
    level: 1,
    questionNumber: 16,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-17',
    type: 'multiple-choice',
    content: 'What is the past tense of "become"?',
    correctAnswer: 'became',
    options: ['becomed', 'became', 'become', 'becoming'],
    explanation: 'The past tense of "become" is "became".',
    planet: 'earth',
    level: 1,
    questionNumber: 17,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-18',
    type: 'multiple-choice',
    content: 'What is the past participle of "leave"?',
    correctAnswer: 'left',
    options: ['leaved', 'left', 'leaven', 'leaving'],
    explanation: 'The past participle of "leave" is "left".',
    planet: 'earth',
    level: 1,
    questionNumber: 18,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-19',
    type: 'multiple-choice',
    content: 'What is the past tense of "put"?',
    correctAnswer: 'put',
    options: ['puted', 'put', 'putten', 'putting'],
    explanation: 'The past tense of "put" is "put" (it remains the same).',
    planet: 'earth',
    level: 1,
    questionNumber: 19,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-20',
    type: 'multiple-choice',
    content: 'What is the past participle of "mean"?',
    correctAnswer: 'meant',
    options: ['meaned', 'meant', 'meanten', 'meaning'],
    explanation: 'The past participle of "mean" is "meant".',
    planet: 'earth',
    level: 1,
    questionNumber: 20,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-21',
    type: 'multiple-choice',
    content: 'What is the past tense of "think"?',
    correctAnswer: 'thought',
    options: ['thinked', 'thought', 'thunk', 'thinking'],
    explanation: 'The past tense of "think" is "thought".',
    planet: 'earth',
    level: 1,
    questionNumber: 21,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-22',
    type: 'multiple-choice',
    content: 'What is the past participle of "bring"?',
    correctAnswer: 'brought',
    options: ['bringed', 'brought', 'brang', 'bringing'],
    explanation: 'The past participle of "bring" is "brought".',
    planet: 'earth',
    level: 1,
    questionNumber: 22,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-23',
    type: 'multiple-choice',
    content: 'What is the past tense of "buy"?',
    correctAnswer: 'bought',
    options: ['buyed', 'bought', 'buyen', 'buying'],
    explanation: 'The past tense of "buy" is "bought".',
    planet: 'earth',
    level: 1,
    questionNumber: 23,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-24',
    type: 'multiple-choice',
    content: 'What is the past participle of "catch"?',
    correctAnswer: 'caught',
    options: ['catched', 'caught', 'catchen', 'catching'],
    explanation: 'The past participle of "catch" is "caught".',
    planet: 'earth',
    level: 1,
    questionNumber: 24,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-25',
    type: 'multiple-choice',
    content: 'What is the past tense of "teach"?',
    correctAnswer: 'taught',
    options: ['teached', 'taught', 'teachen', 'teaching'],
    explanation: 'The past tense of "teach" is "taught".',
    planet: 'earth',
    level: 1,
    questionNumber: 25,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-26',
    type: 'multiple-choice',
    content: 'What is the past participle of "fight"?',
    correctAnswer: 'fought',
    options: ['fighted', 'fought', 'fighten', 'fighting'],
    explanation: 'The past participle of "fight" is "fought".',
    planet: 'earth',
    level: 1,
    questionNumber: 26,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-27',
    type: 'multiple-choice',
    content: 'What is the past tense of "find"?',
    correctAnswer: 'found',
    options: ['finded', 'found', 'fanden', 'finding'],
    explanation: 'The past tense of "find" is "found".',
    planet: 'earth',
    level: 1,
    questionNumber: 27,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-28',
    type: 'multiple-choice',
    content: 'What is the past participle of "lose"?',
    correctAnswer: 'lost',
    options: ['losed', 'lost', 'losen', 'losing'],
    explanation: 'The past participle of "lose" is "lost".',
    planet: 'earth',
    level: 1,
    questionNumber: 28,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-29',
    type: 'multiple-choice',
    content: 'What is the past tense of "keep"?',
    correctAnswer: 'kept',
    options: ['keeped', 'kept', 'keepen', 'keeping'],
    explanation: 'The past tense of "keep" is "kept".',
    planet: 'earth',
    level: 1,
    questionNumber: 29,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-30',
    type: 'multiple-choice',
    content: 'What is the past participle of "sleep"?',
    correctAnswer: 'slept',
    options: ['sleeped', 'slept', 'sleepen', 'sleeping'],
    explanation: 'The past participle of "sleep" is "slept".',
    planet: 'earth',
    level: 1,
    questionNumber: 30,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-31',
    type: 'multiple-choice',
    content: 'What is the past tense of "feel"?',
    correctAnswer: 'felt',
    options: ['feeled', 'felt', 'feelen', 'feeling'],
    explanation: 'The past tense of "feel" is "felt".',
    planet: 'earth',
    level: 1,
    questionNumber: 31,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-32',
    type: 'multiple-choice',
    content: 'What is the past participle of "meet"?',
    correctAnswer: 'met',
    options: ['meeted', 'met', 'meeten', 'meeting'],
    explanation: 'The past participle of "meet" is "met".',
    planet: 'earth',
    level: 1,
    questionNumber: 32,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-33',
    type: 'multiple-choice',
    content: 'What is the past tense of "send"?',
    correctAnswer: 'sent',
    options: ['sended', 'sent', 'senden', 'sending'],
    explanation: 'The past tense of "send" is "sent".',
    planet: 'earth',
    level: 1,
    questionNumber: 33,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-34',
    type: 'multiple-choice',
    content: 'What is the past participle of "spend"?',
    correctAnswer: 'spent',
    options: ['spended', 'spent', 'spenden', 'spending'],
    explanation: 'The past participle of "spend" is "spent".',
    planet: 'earth',
    level: 1,
    questionNumber: 34,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-35',
    type: 'multiple-choice',
    content: 'What is the past tense of "build"?',
    correctAnswer: 'built',
    options: ['builded', 'built', 'builden', 'building'],
    explanation: 'The past tense of "build" is "built".',
    planet: 'earth',
    level: 1,
    questionNumber: 35,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-36',
    type: 'multiple-choice',
    content: 'What is the past participle of "lend"?',
    correctAnswer: 'lent',
    options: ['lended', 'lent', 'lenden', 'lending'],
    explanation: 'The past participle of "lend" is "lent".',
    planet: 'earth',
    level: 1,
    questionNumber: 36,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-37',
    type: 'multiple-choice',
    content: 'What is the past tense of "stand"?',
    correctAnswer: 'stood',
    options: ['standed', 'stood', 'standen', 'standing'],
    explanation: 'The past tense of "stand" is "stood".',
    planet: 'earth',
    level: 1,
    questionNumber: 37,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-38',
    type: 'multiple-choice',
    content: 'What is the past participle of "understand"?',
    correctAnswer: 'understood',
    options: ['understanded', 'understood', 'understanden', 'understanding'],
    explanation: 'The past participle of "understand" is "understood".',
    planet: 'earth',
    level: 1,
    questionNumber: 38,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-39',
    type: 'multiple-choice',
    content: 'What is the past tense of "hear"?',
    correctAnswer: 'heard',
    options: ['heared', 'heard', 'hearen', 'hearing'],
    explanation: 'The past tense of "hear" is "heard".',
    planet: 'earth',
    level: 1,
    questionNumber: 39,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-40',
    type: 'multiple-choice',
    content: 'What is the past participle of "tell"?',
    correctAnswer: 'told',
    options: ['telled', 'told', 'tellen', 'telling'],
    explanation: 'The past participle of "tell" is "told".',
    planet: 'earth',
    level: 1,
    questionNumber: 40,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-41',
    type: 'multiple-choice',
    content: 'What is the past tense of "sell"?',
    correctAnswer: 'sold',
    options: ['selled', 'sold', 'sellen', 'selling'],
    explanation: 'The past tense of "sell" is "sold".',
    planet: 'earth',
    level: 1,
    questionNumber: 41,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-42',
    type: 'multiple-choice',
    content: 'What is the past participle of "hold"?',
    correctAnswer: 'held',
    options: ['holded', 'held', 'holden', 'holding'],
    explanation: 'The past participle of "hold" is "held".',
    planet: 'earth',
    level: 1,
    questionNumber: 42,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-43',
    type: 'multiple-choice',
    content: 'What is the past tense of "read"?',
    correctAnswer: 'read',
    options: ['readed', 'read', 'reden', 'reading'],
    explanation: 'The past tense of "read" is "read" (pronounced "red").',
    planet: 'earth',
    level: 1,
    questionNumber: 43,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-44',
    type: 'multiple-choice',
    content: 'What is the past participle of "lead"?',
    correctAnswer: 'led',
    options: ['leaded', 'led', 'leaden', 'leading'],
    explanation: 'The past participle of "lead" is "led".',
    planet: 'earth',
    level: 1,
    questionNumber: 44,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-45',
    type: 'multiple-choice',
    content: 'What is the past tense of "feed"?',
    correctAnswer: 'fed',
    options: ['feeded', 'fed', 'feden', 'feeding'],
    explanation: 'The past tense of "feed" is "fed".',
    planet: 'earth',
    level: 1,
    questionNumber: 45,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-46',
    type: 'multiple-choice',
    content: 'What is the past participle of "bleed"?',
    correctAnswer: 'bled',
    options: ['bleeded', 'bled', 'bleden', 'bleeding'],
    explanation: 'The past participle of "bleed" is "bled".',
    planet: 'earth',
    level: 1,
    questionNumber: 46,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-47',
    type: 'multiple-choice',
    content: 'What is the past tense of "speed"?',
    correctAnswer: 'sped',
    options: ['speeded', 'sped', 'speden', 'speeding'],
    explanation: 'The past tense of "speed" is "sped".',
    planet: 'earth',
    level: 1,
    questionNumber: 47,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-48',
    type: 'multiple-choice',
    content: 'What is the past participle of "breed"?',
    correctAnswer: 'bred',
    options: ['breeded', 'bred', 'breden', 'breeding'],
    explanation: 'The past participle of "breed" is "bred".',
    planet: 'earth',
    level: 1,
    questionNumber: 48,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-49',
    type: 'multiple-choice',
    content: 'What is the past tense of "light"?',
    correctAnswer: 'lit',
    options: ['lighted', 'lit', 'lighten', 'lighting'],
    explanation: 'The past tense of "light" is "lit".',
    planet: 'earth',
    level: 1,
    questionNumber: 49,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-1-50',
    type: 'multiple-choice',
    content: 'What is the past participle of "strike"?',
    correctAnswer: 'struck',
    options: ['striked', 'struck', 'striken', 'striking'],
    explanation: 'The past participle of "strike" is "struck".',
    planet: 'earth',
    level: 1,
    questionNumber: 50,
    points: 10,
    difficulty: 'beginner'
  }

];

export const earthLevel2Questions: Exercise[] = [
  {
    id: 'earth-2-1',
    type: 'fill-in-blank',
    content: 'Fill in the blank: Yesterday I _____ to the store. (walk)',
    correctAnswer: 'walked',
    explanation: 'Regular verbs in past tense add -ed to the base form.',
    planet: 'earth',
    level: 2,
    questionNumber: 1,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-2',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She has _____ many letters. (write)',
    correctAnswer: 'written',
    explanation: 'The past participle of "write" is "written".',
    planet: 'earth',
    level: 2,
    questionNumber: 2,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-3',
    type: 'fill-in-blank',
    content: 'Fill in the blank: We _____ dinner at 6 PM. (eat)',
    correctAnswer: 'ate',
    explanation: 'The past tense of "eat" is "ate".',
    planet: 'earth',
    level: 2,
    questionNumber: 3,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-4',
    type: 'fill-in-blank',
    content: 'Fill in the blank: They have _____ to Paris. (go)',
    correctAnswer: 'gone',
    explanation: 'The past participle of "go" is "gone".',
    planet: 'earth',
    level: 2,
    questionNumber: 4,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-5',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I _____ a movie yesterday. (see)',
    correctAnswer: 'saw',
    explanation: 'The past tense of "see" is "saw".',
    planet: 'earth',
    level: 2,
    questionNumber: 5,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-6',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She has _____ the book. (take)',
    correctAnswer: 'taken',
    explanation: 'The past participle of "take" is "taken".',
    planet: 'earth',
    level: 2,
    questionNumber: 6,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-7',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He _____ me a present. (give)',
    correctAnswer: 'gave',
    explanation: 'The past tense of "give" is "gave".',
    planet: 'earth',
    level: 2,
    questionNumber: 7,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-8',
    type: 'fill-in-blank',
    content: 'Fill in the blank: The vase has been _____. (break)',
    correctAnswer: 'broken',
    explanation: 'The past participle of "break" is "broken".',
    planet: 'earth',
    level: 2,
    questionNumber: 8,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-9',
    type: 'fill-in-blank',
    content: 'Fill in the blank: They _____ to the party. (come)',
    correctAnswer: 'came',
    explanation: 'The past tense of "come" is "came".',
    planet: 'earth',
    level: 2,
    questionNumber: 9,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-10',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I have _____ him for years. (know)',
    correctAnswer: 'known',
    explanation: 'The past participle of "know" is "known".',
    planet: 'earth',
    level: 2,
    questionNumber: 10,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-11',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She _____ a new car. (get)',
    correctAnswer: 'got',
    explanation: 'The past tense of "get" is "got".',
    planet: 'earth',
    level: 2,
    questionNumber: 11,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-12',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He has _____ a cake. (make)',
    correctAnswer: 'made',
    explanation: 'The past participle of "make" is "made".',
    planet: 'earth',
    level: 2,
    questionNumber: 12,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-13',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I _____ about the problem. (think)',
    correctAnswer: 'thought',
    explanation: 'The past tense of "think" is "thought".',
    planet: 'earth',
    level: 2,
    questionNumber: 13,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-14',
    type: 'fill-in-blank',
    content: 'Fill in the blank: They have _____ the answer. (find)',
    correctAnswer: 'found',
    explanation: 'The past participle of "find" is "found".',
    planet: 'earth',
    level: 2,
    questionNumber: 14,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-15',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She _____ me the truth. (tell)',
    correctAnswer: 'told',
    explanation: 'The past tense of "tell" is "told".',
    planet: 'earth',
    level: 2,
    questionNumber: 15,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-16',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I have _____ happy today. (feel)',
    correctAnswer: 'felt',
    explanation: 'The past participle of "feel" is "felt".',
    planet: 'earth',
    level: 2,
    questionNumber: 16,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-17',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He _____ a doctor. (become)',
    correctAnswer: 'became',
    explanation: 'The past tense of "become" is "became".',
    planet: 'earth',
    level: 2,
    questionNumber: 17,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-18',
    type: 'fill-in-blank',
    content: 'Fill in the blank: They have _____ the building. (leave)',
    correctAnswer: 'left',
    explanation: 'The past participle of "leave" is "left".',
    planet: 'earth',
    level: 2,
    questionNumber: 18,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-19',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I _____ the book on the table. (put)',
    correctAnswer: 'put',
    explanation: 'The past tense of "put" is "put" (it remains the same).',
    planet: 'earth',
    level: 2,
    questionNumber: 19,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-20',
    type: 'fill-in-blank',
    content: 'Fill in the blank: This word has _____ a lot to me. (mean)',
    correctAnswer: 'meant',
    explanation: 'The past participle of "mean" is "meant".',
    planet: 'earth',
    level: 2,
    questionNumber: 20,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-21',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I _____ about the solution. (think)',
    correctAnswer: 'thought',
    explanation: 'The past tense of "think" is "thought".',
    planet: 'earth',
    level: 2,
    questionNumber: 21,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-22',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She has _____ lunch. (bring)',
    correctAnswer: 'brought',
    explanation: 'The past participle of "bring" is "brought".',
    planet: 'earth',
    level: 2,
    questionNumber: 22,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-23',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He _____ a new house. (buy)',
    correctAnswer: 'bought',
    explanation: 'The past tense of "buy" is "bought".',
    planet: 'earth',
    level: 2,
    questionNumber: 23,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-24',
    type: 'fill-in-blank',
    content: 'Fill in the blank: They have _____ the ball. (catch)',
    correctAnswer: 'caught',
    explanation: 'The past participle of "catch" is "caught".',
    planet: 'earth',
    level: 2,
    questionNumber: 24,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-25',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She _____ English last year. (teach)',
    correctAnswer: 'taught',
    explanation: 'The past tense of "teach" is "taught".',
    planet: 'earth',
    level: 2,
    questionNumber: 25,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-26',
    type: 'fill-in-blank',
    content: 'Fill in the blank: We have _____ for our rights. (fight)',
    correctAnswer: 'fought',
    explanation: 'The past participle of "fight" is "fought".',
    planet: 'earth',
    level: 2,
    questionNumber: 26,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-27',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I _____ my keys yesterday. (find)',
    correctAnswer: 'found',
    explanation: 'The past tense of "find" is "found".',
    planet: 'earth',
    level: 2,
    questionNumber: 27,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-28',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He has _____ his wallet. (lose)',
    correctAnswer: 'lost',
    explanation: 'The past participle of "lose" is "lost".',
    planet: 'earth',
    level: 2,
    questionNumber: 28,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-29',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She _____ the secret. (keep)',
    correctAnswer: 'kept',
    explanation: 'The past tense of "keep" is "kept".',
    planet: 'earth',
    level: 2,
    questionNumber: 29,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-30',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I have _____ well last night. (sleep)',
    correctAnswer: 'slept',
    explanation: 'The past participle of "sleep" is "slept".',
    planet: 'earth',
    level: 2,
    questionNumber: 30,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-31',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He _____ sad yesterday. (feel)',
    correctAnswer: 'felt',
    explanation: 'The past tense of "feel" is "felt".',
    planet: 'earth',
    level: 2,
    questionNumber: 31,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-32',
    type: 'fill-in-blank',
    content: 'Fill in the blank: We have _____ our friends. (meet)',
    correctAnswer: 'met',
    explanation: 'The past participle of "meet" is "met".',
    planet: 'earth',
    level: 2,
    questionNumber: 32,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-33',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She _____ the letter yesterday. (send)',
    correctAnswer: 'sent',
    explanation: 'The past tense of "send" is "sent".',
    planet: 'earth',
    level: 2,
    questionNumber: 33,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-34',
    type: 'fill-in-blank',
    content: 'Fill in the blank: They have _____ all their money. (spend)',
    correctAnswer: 'spent',
    explanation: 'The past participle of "spend" is "spent".',
    planet: 'earth',
    level: 2,
    questionNumber: 34,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-35',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He _____ a house last year. (build)',
    correctAnswer: 'built',
    explanation: 'The past tense of "build" is "built".',
    planet: 'earth',
    level: 2,
    questionNumber: 35,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-36',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I have _____ money to my friend. (lend)',
    correctAnswer: 'lent',
    explanation: 'The past participle of "lend" is "lent".',
    planet: 'earth',
    level: 2,
    questionNumber: 36,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-37',
    type: 'fill-in-blank',
    content: 'Fill in the blank: We _____ in line for hours. (stand)',
    correctAnswer: 'stood',
    explanation: 'The past tense of "stand" is "stood".',
    planet: 'earth',
    level: 2,
    questionNumber: 37,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-38',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She has _____ the lesson. (understand)',
    correctAnswer: 'understood',
    explanation: 'The past participle of "understand" is "understood".',
    planet: 'earth',
    level: 2,
    questionNumber: 38,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-39',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I _____ the music clearly. (hear)',
    correctAnswer: 'heard',
    explanation: 'The past tense of "hear" is "heard".',
    planet: 'earth',
    level: 2,
    questionNumber: 39,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-40',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He has _____ me the story. (tell)',
    correctAnswer: 'told',
    explanation: 'The past participle of "tell" is "told".',
    planet: 'earth',
    level: 2,
    questionNumber: 40,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-41',
    type: 'fill-in-blank',
    content: 'Fill in the blank: They _____ their car yesterday. (sell)',
    correctAnswer: 'sold',
    explanation: 'The past tense of "sell" is "sold".',
    planet: 'earth',
    level: 2,
    questionNumber: 41,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-42',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She has _____ the baby. (hold)',
    correctAnswer: 'held',
    explanation: 'The past participle of "hold" is "held".',
    planet: 'earth',
    level: 2,
    questionNumber: 42,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-43',
    type: 'fill-in-blank',
    content: 'Fill in the blank: I _____ the book yesterday. (read)',
    correctAnswer: 'read',
    explanation: 'The past tense of "read" is "read" (pronounced "red").',
    planet: 'earth',
    level: 2,
    questionNumber: 43,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-44',
    type: 'fill-in-blank',
    content: 'Fill in the blank: He has _____ the team. (lead)',
    correctAnswer: 'led',
    explanation: 'The past participle of "lead" is "led".',
    planet: 'earth',
    level: 2,
    questionNumber: 44,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-45',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She _____ the cat yesterday. (feed)',
    correctAnswer: 'fed',
    explanation: 'The past tense of "feed" is "fed".',
    planet: 'earth',
    level: 2,
    questionNumber: 45,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-46',
    type: 'fill-in-blank',
    content: 'Fill in the blank: The wound has _____. (bleed)',
    correctAnswer: 'bled',
    explanation: 'The past participle of "bleed" is "bled".',
    planet: 'earth',
    level: 2,
    questionNumber: 46,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-47',
    type: 'fill-in-blank',
    content: 'Fill in the blank: The car _____ down the highway. (speed)',
    correctAnswer: 'sped',
    explanation: 'The past tense of "speed" is "sped".',
    planet: 'earth',
    level: 2,
    questionNumber: 47,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-48',
    type: 'fill-in-blank',
    content: 'Fill in the blank: They have _____ horses. (breed)',
    correctAnswer: 'bred',
    explanation: 'The past participle of "breed" is "bred".',
    planet: 'earth',
    level: 2,
    questionNumber: 48,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-49',
    type: 'fill-in-blank',
    content: 'Fill in the blank: She _____ the candle. (light)',
    correctAnswer: 'lit',
    explanation: 'The past tense of "light" is "lit".',
    planet: 'earth',
    level: 2,
    questionNumber: 49,
    points: 10,
    difficulty: 'beginner'
  },
  {
    id: 'earth-2-50',
    type: 'fill-in-blank',
    content: 'Fill in the blank: The clock has _____ midnight. (strike)',
    correctAnswer: 'struck',
    explanation: 'The past participle of "strike" is "struck".',
    planet: 'earth',
    level: 2,
    questionNumber: 50,
    points: 10,
    difficulty: 'beginner'
  }
];
