import { Exercise } from '@/types/curriculum';

export const earthLevel8Questions: Exercise[] = [
  {
    id: 'earth-8-1',
    type: 'multiple-choice',
    content: 'Choose the correct tense sequence: "By the time she arrives, we _____ dinner."',
    correctAnswer: 'will have finished',
    options: ['will finish', 'will have finished', 'finished', 'are finishing'],
    explanation: 'Future perfect shows completion before a future point in time.',
    planet: 'earth',
    level: 8,
    questionNumber: 1,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-2',
    type: 'multiple-choice',
    content: 'Select the correct form: "If I _____ you were coming, I would have prepared lunch."',
    correctAnswer: 'had known',
    options: ['knew', 'had known', 'would know', 'have known'],
    explanation: 'Third conditional uses past perfect in the if-clause.',
    planet: 'earth',
    level: 8,
    questionNumber: 2,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-3',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "She _____ for three hours when I called."',
    correctAnswer: 'had been studying',
    options: ['was studying', 'had been studying', 'has been studying', 'studied'],
    explanation: 'Past perfect continuous shows duration before a past point.',
    planet: 'earth',
    level: 8,
    questionNumber: 3,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-4',
    type: 'multiple-choice',
    content: 'Select the correct form: "I wish I _____ more time yesterday."',
    correctAnswer: 'had had',
    options: ['have', 'had', 'had had', 'would have'],
    explanation: 'Wish + past perfect expresses regret about the past.',
    planet: 'earth',
    level: 8,
    questionNumber: 4,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-5',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "By next year, they _____ married for ten years."',
    correctAnswer: 'will have been',
    options: ['will be', 'will have been', 'are', 'have been'],
    explanation: 'Future perfect shows duration up to a future point.',
    planet: 'earth',
    level: 8,
    questionNumber: 5,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-6',
    type: 'fill-in-blank',
    content: 'Complete: "If she _____ (study) harder, she would have passed the exam."',
    correctAnswer: 'had studied',
    explanation: 'Third conditional requires past perfect in the if-clause.',
    planet: 'earth',
    level: 8,
    questionNumber: 6,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-7',
    type: 'multiple-choice',
    content: 'Select the correct form: "He acts as if he _____ the owner."',
    correctAnswer: 'were',
    options: ['is', 'was', 'were', 'would be'],
    explanation: 'Subjunctive mood uses "were" for all persons in hypothetical situations.',
    planet: 'earth',
    level: 8,
    questionNumber: 7,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-8',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "I would rather you _____ me the truth."',
    correctAnswer: 'told',
    options: ['tell', 'told', 'have told', 'will tell'],
    explanation: '"Would rather" is followed by past tense for present/future reference.',
    planet: 'earth',
    level: 8,
    questionNumber: 8,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-9',
    type: 'multiple-choice',
    content: 'Select the correct form: "It\'s time we _____ home."',
    correctAnswer: 'went',
    options: ['go', 'went', 'have gone', 'will go'],
    explanation: '"It\'s time" is followed by past tense for present reference.',
    planet: 'earth',
    level: 8,
    questionNumber: 9,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-10',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "She suggested that he _____ a doctor."',
    correctAnswer: 'see',
    options: ['sees', 'saw', 'see', 'would see'],
    explanation: 'Subjunctive mood uses base form after "suggest that".',
    planet: 'earth',
    level: 8,
    questionNumber: 10,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-11',
    type: 'fill-in-blank',
    content: 'Complete: "I _____ (work) here for five years by December."',
    correctAnswer: 'will have been working',
    explanation: 'Future perfect continuous shows duration up to a future point.',
    planet: 'earth',
    level: 8,
    questionNumber: 11,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-12',
    type: 'multiple-choice',
    content: 'Select the correct form: "Should you need help, _____ me."',
    correctAnswer: 'call',
    options: ['call', 'called', 'calling', 'to call'],
    explanation: 'Inverted conditional uses base form in the main clause.',
    planet: 'earth',
    level: 8,
    questionNumber: 12,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-13',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "He said he _____ the report by Friday."',
    correctAnswer: 'would finish',
    options: ['will finish', 'would finish', 'finishes', 'finished'],
    explanation: 'Reported speech changes "will" to "would".',
    planet: 'earth',
    level: 8,
    questionNumber: 13,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-14',
    type: 'multiple-choice',
    content: 'Select the correct form: "Were I you, I _____ accept the offer."',
    correctAnswer: 'would',
    options: ['will', 'would', 'should', 'could'],
    explanation: 'Inverted conditional "Were I you" requires "would" in the main clause.',
    planet: 'earth',
    level: 8,
    questionNumber: 14,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-15',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "I insist that she _____ on time."',
    correctAnswer: 'be',
    options: ['is', 'was', 'be', 'will be'],
    explanation: 'Subjunctive mood uses base form after "insist that".',
    planet: 'earth',
    level: 8,
    questionNumber: 15,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-16',
    type: 'fill-in-blank',
    content: 'Complete: "If only I _____ (listen) to your advice!"',
    correctAnswer: 'had listened',
    explanation: '"If only" + past perfect expresses regret about the past.',
    planet: 'earth',
    level: 8,
    questionNumber: 16,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-17',
    type: 'multiple-choice',
    content: 'Select the correct form: "He would have succeeded _____ he tried harder."',
    correctAnswer: 'had',
    options: ['if', 'had', 'should', 'would'],
    explanation: 'Inverted third conditional omits "if" and uses "had".',
    planet: 'earth',
    level: 8,
    questionNumber: 17,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-18',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "She behaves as though she _____ everything."',
    correctAnswer: 'knew',
    options: ['knows', 'knew', 'has known', 'will know'],
    explanation: '"As though" uses past tense for present unreal situations.',
    planet: 'earth',
    level: 8,
    questionNumber: 18,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-19',
    type: 'multiple-choice',
    content: 'Select the correct form: "I\'d sooner you _____ smoking."',
    correctAnswer: 'stopped',
    options: ['stop', 'stopped', 'have stopped', 'will stop'],
    explanation: '"Would sooner" is followed by past tense.',
    planet: 'earth',
    level: 8,
    questionNumber: 19,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-20',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "Suppose you _____ a million dollars, what would you do?"',
    correctAnswer: 'won',
    options: ['win', 'won', 'have won', 'will win'],
    explanation: '"Suppose" in hypothetical situations uses past tense.',
    planet: 'earth',
    level: 8,
    questionNumber: 20,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-21',
    type: 'correction',
    content: 'Correct the sentence: "If I would have known, I would have come."',
    correctAnswer: 'If I had known, I would have come.',
    explanation: 'Third conditional uses past perfect, not "would have" in the if-clause.',
    planet: 'earth',
    level: 8,
    questionNumber: 21,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-22',
    type: 'multiple-choice',
    content: 'Select the correct form: "The proposal _____ by the committee yesterday."',
    correctAnswer: 'was rejected',
    options: ['rejected', 'was rejected', 'has been rejected', 'had been rejected'],
    explanation: 'Past passive voice: was/were + past participle.',
    planet: 'earth',
    level: 8,
    questionNumber: 22,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-23',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "I demand that the meeting _____ postponed."',
    correctAnswer: 'be',
    options: ['is', 'was', 'be', 'will be'],
    explanation: 'Subjunctive mood uses base form after "demand that".',
    planet: 'earth',
    level: 8,
    questionNumber: 23,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-24',
    type: 'fill-in-blank',
    content: 'Complete: "She talks as if she _____ (be) the boss."',
    correctAnswer: 'were',
    explanation: 'Subjunctive "were" is used for all persons in unreal situations.',
    planet: 'earth',
    level: 8,
    questionNumber: 24,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-25',
    type: 'multiple-choice',
    content: 'Select the correct form: "Little _____ he know what awaited him."',
    correctAnswer: 'did',
    options: ['did', 'does', 'had', 'would'],
    explanation: 'Inversion with "little" requires auxiliary "did" for past tense.',
    planet: 'earth',
    level: 8,
    questionNumber: 25,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-26',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "Not until yesterday _____ the truth."',
    correctAnswer: 'did I learn',
    options: ['I learned', 'did I learn', 'I had learned', 'have I learned'],
    explanation: 'Inversion after "not until" requires auxiliary verb.',
    planet: 'earth',
    level: 8,
    questionNumber: 26,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-27',
    type: 'multiple-choice',
    content: 'Select the correct form: "Rarely _____ such dedication."',
    correctAnswer: 'have I seen',
    options: ['I have seen', 'have I seen', 'I saw', 'did I see'],
    explanation: 'Inversion with "rarely" uses present perfect for experience.',
    planet: 'earth',
    level: 8,
    questionNumber: 27,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-28',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "No sooner _____ than it started raining."',
    correctAnswer: 'had we arrived',
    options: ['we arrived', 'had we arrived', 'we had arrived', 'did we arrive'],
    explanation: '"No sooner" requires inversion with past perfect.',
    planet: 'earth',
    level: 8,
    questionNumber: 28,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-29',
    type: 'fill-in-blank',
    content: 'Complete: "Scarcely _____ (we/finish) when the bell rang."',
    correctAnswer: 'had we finished',
    explanation: '"Scarcely" requires inversion with past perfect.',
    planet: 'earth',
    level: 8,
    questionNumber: 29,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-30',
    type: 'multiple-choice',
    content: 'Select the correct form: "Under no circumstances _____ this information."',
    correctAnswer: 'should you reveal',
    options: ['you should reveal', 'should you reveal', 'you reveal', 'do you reveal'],
    explanation: 'Negative inversion requires auxiliary verb placement.',
    planet: 'earth',
    level: 8,
    questionNumber: 30,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-31',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "She said she _____ the book the previous week."',
    correctAnswer: 'had read',
    options: ['read', 'had read', 'has read', 'would read'],
    explanation: 'Reported speech: past perfect for actions before the reporting time.',
    planet: 'earth',
    level: 8,
    questionNumber: 31,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-32',
    type: 'multiple-choice',
    content: 'Select the correct form: "He told me he _____ there many times."',
    correctAnswer: 'had been',
    options: ['was', 'had been', 'has been', 'would be'],
    explanation: 'Reported speech changes present perfect to past perfect.',
    planet: 'earth',
    level: 8,
    questionNumber: 32,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-33',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "They announced that the flight _____ delayed."',
    correctAnswer: 'had been',
    options: ['was', 'had been', 'has been', 'would be'],
    explanation: 'Past perfect passive in reported speech for prior events.',
    planet: 'earth',
    level: 8,
    questionNumber: 33,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-34',
    type: 'fill-in-blank',
    content: 'Complete: "She mentioned that she _____ (work) there for years."',
    correctAnswer: 'had been working',
    explanation: 'Past perfect continuous in reported speech for duration.',
    planet: 'earth',
    level: 8,
    questionNumber: 34,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-35',
    type: 'multiple-choice',
    content: 'Select the correct form: "I wish I _____ more careful yesterday."',
    correctAnswer: 'had been',
    options: ['was', 'had been', 'have been', 'would be'],
    explanation: 'Wish + past perfect for regret about past situations.',
    planet: 'earth',
    level: 8,
    questionNumber: 35,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-36',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "If she _____ harder, she would be successful now."',
    correctAnswer: 'had worked',
    options: ['worked', 'had worked', 'has worked', 'works'],
    explanation: 'Mixed conditional: past perfect condition, present result.',
    planet: 'earth',
    level: 8,
    questionNumber: 36,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-37',
    type: 'multiple-choice',
    content: 'Select the correct form: "But for your help, I _____ failed."',
    correctAnswer: 'would have',
    options: ['would', 'would have', 'will have', 'had'],
    explanation: '"But for" means "if not for" and uses conditional perfect.',
    planet: 'earth',
    level: 8,
    questionNumber: 37,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-38',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "Provided that you _____ early, we can go together."',
    correctAnswer: 'arrive',
    options: ['arrive', 'arrived', 'will arrive', 'have arrived'],
    explanation: '"Provided that" uses present tense for future conditions.',
    planet: 'earth',
    level: 8,
    questionNumber: 38,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-39',
    type: 'fill-in-blank',
    content: 'Complete: "Unless you _____ (hurry), you will miss the train."',
    correctAnswer: 'hurry',
    explanation: '"Unless" (meaning "if not") uses present tense for future conditions.',
    planet: 'earth',
    level: 8,
    questionNumber: 39,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-40',
    type: 'multiple-choice',
    content: 'Select the correct form: "In case you _____ me, I\'ll be at home."',
    correctAnswer: 'need',
    options: ['need', 'needed', 'will need', 'would need'],
    explanation: '"In case" uses present tense for future possibilities.',
    planet: 'earth',
    level: 8,
    questionNumber: 40,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-41',
    type: 'correction',
    content: 'Correct the sentence: "I would rather you didn\'t told me."',
    correctAnswer: 'I would rather you didn\'t tell me.',
    explanation: '"Would rather" + negative uses "didn\'t" + base form.',
    planet: 'earth',
    level: 8,
    questionNumber: 41,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-42',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "It\'s high time you _____ responsibility."',
    correctAnswer: 'took',
    options: ['take', 'took', 'have taken', 'will take'],
    explanation: '"It\'s high time" is followed by past tense.',
    planet: 'earth',
    level: 8,
    questionNumber: 42,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-43',
    type: 'multiple-choice',
    content: 'Select the correct form: "The doctor recommended that she _____ rest."',
    correctAnswer: 'take',
    options: ['takes', 'took', 'take', 'would take'],
    explanation: 'Subjunctive mood uses base form after "recommend that".',
    planet: 'earth',
    level: 8,
    questionNumber: 43,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-44',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "So tired _____ that I fell asleep immediately."',
    correctAnswer: 'was I',
    options: ['I was', 'was I', 'I am', 'am I'],
    explanation: 'Inversion after "so + adjective" for emphasis.',
    planet: 'earth',
    level: 8,
    questionNumber: 44,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-45',
    type: 'fill-in-blank',
    content: 'Complete: "Never _____ (I/see) such a beautiful sunset."',
    correctAnswer: 'have I seen',
    explanation: 'Inversion with "never" uses present perfect for experience.',
    planet: 'earth',
    level: 8,
    questionNumber: 45,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-46',
    type: 'multiple-choice',
    content: 'Select the correct form: "Only when I arrived _____ the truth."',
    correctAnswer: 'did I discover',
    options: ['I discovered', 'did I discover', 'I had discovered', 'have I discovered'],
    explanation: 'Inversion after "only when" requires auxiliary verb.',
    planet: 'earth',
    level: 8,
    questionNumber: 46,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-47',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "Hardly _____ when the phone rang."',
    correctAnswer: 'had I sat down',
    options: ['I sat down', 'had I sat down', 'I had sat down', 'did I sit down'],
    explanation: '"Hardly" requires inversion with past perfect.',
    planet: 'earth',
    level: 8,
    questionNumber: 47,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-48',
    type: 'multiple-choice',
    content: 'Select the correct form: "At no time _____ give up hope."',
    correctAnswer: 'should you',
    options: ['you should', 'should you', 'you will', 'will you'],
    explanation: 'Negative inversion with "at no time" uses modal auxiliary.',
    planet: 'earth',
    level: 8,
    questionNumber: 48,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-49',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "Not only _____ late, but he also forgot his keys."',
    correctAnswer: 'was he',
    options: ['he was', 'was he', 'he is', 'is he'],
    explanation: 'Inversion after "not only" at the beginning of a sentence.',
    planet: 'earth',
    level: 8,
    questionNumber: 49,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-8-50',
    type: 'correction',
    content: 'Correct the sentence: "If I was you, I would accept the offer."',
    correctAnswer: 'If I were you, I would accept the offer.',
    explanation: 'Subjunctive "were" is used for all persons in hypothetical conditions.',
    planet: 'earth',
    level: 8,
    questionNumber: 50,
    points: 10,
    difficulty: 'advanced'
  }
]; 