import { Exercise } from '@/types/curriculum';

export const earthLevel10Questions: Exercise[] = [
  {
    id: 'earth-10-1',
    type: 'multiple-choice',
    content: 'Choose the most sophisticated form: "The research _____ for decades before the breakthrough was achieved."',
    correctAnswer: 'had been being conducted',
    options: ['was being conducted', 'had been conducted', 'had been being conducted', 'would have been conducted'],
    explanation: 'Past perfect continuous passive shows duration before a past event.',
    planet: 'earth',
    level: 10,
    questionNumber: 1,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-2',
    type: 'fill-in-blank',
    content: 'Complete the complex conditional: "Were it not to have been for the intervention, the crisis _____ (escalate) beyond control."',
    correctAnswer: 'would have escalated',
    explanation: 'Complex inverted conditional with perfect infinitive.',
    planet: 'earth',
    level: 10,
    questionNumber: 2,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-3',
    type: 'multiple-choice',
    content: 'Select the correct sophisticated structure: "The manuscript _____ publication when the author decided to make revisions."',
    correctAnswer: 'was on the verge of being submitted for',
    options: ['was about to submit for', 'was on the verge of being submitted for', 'was going to be submitted for', 'would be submitted for'],
    explanation: 'Complex passive structure with idiomatic expression.',
    planet: 'earth',
    level: 10,
    questionNumber: 3,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-4',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The committee recommended that the proposal _____ before the next meeting."',
    correctAnswer: 'be thoroughly reviewed',
    options: ['is thoroughly reviewed', 'be thoroughly reviewed', 'should be thoroughly reviewed', 'will be thoroughly reviewed'],
    explanation: 'Subjunctive passive with adverbial modification.',
    planet: 'earth',
    level: 10,
    questionNumber: 4,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-5',
    type: 'correction',
    content: 'Correct the sophisticated error: "The building would have been being constructed for two years by now if the permits had been approved."',
    correctAnswer: 'The building would have been under construction for two years by now if the permits had been approved.',
    explanation: 'Avoid awkward continuous passive; use idiomatic expression instead.',
    planet: 'earth',
    level: 10,
    questionNumber: 5,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-6',
    type: 'fill-in-blank',
    content: 'Complete: "Not only _____ (the data/analyze) incorrectly, but the conclusions were also flawed."',
    correctAnswer: 'had the data been analyzed',
    explanation: 'Inversion with "not only" using past perfect passive.',
    planet: 'earth',
    level: 10,
    questionNumber: 6,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-7',
    type: 'multiple-choice',
    content: 'Select the most precise form: "The negotiations _____ for months when the breakthrough occurred."',
    correctAnswer: 'had been at a standstill',
    options: ['were stalled', 'had been stalled', 'had been at a standstill', 'would have been stalled'],
    explanation: 'Idiomatic expression with past perfect for sophisticated style.',
    planet: 'earth',
    level: 10,
    questionNumber: 7,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-8',
    type: 'multiple-choice',
    content: 'Choose the correct complex structure: "The policy _____ implementation when public opposition emerged."',
    correctAnswer: 'was in the process of being prepared for',
    options: ['was being prepared for', 'was in the process of being prepared for', 'had been prepared for', 'would be prepared for'],
    explanation: 'Complex passive structure with progressive aspect.',
    planet: 'earth',
    level: 10,
    questionNumber: 8,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-9',
    type: 'fill-in-blank',
    content: 'Complete the sophisticated conditional: "Should the circumstances _____ (prove) favorable, the project will proceed as planned."',
    correctAnswer: 'prove',
    explanation: 'Inverted conditional with subjunctive-like usage.',
    planet: 'earth',
    level: 10,
    questionNumber: 9,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-10',
    type: 'multiple-choice',
    content: 'Select the most sophisticated form: "The discovery _____ scientific understanding of the phenomenon."',
    correctAnswer: 'was instrumental in revolutionizing',
    options: ['revolutionized', 'was revolutionary for', 'was instrumental in revolutionizing', 'had revolutionized'],
    explanation: 'Sophisticated causative structure with gerund.',
    planet: 'earth',
    level: 10,
    questionNumber: 10,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-11',
    type: 'multiple-choice',
    content: 'Choose the correct advanced structure: "The evidence _____ the defendant\'s innocence."',
    correctAnswer: 'was conducive to establishing',
    options: ['established', 'was establishing', 'was conducive to establishing', 'had established'],
    explanation: 'Sophisticated structure with adjective + preposition + gerund.',
    planet: 'earth',
    level: 10,
    questionNumber: 11,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-12',
    type: 'correction',
    content: 'Refine this sentence: "The report was being written by the team for weeks."',
    correctAnswer: 'The report had been in preparation by the team for weeks.',
    explanation: 'Use more sophisticated expression instead of simple continuous passive.',
    planet: 'earth',
    level: 10,
    questionNumber: 12,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-13',
    type: 'fill-in-blank',
    content: 'Complete: "Rarely _____ (such meticulous attention/pay) to detail in modern research."',
    correctAnswer: 'is such meticulous attention paid',
    explanation: 'Inversion with "rarely" using present passive with complex noun phrase.',
    planet: 'earth',
    level: 10,
    questionNumber: 13,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-14',
    type: 'multiple-choice',
    content: 'Select the most refined form: "The theory _____ widespread acceptance among scholars."',
    correctAnswer: 'has gained',
    options: ['gained', 'has gained', 'was gaining', 'had gained'],
    explanation: 'Present perfect for achievement with continuing relevance.',
    planet: 'earth',
    level: 10,
    questionNumber: 14,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-15',
    type: 'multiple-choice',
    content: 'Choose the sophisticated structure: "The proposal _____ consideration by the board."',
    correctAnswer: 'merits serious',
    options: ['needs', 'requires', 'merits serious', 'demands'],
    explanation: 'Sophisticated verb choice with appropriate modification.',
    planet: 'earth',
    level: 10,
    questionNumber: 15,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-16',
    type: 'fill-in-blank',
    content: 'Complete the complex passive: "The manuscript _____ (subject) to rigorous peer review before publication."',
    correctAnswer: 'will be subjected',
    explanation: 'Future passive with sophisticated verb choice.',
    planet: 'earth',
    level: 10,
    questionNumber: 16,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-17',
    type: 'multiple-choice',
    content: 'Select the most precise form: "The research findings _____ our understanding of the subject."',
    correctAnswer: 'have fundamentally altered',
    options: ['changed', 'have changed', 'have fundamentally altered', 'altered'],
    explanation: 'Present perfect with sophisticated adverbial modification.',
    planet: 'earth',
    level: 10,
    questionNumber: 17,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-18',
    type: 'multiple-choice',
    content: 'Choose the advanced conditional: "_____ the funding been secured earlier, the project would have proceeded smoothly."',
    correctAnswer: 'Had',
    options: ['If', 'Had', 'Should', 'Were'],
    explanation: 'Inverted third conditional for sophisticated style.',
    planet: 'earth',
    level: 10,
    questionNumber: 18,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-19',
    type: 'correction',
    content: 'Elevate this sentence: "The problem needs to be solved quickly."',
    correctAnswer: 'The problem requires immediate resolution.',
    explanation: 'Use more sophisticated vocabulary and nominalization.',
    planet: 'earth',
    level: 10,
    questionNumber: 19,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-20',
    type: 'fill-in-blank',
    content: 'Complete: "Seldom _____ (such comprehensive measures/implement) to address the issue."',
    correctAnswer: 'have such comprehensive measures been implemented',
    explanation: 'Inversion with "seldom" using present perfect passive.',
    planet: 'earth',
    level: 10,
    questionNumber: 20,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-21',
    type: 'multiple-choice',
    content: 'Select the most sophisticated structure: "The innovation _____ a paradigm shift in the industry."',
    correctAnswer: 'precipitated',
    options: ['caused', 'led to', 'precipitated', 'resulted in'],
    explanation: 'Sophisticated verb choice for academic/formal register.',
    planet: 'earth',
    level: 10,
    questionNumber: 21,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-22',
    type: 'multiple-choice',
    content: 'Choose the refined form: "The committee\'s decision _____ considerable controversy."',
    correctAnswer: 'engendered',
    options: ['caused', 'created', 'engendered', 'made'],
    explanation: 'Sophisticated verb for formal academic writing.',
    planet: 'earth',
    level: 10,
    questionNumber: 22,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-23',
    type: 'fill-in-blank',
    content: 'Complete the sophisticated structure: "The data _____ (corroborate) the hypothesis put forward by the researchers."',
    correctAnswer: 'serves to corroborate',
    explanation: 'Sophisticated structure with infinitive of purpose.',
    planet: 'earth',
    level: 10,
    questionNumber: 23,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-24',
    type: 'multiple-choice',
    content: 'Select the most precise form: "The study _____ new insights into the phenomenon."',
    correctAnswer: 'has yielded',
    options: ['gave', 'provided', 'has yielded', 'offered'],
    explanation: 'Sophisticated verb choice with present perfect aspect.',
    planet: 'earth',
    level: 10,
    questionNumber: 24,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-25',
    type: 'multiple-choice',
    content: 'Choose the advanced structure: "The findings _____ the need for further investigation."',
    correctAnswer: 'underscore',
    options: ['show', 'indicate', 'underscore', 'suggest'],
    explanation: 'Sophisticated verb for emphasizing importance.',
    planet: 'earth',
    level: 10,
    questionNumber: 25,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-26',
    type: 'correction',
    content: 'Enhance this sentence: "The method was used by many researchers."',
    correctAnswer: 'The methodology was widely adopted by the research community.',
    explanation: 'Use more sophisticated vocabulary and structure.',
    planet: 'earth',
    level: 10,
    questionNumber: 26,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-27',
    type: 'fill-in-blank',
    content: 'Complete: "Never before _____ (such a comprehensive analysis/undertake) of this complex phenomenon."',
    correctAnswer: 'has such a comprehensive analysis been undertaken',
    explanation: 'Inversion with "never before" using present perfect passive.',
    planet: 'earth',
    level: 10,
    questionNumber: 27,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-28',
    type: 'multiple-choice',
    content: 'Select the most sophisticated form: "The research _____ our understanding of the subject matter."',
    correctAnswer: 'has considerably enhanced',
    options: ['improved', 'has improved', 'has considerably enhanced', 'enhanced'],
    explanation: 'Present perfect with sophisticated adverbial modification.',
    planet: 'earth',
    level: 10,
    questionNumber: 28,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-29',
    type: 'multiple-choice',
    content: 'Choose the refined structure: "The theory _____ empirical validation."',
    correctAnswer: 'lacks',
    options: ['needs', 'requires', 'lacks', 'wants'],
    explanation: 'Sophisticated verb choice for academic discourse.',
    planet: 'earth',
    level: 10,
    questionNumber: 29,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-30',
    type: 'fill-in-blank',
    content: 'Complete the advanced passive: "The proposal _____ (scrutinize) by experts in the field."',
    correctAnswer: 'will be scrutinized',
    explanation: 'Future passive with sophisticated verb choice.',
    planet: 'earth',
    level: 10,
    questionNumber: 30,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-31',
    type: 'multiple-choice',
    content: 'Select the most precise form: "The evidence _____ the researchers\' hypothesis."',
    correctAnswer: 'substantiates',
    options: ['supports', 'proves', 'substantiates', 'confirms'],
    explanation: 'Sophisticated verb for academic validation.',
    planet: 'earth',
    level: 10,
    questionNumber: 31,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-32',
    type: 'multiple-choice',
    content: 'Choose the advanced form: "The study _____ significant implications for future research."',
    correctAnswer: 'portends',
    options: ['has', 'suggests', 'portends', 'indicates'],
    explanation: 'Sophisticated verb for indicating future consequences.',
    planet: 'earth',
    level: 10,
    questionNumber: 32,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-33',
    type: 'correction',
    content: 'Refine this academic sentence: "The results show that the hypothesis is correct."',
    correctAnswer: 'The findings corroborate the validity of the hypothesis.',
    explanation: 'Use more sophisticated academic vocabulary and structure.',
    planet: 'earth',
    level: 10,
    questionNumber: 33,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-34',
    type: 'fill-in-blank',
    content: 'Complete: "Little _____ (the researchers/anticipate) the profound impact of their discovery."',
    correctAnswer: 'did the researchers anticipate',
    explanation: 'Inversion with "little" using sophisticated verb choice.',
    planet: 'earth',
    level: 10,
    questionNumber: 34,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-35',
    type: 'multiple-choice',
    content: 'Select the most sophisticated structure: "The methodology _____ rigorous testing."',
    correctAnswer: 'underwent',
    options: ['had', 'received', 'underwent', 'experienced'],
    explanation: 'Sophisticated verb for describing process.',
    planet: 'earth',
    level: 10,
    questionNumber: 35,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-36',
    type: 'multiple-choice',
    content: 'Choose the refined form: "The research _____ new avenues for investigation."',
    correctAnswer: 'has opened up',
    options: ['created', 'made', 'has opened up', 'provided'],
    explanation: 'Idiomatic phrasal verb with present perfect aspect.',
    planet: 'earth',
    level: 10,
    questionNumber: 36,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-37',
    type: 'fill-in-blank',
    content: 'Complete the sophisticated conditional: "Were the conditions _____ (optimize), the results would be significantly improved."',
    correctAnswer: 'to be optimized',
    explanation: 'Inverted conditional with passive infinitive.',
    planet: 'earth',
    level: 10,
    questionNumber: 37,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-38',
    type: 'multiple-choice',
    content: 'Select the most precise form: "The data _____ careful analysis."',
    correctAnswer: 'warrants',
    options: ['needs', 'requires', 'warrants', 'demands'],
    explanation: 'Sophisticated verb indicating justified necessity.',
    planet: 'earth',
    level: 10,
    questionNumber: 38,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-39',
    type: 'multiple-choice',
    content: 'Choose the advanced structure: "The findings _____ established theories."',
    correctAnswer: 'call into question',
    options: ['question', 'doubt', 'call into question', 'challenge'],
    explanation: 'Sophisticated idiomatic expression for academic discourse.',
    planet: 'earth',
    level: 10,
    questionNumber: 39,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-40',
    type: 'correction',
    content: 'Elevate this sentence: "The experiment was done carefully by the team."',
    correctAnswer: 'The experiment was conducted with meticulous precision by the research team.',
    explanation: 'Use more sophisticated vocabulary and detailed modification.',
    planet: 'earth',
    level: 10,
    questionNumber: 40,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-41',
    type: 'fill-in-blank',
    content: 'Complete: "Hardly _____ (the implications/become) apparent when new questions arose."',
    correctAnswer: 'had the implications become',
    explanation: 'Inversion with "hardly" using past perfect.',
    planet: 'earth',
    level: 10,
    questionNumber: 41,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-42',
    type: 'multiple-choice',
    content: 'Select the most sophisticated form: "The study _____ conventional wisdom."',
    correctAnswer: 'challenges',
    options: ['questions', 'doubts', 'challenges', 'disputes'],
    explanation: 'Sophisticated verb for academic disagreement.',
    planet: 'earth',
    level: 10,
    questionNumber: 42,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-43',
    type: 'multiple-choice',
    content: 'Choose the refined structure: "The research _____ significant breakthroughs."',
    correctAnswer: 'has culminated in',
    options: ['led to', 'resulted in', 'has culminated in', 'produced'],
    explanation: 'Sophisticated phrasal verb with present perfect aspect.',
    planet: 'earth',
    level: 10,
    questionNumber: 43,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-44',
    type: 'fill-in-blank',
    content: 'Complete the advanced structure: "The methodology _____ (refine) through iterative testing."',
    correctAnswer: 'was refined',
    explanation: 'Past passive with sophisticated academic vocabulary.',
    planet: 'earth',
    level: 10,
    questionNumber: 44,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-45',
    type: 'multiple-choice',
    content: 'Select the most precise form: "The theory _____ extensive empirical support."',
    correctAnswer: 'enjoys',
    options: ['has', 'receives', 'enjoys', 'gets'],
    explanation: 'Sophisticated verb for describing theoretical acceptance.',
    planet: 'earth',
    level: 10,
    questionNumber: 45,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-46',
    type: 'multiple-choice',
    content: 'Choose the advanced form: "The discovery _____ a new era in scientific research."',
    correctAnswer: 'ushered in',
    options: ['started', 'began', 'ushered in', 'initiated'],
    explanation: 'Sophisticated phrasal verb for marking beginnings.',
    planet: 'earth',
    level: 10,
    questionNumber: 46,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-47',
    type: 'correction',
    content: 'Enhance this conclusion: "The study proves that the theory is right."',
    correctAnswer: 'The investigation provides compelling evidence for the validity of the theoretical framework.',
    explanation: 'Use more sophisticated academic language and avoid absolute claims.',
    planet: 'earth',
    level: 10,
    questionNumber: 47,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-48',
    type: 'fill-in-blank',
    content: 'Complete: "Scarcely _____ (the research/commence) when unexpected challenges emerged."',
    correctAnswer: 'had the research commenced',
    explanation: 'Inversion with "scarcely" using sophisticated vocabulary.',
    planet: 'earth',
    level: 10,
    questionNumber: 48,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-49',
    type: 'multiple-choice',
    content: 'Select the most sophisticated structure: "The findings _____ further investigation."',
    correctAnswer: 'necessitate',
    options: ['need', 'require', 'necessitate', 'call for'],
    explanation: 'Sophisticated verb indicating logical requirement.',
    planet: 'earth',
    level: 10,
    questionNumber: 49,
    points: 10,
    difficulty: 'advanced'
  },
  {
    id: 'earth-10-50',
    type: 'multiple-choice',
    content: 'Choose the ultimate mastery form: "The research _____ our fundamental understanding of the phenomenon."',
    correctAnswer: 'has revolutionized',
    options: ['changed', 'improved', 'has revolutionized', 'affected'],
    explanation: 'Sophisticated verb with present perfect for ultimate impact.',
    planet: 'earth',
    level: 10,
    questionNumber: 50,
    points: 10,
    difficulty: 'advanced'
  }
]; 