import { Exercise } from '@/types/curriculum';

export const earthLevel5Questions: Exercise[] = [
  {
    id: 'earth-5-1',
    type: 'multiple-choice',
    content: 'What is the past participle of "eat"?',
    correctAnswer: 'eaten',
    options: ['ate', 'eaten', 'eating', 'eats'],
    explanation: 'The past participle of "eat" is "eaten".',
    planet: 'earth',
    level: 5,
    questionNumber: 1,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-2',
    type: 'multiple-choice',
    content: 'Choose the correct form: "I have _____ this book before."',
    correctAnswer: 'read',
    options: ['read', 'reading', 'reads', 'readed'],
    explanation: 'Present perfect uses "have/has + past participle".',
    planet: 'earth',
    level: 5,
    questionNumber: 2,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-3',
    type: 'multiple-choice',
    content: 'What is the past participle of "go"?',
    correctAnswer: 'gone',
    options: ['went', 'gone', 'going', 'goes'],
    explanation: 'The past participle of "go" is "gone".',
    planet: 'earth',
    level: 5,
    questionNumber: 3,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-4',
    type: 'fill-in-blank',
    content: 'Complete: "She has _____ (write) three letters today."',
    correctAnswer: 'written',
    explanation: 'The past participle of "write" is "written".',
    planet: 'earth',
    level: 5,
    questionNumber: 4,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-5',
    type: 'multiple-choice',
    content: 'Choose the correct form: "They have _____ to Paris twice."',
    correctAnswer: 'been',
    options: ['be', 'been', 'being', 'was'],
    explanation: 'The past participle of "be" is "been".',
    planet: 'earth',
    level: 5,
    questionNumber: 5,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-6',
    type: 'multiple-choice',
    content: 'What is the past participle of "take"?',
    correctAnswer: 'taken',
    options: ['took', 'taken', 'taking', 'takes'],
    explanation: 'The past participle of "take" is "taken".',
    planet: 'earth',
    level: 5,
    questionNumber: 6,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-7',
    type: 'multiple-choice',
    content: 'Choose the correct form: "He has _____ his homework."',
    correctAnswer: 'finished',
    options: ['finish', 'finished', 'finishing', 'finishes'],
    explanation: 'Regular verbs form past participle by adding -ed.',
    planet: 'earth',
    level: 5,
    questionNumber: 7,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-8',
    type: 'fill-in-blank',
    content: 'Complete: "We have _____ (see) that movie already."',
    correctAnswer: 'seen',
    explanation: 'The past participle of "see" is "seen".',
    planet: 'earth',
    level: 5,
    questionNumber: 8,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-9',
    type: 'multiple-choice',
    content: 'What is the past participle of "break"?',
    correctAnswer: 'broken',
    options: ['broke', 'broken', 'breaking', 'breaks'],
    explanation: 'The past participle of "break" is "broken".',
    planet: 'earth',
    level: 5,
    questionNumber: 9,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-10',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The window has been _____."',
    correctAnswer: 'broken',
    options: ['break', 'broke', 'broken', 'breaking'],
    explanation: 'Passive voice uses "been + past participle".',
    planet: 'earth',
    level: 5,
    questionNumber: 10,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-11',
    type: 'multiple-choice',
    content: 'What is the past participle of "give"?',
    correctAnswer: 'given',
    options: ['gave', 'given', 'giving', 'gives'],
    explanation: 'The past participle of "give" is "given".',
    planet: 'earth',
    level: 5,
    questionNumber: 11,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-12',
    type: 'fill-in-blank',
    content: 'Complete: "I have _____ (know) him for years."',
    correctAnswer: 'known',
    explanation: 'The past participle of "know" is "known".',
    planet: 'earth',
    level: 5,
    questionNumber: 12,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-13',
    type: 'multiple-choice',
    content: 'Choose the correct form: "She has _____ a beautiful song."',
    correctAnswer: 'sung',
    options: ['sing', 'sang', 'sung', 'singing'],
    explanation: 'The past participle of "sing" is "sung".',
    planet: 'earth',
    level: 5,
    questionNumber: 13,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-14',
    type: 'multiple-choice',
    content: 'What is the past participle of "fly"?',
    correctAnswer: 'flown',
    options: ['flew', 'flown', 'flying', 'flies'],
    explanation: 'The past participle of "fly" is "flown".',
    planet: 'earth',
    level: 5,
    questionNumber: 14,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-15',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The bird has _____ away."',
    correctAnswer: 'flown',
    options: ['fly', 'flew', 'flown', 'flying'],
    explanation: 'Present perfect: has + past participle (flown).',
    planet: 'earth',
    level: 5,
    questionNumber: 15,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-16',
    type: 'fill-in-blank',
    content: 'Complete: "They have _____ (come) to visit us."',
    correctAnswer: 'come',
    explanation: 'The past participle of "come" is "come" (same as base form).',
    planet: 'earth',
    level: 5,
    questionNumber: 16,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-17',
    type: 'multiple-choice',
    content: 'What is the past participle of "drink"?',
    correctAnswer: 'drunk',
    options: ['drank', 'drunk', 'drinking', 'drinks'],
    explanation: 'The past participle of "drink" is "drunk".',
    planet: 'earth',
    level: 5,
    questionNumber: 17,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-18',
    type: 'multiple-choice',
    content: 'Choose the correct form: "He has _____ all the water."',
    correctAnswer: 'drunk',
    options: ['drink', 'drank', 'drunk', 'drinking'],
    explanation: 'Present perfect uses past participle "drunk".',
    planet: 'earth',
    level: 5,
    questionNumber: 18,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-19',
    type: 'multiple-choice',
    content: 'What is the past participle of "swim"?',
    correctAnswer: 'swum',
    options: ['swam', 'swum', 'swimming', 'swims'],
    explanation: 'The past participle of "swim" is "swum".',
    planet: 'earth',
    level: 5,
    questionNumber: 19,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-20',
    type: 'fill-in-blank',
    content: 'Complete: "We have _____ (swim) in this pool before."',
    correctAnswer: 'swum',
    explanation: 'The past participle of "swim" is "swum".',
    planet: 'earth',
    level: 5,
    questionNumber: 20,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-21',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The letter has been _____."',
    correctAnswer: 'sent',
    options: ['send', 'sent', 'sending', 'sends'],
    explanation: 'Passive voice: has been + past participle (sent).',
    planet: 'earth',
    level: 5,
    questionNumber: 21,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-22',
    type: 'multiple-choice',
    content: 'What is the past participle of "run"?',
    correctAnswer: 'run',
    options: ['ran', 'run', 'running', 'runs'],
    explanation: 'The past participle of "run" is "run" (same as base form).',
    planet: 'earth',
    level: 5,
    questionNumber: 22,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-23',
    type: 'multiple-choice',
    content: 'Choose the correct form: "She has _____ five miles today."',
    correctAnswer: 'run',
    options: ['run', 'ran', 'running', 'runs'],
    explanation: 'Present perfect: has + past participle (run).',
    planet: 'earth',
    level: 5,
    questionNumber: 23,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-24',
    type: 'fill-in-blank',
    content: 'Complete: "I have _____ (lose) my keys."',
    correctAnswer: 'lost',
    explanation: 'The past participle of "lose" is "lost".',
    planet: 'earth',
    level: 5,
    questionNumber: 24,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-25',
    type: 'multiple-choice',
    content: 'What is the past participle of "find"?',
    correctAnswer: 'found',
    options: ['find', 'found', 'finding', 'finds'],
    explanation: 'The past participle of "find" is "found".',
    planet: 'earth',
    level: 5,
    questionNumber: 25,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-26',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The treasure has been _____."',
    correctAnswer: 'found',
    options: ['find', 'found', 'finding', 'finds'],
    explanation: 'Passive voice: has been + past participle (found).',
    planet: 'earth',
    level: 5,
    questionNumber: 26,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-27',
    type: 'multiple-choice',
    content: 'What is the past participle of "speak"?',
    correctAnswer: 'spoken',
    options: ['spoke', 'spoken', 'speaking', 'speaks'],
    explanation: 'The past participle of "speak" is "spoken".',
    planet: 'earth',
    level: 5,
    questionNumber: 27,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-28',
    type: 'fill-in-blank',
    content: 'Complete: "He has _____ (speak) to the manager."',
    correctAnswer: 'spoken',
    explanation: 'The past participle of "speak" is "spoken".',
    planet: 'earth',
    level: 5,
    questionNumber: 28,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-29',
    type: 'multiple-choice',
    content: 'Choose the correct form: "They have _____ the house."',
    correctAnswer: 'bought',
    options: ['buy', 'bought', 'buying', 'buys'],
    explanation: 'The past participle of "buy" is "bought".',
    planet: 'earth',
    level: 5,
    questionNumber: 29,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-30',
    type: 'multiple-choice',
    content: 'What is the past participle of "teach"?',
    correctAnswer: 'taught',
    options: ['teach', 'taught', 'teaching', 'teaches'],
    explanation: 'The past participle of "teach" is "taught".',
    planet: 'earth',
    level: 5,
    questionNumber: 30,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-31',
    type: 'correction',
    content: 'Correct the sentence: "I have ate lunch already."',
    correctAnswer: 'I have eaten lunch already.',
    explanation: 'Use the past participle "eaten", not the past tense "ate".',
    planet: 'earth',
    level: 5,
    questionNumber: 31,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-32',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The lesson has been _____."',
    correctAnswer: 'taught',
    options: ['teach', 'taught', 'teaching', 'teaches'],
    explanation: 'Passive voice: has been + past participle (taught).',
    planet: 'earth',
    level: 5,
    questionNumber: 32,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-33',
    type: 'fill-in-blank',
    content: 'Complete: "She has _____ (bring) her books."',
    correctAnswer: 'brought',
    explanation: 'The past participle of "bring" is "brought".',
    planet: 'earth',
    level: 5,
    questionNumber: 33,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-34',
    type: 'multiple-choice',
    content: 'What is the past participle of "catch"?',
    correctAnswer: 'caught',
    options: ['catch', 'caught', 'catching', 'catches'],
    explanation: 'The past participle of "catch" is "caught".',
    planet: 'earth',
    level: 5,
    questionNumber: 34,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-35',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The ball has been _____."',
    correctAnswer: 'caught',
    options: ['catch', 'caught', 'catching', 'catches'],
    explanation: 'Passive voice: has been + past participle (caught).',
    planet: 'earth',
    level: 5,
    questionNumber: 35,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-36',
    type: 'multiple-choice',
    content: 'What is the past participle of "think"?',
    correctAnswer: 'thought',
    options: ['think', 'thought', 'thinking', 'thinks'],
    explanation: 'The past participle of "think" is "thought".',
    planet: 'earth',
    level: 5,
    questionNumber: 36,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-37',
    type: 'fill-in-blank',
    content: 'Complete: "I have _____ (think) about this problem."',
    correctAnswer: 'thought',
    explanation: 'The past participle of "think" is "thought".',
    planet: 'earth',
    level: 5,
    questionNumber: 37,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-38',
    type: 'multiple-choice',
    content: 'Choose the correct form: "He has _____ the truth."',
    correctAnswer: 'told',
    options: ['tell', 'told', 'telling', 'tells'],
    explanation: 'The past participle of "tell" is "told".',
    planet: 'earth',
    level: 5,
    questionNumber: 38,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-39',
    type: 'multiple-choice',
    content: 'What is the past participle of "feel"?',
    correctAnswer: 'felt',
    options: ['feel', 'felt', 'feeling', 'feels'],
    explanation: 'The past participle of "feel" is "felt".',
    planet: 'earth',
    level: 5,
    questionNumber: 39,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-40',
    type: 'correction',
    content: 'Correct the sentence: "She has went to the store."',
    correctAnswer: 'She has gone to the store.',
    explanation: 'Use the past participle "gone", not the past tense "went".',
    planet: 'earth',
    level: 5,
    questionNumber: 40,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-41',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The work has been _____."',
    correctAnswer: 'done',
    options: ['do', 'did', 'done', 'doing'],
    explanation: 'The past participle of "do" is "done".',
    planet: 'earth',
    level: 5,
    questionNumber: 41,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-42',
    type: 'fill-in-blank',
    content: 'Complete: "We have _____ (make) a decision."',
    correctAnswer: 'made',
    explanation: 'The past participle of "make" is "made".',
    planet: 'earth',
    level: 5,
    questionNumber: 42,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-43',
    type: 'multiple-choice',
    content: 'What is the past participle of "wear"?',
    correctAnswer: 'worn',
    options: ['wear', 'wore', 'worn', 'wearing'],
    explanation: 'The past participle of "wear" is "worn".',
    planet: 'earth',
    level: 5,
    questionNumber: 43,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-44',
    type: 'multiple-choice',
    content: 'Choose the correct form: "This shirt has been _____ many times."',
    correctAnswer: 'worn',
    options: ['wear', 'wore', 'worn', 'wearing'],
    explanation: 'Passive voice: has been + past participle (worn).',
    planet: 'earth',
    level: 5,
    questionNumber: 44,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-45',
    type: 'multiple-choice',
    content: 'What is the past participle of "choose"?',
    correctAnswer: 'chosen',
    options: ['choose', 'chose', 'chosen', 'choosing'],
    explanation: 'The past participle of "choose" is "chosen".',
    planet: 'earth',
    level: 5,
    questionNumber: 45,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-46',
    type: 'fill-in-blank',
    content: 'Complete: "The winner has been _____ (choose)."',
    correctAnswer: 'chosen',
    explanation: 'Passive voice: has been + past participle (chosen).',
    planet: 'earth',
    level: 5,
    questionNumber: 46,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-47',
    type: 'correction',
    content: 'Correct the sentence: "They have did their homework."',
    correctAnswer: 'They have done their homework.',
    explanation: 'Use the past participle "done", not the past tense "did".',
    planet: 'earth',
    level: 5,
    questionNumber: 47,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-48',
    type: 'multiple-choice',
    content: 'Choose the correct form: "I have _____ this mistake before."',
    correctAnswer: 'made',
    options: ['make', 'made', 'making', 'makes'],
    explanation: 'Present perfect: have + past participle (made).',
    planet: 'earth',
    level: 5,
    questionNumber: 48,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-49',
    type: 'multiple-choice',
    content: 'What is the past participle of "hide"?',
    correctAnswer: 'hidden',
    options: ['hide', 'hid', 'hidden', 'hiding'],
    explanation: 'The past participle of "hide" is "hidden".',
    planet: 'earth',
    level: 5,
    questionNumber: 49,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-5-50',
    type: 'multiple-choice',
    content: 'Choose the correct form: "The treasure has been _____ for years."',
    correctAnswer: 'hidden',
    options: ['hide', 'hid', 'hidden', 'hiding'],
    explanation: 'Passive voice: has been + past participle (hidden).',
    planet: 'earth',
    level: 5,
    questionNumber: 50,
    points: 10,
    difficulty: 'intermediate'
  }
]; 