import { Exercise } from '@/types/curriculum';

export const earthLevel6Questions: Exercise[] = [
  {
    id: 'earth-6-1',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "When I arrived, she _____ dinner."',
    correctAnswer: 'was cooking',
    options: ['cooked', 'was cooking', 'had cooked', 'cooks'],
    explanation: 'Past continuous for ongoing action when another action occurred.',
    planet: 'earth',
    level: 6,
    questionNumber: 1,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-2',
    type: 'multiple-choice',
    content: 'Select the correct form: "By the time we got there, the movie _____ already."',
    correctAnswer: 'had started',
    options: ['started', 'was starting', 'had started', 'starts'],
    explanation: 'Past perfect for action completed before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 2,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-3',
    type: 'fill-in-blank',
    content: 'Complete: "While I _____ (study), my brother _____ (watch) TV."',
    correctAnswer: 'was studying, was watching',
    explanation: 'Both actions were ongoing simultaneously in the past.',
    planet: 'earth',
    level: 6,
    questionNumber: 3,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-4',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "She _____ her keys before she left the house."',
    correctAnswer: 'had lost',
    options: ['lost', 'was losing', 'had lost', 'loses'],
    explanation: 'Past perfect for action completed before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 4,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-5',
    type: 'multiple-choice',
    content: 'Select the correct form: "The children _____ when their parents came home."',
    correctAnswer: 'were sleeping',
    options: ['slept', 'were sleeping', 'had slept', 'sleep'],
    explanation: 'Past continuous for ongoing action interrupted by another action.',
    planet: 'earth',
    level: 6,
    questionNumber: 5,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-6',
    type: 'fill-in-blank',
    content: 'Complete: "After he _____ (finish) his work, he _____ (go) home."',
    correctAnswer: 'had finished, went',
    explanation: 'Past perfect for the first action, simple past for the second.',
    planet: 'earth',
    level: 6,
    questionNumber: 6,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-7',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "I _____ my homework when the phone rang."',
    correctAnswer: 'was doing',
    options: ['did', 'was doing', 'had done', 'do'],
    explanation: 'Past continuous for interrupted action.',
    planet: 'earth',
    level: 6,
    questionNumber: 7,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-8',
    type: 'multiple-choice',
    content: 'Select the correct form: "They _____ for two hours before the rain stopped."',
    correctAnswer: 'had been waiting',
    options: ['waited', 'were waiting', 'had been waiting', 'wait'],
    explanation: 'Past perfect continuous for duration before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 8,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-9',
    type: 'correction',
    content: 'Correct the sentence: "When I was young, I was go to school by bus."',
    correctAnswer: 'When I was young, I went to school by bus.',
    explanation: 'Use simple past for habitual actions in the past, not past continuous.',
    planet: 'earth',
    level: 6,
    questionNumber: 9,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-10',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "She _____ three books before she turned 10."',
    correctAnswer: 'had read',
    options: ['read', 'was reading', 'had read', 'reads'],
    explanation: 'Past perfect for action completed before a specific past time.',
    planet: 'earth',
    level: 6,
    questionNumber: 10,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-11',
    type: 'fill-in-blank',
    content: 'Complete: "While it _____ (rain), we _____ (stay) inside."',
    correctAnswer: 'was raining, stayed',
    explanation: 'Past continuous for ongoing condition, simple past for completed action.',
    planet: 'earth',
    level: 6,
    questionNumber: 11,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-12',
    type: 'multiple-choice',
    content: 'Select the correct form: "The train _____ by the time we reached the station."',
    correctAnswer: 'had left',
    options: ['left', 'was leaving', 'had left', 'leaves'],
    explanation: 'Past perfect for action completed before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 12,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-13',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "He _____ TV when I called him last night."',
    correctAnswer: 'was watching',
    options: ['watched', 'was watching', 'had watched', 'watches'],
    explanation: 'Past continuous for ongoing action at a specific past time.',
    planet: 'earth',
    level: 6,
    questionNumber: 13,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-14',
    type: 'multiple-choice',
    content: 'Select the correct form: "I _____ never _____ such a beautiful sunset before."',
    correctAnswer: 'had, seen',
    options: ['have, seen', 'had, seen', 'was, seeing', 'did, see'],
    explanation: 'Past perfect for experience before a past reference point.',
    planet: 'earth',
    level: 6,
    questionNumber: 14,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-15',
    type: 'fill-in-blank',
    content: 'Complete: "She _____ (live) in Paris for five years before she _____ (move) to London."',
    correctAnswer: 'had lived, moved',
    explanation: 'Past perfect for duration before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 15,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-16',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The students _____ notes while the teacher was explaining."',
    correctAnswer: 'were taking',
    options: ['took', 'were taking', 'had taken', 'take'],
    explanation: 'Past continuous for simultaneous ongoing actions.',
    planet: 'earth',
    level: 6,
    questionNumber: 16,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-17',
    type: 'multiple-choice',
    content: 'Select the correct form: "After the guests _____, we cleaned the house."',
    correctAnswer: 'had left',
    options: ['left', 'were leaving', 'had left', 'leave'],
    explanation: 'Past perfect for action completed before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 17,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-18',
    type: 'correction',
    content: 'Correct the sentence: "I had been knowing him for years when he moved away."',
    correctAnswer: 'I had known him for years when he moved away.',
    explanation: 'Use past perfect, not past perfect continuous, with stative verbs like "know".',
    planet: 'earth',
    level: 6,
    questionNumber: 18,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-19',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "When we arrived, the party _____ for an hour."',
    correctAnswer: 'had been going on',
    options: ['went on', 'was going on', 'had been going on', 'goes on'],
    explanation: 'Past perfect continuous for duration before a past reference point.',
    planet: 'earth',
    level: 6,
    questionNumber: 19,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-20',
    type: 'fill-in-blank',
    content: 'Complete: "While she _____ (cook), he _____ (set) the table."',
    correctAnswer: 'was cooking, was setting',
    explanation: 'Both actions were ongoing simultaneously in the past.',
    planet: 'earth',
    level: 6,
    questionNumber: 20,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-21',
    type: 'multiple-choice',
    content: 'Select the correct form: "I _____ my wallet after I _____ the store."',
    correctAnswer: 'realized I had lost, left',
    options: ['lost, left', 'was losing, was leaving', 'realized I had lost, left', 'lose, leave'],
    explanation: 'Past perfect for the earlier action, simple past for the later realization.',
    planet: 'earth',
    level: 6,
    questionNumber: 21,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-22',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The baby _____ when the doorbell rang."',
    correctAnswer: 'was sleeping',
    options: ['slept', 'was sleeping', 'had slept', 'sleeps'],
    explanation: 'Past continuous for ongoing action interrupted by another action.',
    planet: 'earth',
    level: 6,
    questionNumber: 22,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-23',
    type: 'multiple-choice',
    content: 'Select the correct form: "By 8 PM, we _____ dinner and _____ the dishes."',
    correctAnswer: 'had eaten, had washed',
    options: ['ate, washed', 'were eating, were washing', 'had eaten, had washed', 'eat, wash'],
    explanation: 'Past perfect for both actions completed before a past reference time.',
    planet: 'earth',
    level: 6,
    questionNumber: 23,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-24',
    type: 'fill-in-blank',
    content: 'Complete: "He _____ (work) there for ten years before he _____ (get) promoted."',
    correctAnswer: 'had been working, got',
    explanation: 'Past perfect continuous for duration, simple past for the result.',
    planet: 'earth',
    level: 6,
    questionNumber: 24,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-25',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "She _____ her homework when her friends arrived."',
    correctAnswer: 'was finishing',
    options: ['finished', 'was finishing', 'had finished', 'finishes'],
    explanation: 'Past continuous for ongoing action when another action occurred.',
    planet: 'earth',
    level: 6,
    questionNumber: 25,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-26',
    type: 'correction',
    content: 'Correct the sentence: "After I was eating lunch, I went for a walk."',
    correctAnswer: 'After I had eaten lunch, I went for a walk.',
    explanation: 'Use past perfect for the completed action before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 26,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-27',
    type: 'multiple-choice',
    content: 'Select the correct form: "The concert _____ when we finally found our seats."',
    correctAnswer: 'had already started',
    options: ['started', 'was starting', 'had already started', 'starts'],
    explanation: 'Past perfect for action completed before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 27,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-28',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "While I _____ for the bus, it started to rain."',
    correctAnswer: 'was waiting',
    options: ['waited', 'was waiting', 'had waited', 'wait'],
    explanation: 'Past continuous for ongoing action interrupted by another action.',
    planet: 'earth',
    level: 6,
    questionNumber: 28,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-29',
    type: 'fill-in-blank',
    content: 'Complete: "They _____ (travel) for six hours before they _____ (reach) their destination."',
    correctAnswer: 'had been traveling, reached',
    explanation: 'Past perfect continuous for duration, simple past for the endpoint.',
    planet: 'earth',
    level: 6,
    questionNumber: 29,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-30',
    type: 'multiple-choice',
    content: 'Select the correct form: "I _____ him before, but I couldn\'t remember where."',
    correctAnswer: 'had met',
    options: ['met', 'was meeting', 'had met', 'meet'],
    explanation: 'Past perfect for experience before a past reference point.',
    planet: 'earth',
    level: 6,
    questionNumber: 30,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-31',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The phone _____ while she was taking a shower."',
    correctAnswer: 'rang',
    options: ['rang', 'was ringing', 'had rung', 'rings'],
    explanation: 'Simple past for the interrupting action.',
    planet: 'earth',
    level: 6,
    questionNumber: 31,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-32',
    type: 'multiple-choice',
    content: 'Select the correct form: "When I was a child, I _____ to the beach every summer."',
    correctAnswer: 'went',
    options: ['went', 'was going', 'had gone', 'go'],
    explanation: 'Simple past for repeated actions in the past.',
    planet: 'earth',
    level: 6,
    questionNumber: 32,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-33',
    type: 'fill-in-blank',
    content: 'Complete: "She _____ (study) English for three years before she _____ (move) to America."',
    correctAnswer: 'had been studying, moved',
    explanation: 'Past perfect continuous for duration, simple past for the change.',
    planet: 'earth',
    level: 6,
    questionNumber: 33,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-34',
    type: 'correction',
    content: 'Correct the sentence: "I was already leaving when you were calling me."',
    correctAnswer: 'I had already left when you called me.',
    explanation: 'Use past perfect for the earlier action, simple past for the later action.',
    planet: 'earth',
    level: 6,
    questionNumber: 34,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-35',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The movie _____ by the time we bought tickets."',
    correctAnswer: 'had sold out',
    options: ['sold out', 'was selling out', 'had sold out', 'sells out'],
    explanation: 'Past perfect for action completed before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 35,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-36',
    type: 'multiple-choice',
    content: 'Select the correct form: "While the children _____, the adults were talking."',
    correctAnswer: 'were playing',
    options: ['played', 'were playing', 'had played', 'play'],
    explanation: 'Past continuous for simultaneous ongoing actions.',
    planet: 'earth',
    level: 6,
    questionNumber: 36,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-37',
    type: 'fill-in-blank',
    content: 'Complete: "After he _____ (graduate), he _____ (start) looking for a job."',
    correctAnswer: 'had graduated, started',
    explanation: 'Past perfect for the first completed action, simple past for the second.',
    planet: 'earth',
    level: 6,
    questionNumber: 37,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-38',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "I _____ my keys everywhere before I found them."',
    correctAnswer: 'had been looking for',
    options: ['looked for', 'was looking for', 'had been looking for', 'look for'],
    explanation: 'Past perfect continuous for ongoing action before a past result.',
    planet: 'earth',
    level: 6,
    questionNumber: 38,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-39',
    type: 'multiple-choice',
    content: 'Select the correct form: "She _____ when I knocked on the door."',
    correctAnswer: 'was singing',
    options: ['sang', 'was singing', 'had sung', 'sings'],
    explanation: 'Past continuous for ongoing action interrupted by another action.',
    planet: 'earth',
    level: 6,
    questionNumber: 39,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-40',
    type: 'correction',
    content: 'Correct the sentence: "Before I went to bed, I was brushing my teeth."',
    correctAnswer: 'Before I went to bed, I brushed my teeth.',
    explanation: 'Use simple past for completed routine actions, not past continuous.',
    planet: 'earth',
    level: 6,
    questionNumber: 40,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-41',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The team _____ for months before they won the championship."',
    correctAnswer: 'had been training',
    options: ['trained', 'was training', 'had been training', 'trains'],
    explanation: 'Past perfect continuous for duration before a past achievement.',
    planet: 'earth',
    level: 6,
    questionNumber: 41,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-42',
    type: 'fill-in-blank',
    content: 'Complete: "When I _____ (arrive) at the party, everyone _____ (already/leave)."',
    correctAnswer: 'arrived, had already left',
    explanation: 'Simple past for arrival, past perfect for the earlier departure.',
    planet: 'earth',
    level: 6,
    questionNumber: 42,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-43',
    type: 'multiple-choice',
    content: 'Select the correct form: "I _____ about the problem all night before I found a solution."',
    correctAnswer: 'had been thinking',
    options: ['thought', 'was thinking', 'had been thinking', 'think'],
    explanation: 'Past perfect continuous for mental activity over time before a result.',
    planet: 'earth',
    level: 6,
    questionNumber: 43,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-44',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The sun _____ when we started our hike."',
    correctAnswer: 'was shining',
    options: ['shone', 'was shining', 'had shone', 'shines'],
    explanation: 'Past continuous for ongoing condition at the time of another action.',
    planet: 'earth',
    level: 6,
    questionNumber: 44,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-45',
    type: 'multiple-choice',
    content: 'Select the correct form: "She _____ three cups of coffee before noon."',
    correctAnswer: 'had drunk',
    options: ['drank', 'was drinking', 'had drunk', 'drinks'],
    explanation: 'Past perfect for action completed before a past reference time.',
    planet: 'earth',
    level: 6,
    questionNumber: 45,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-46',
    type: 'correction',
    content: 'Correct the sentence: "While I had been walking, I saw an old friend."',
    correctAnswer: 'While I was walking, I saw an old friend.',
    explanation: 'Use past continuous, not past perfect continuous, for the background action.',
    planet: 'earth',
    level: 6,
    questionNumber: 46,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-47',
    type: 'fill-in-blank',
    content: 'Complete: "The storm _____ (rage) for hours before it _____ (finally/stop)."',
    correctAnswer: 'had been raging, finally stopped',
    explanation: 'Past perfect continuous for duration, simple past for the endpoint.',
    planet: 'earth',
    level: 6,
    questionNumber: 47,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-48',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "I _____ my homework when my computer crashed."',
    correctAnswer: 'was finishing',
    options: ['finished', 'was finishing', 'had finished', 'finish'],
    explanation: 'Past continuous for ongoing action interrupted by another action.',
    planet: 'earth',
    level: 6,
    questionNumber: 48,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-49',
    type: 'multiple-choice',
    content: 'Select the correct form: "By the time the ambulance arrived, the patient _____ consciousness."',
    correctAnswer: 'had regained',
    options: ['regained', 'was regaining', 'had regained', 'regains'],
    explanation: 'Past perfect for action completed before another past action.',
    planet: 'earth',
    level: 6,
    questionNumber: 49,
    points: 10,
    difficulty: 'intermediate'
  },
  {
    id: 'earth-6-50',
    type: 'multiple-choice',
    content: 'Choose the correct tense: "The children _____ quietly when the teacher returned."',
    correctAnswer: 'were working',
    options: ['worked', 'were working', 'had worked', 'work'],
    explanation: 'Past continuous for ongoing action at the time of another action.',
    planet: 'earth',
    level: 6,
    questionNumber: 50,
    points: 10,
    difficulty: 'intermediate'
  }
]; 