import { Exercise } from '@/types/curriculum';
import { Planet } from '@/types/curriculum';

export const allQuestions: Exercise[] = [
  {
    "id": "mercury-1-1",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "run",
    "options": ["run", "happy", "blue", "chair"],
    "explanation": "Run is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 1,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-2",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "kick",
    "options": ["kick", "green", "fun", "slow"],
    "explanation": "Kick is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 2,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-3",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "laugh",
    "options": ["laugh", "tall", "sand", "cold"],
    "explanation": "Laugh is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 3,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-4",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "write",
    "options": ["write", "smooth", "summer", "song"],
    "explanation": "Write is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 4,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-5",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "swim",
    "options": ["swim", "sweet", "dog", "bright"],
    "explanation": "Swim is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 5,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-6",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "climb",
    "options": ["climb", "early", "river", "hard"],
    "explanation": "Climb is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 6,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-7",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "throw",
    "options": ["throw", "quiet", "moon", "round"],
    "explanation": "Throw is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 7,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-8",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "dance",
    "options": ["dance", "yellow", "wind", "kind"],
    "explanation": "Dance is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 8,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-9",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "eat",
    "options": ["eat", "shiny", "cat", "slowly"],
    "explanation": "Eat is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 9,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-10",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "draw",
    "options": ["draw", "soft", "sky", "circle"],
    "explanation": "Draw is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 10,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-11",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "sing",
    "options": ["sing", "heavy", "night", "red"],
    "explanation": "Sing is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 11,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-12",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "read",
    "options": ["read", "smooth", "train", "long"],
    "explanation": "Read is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 12,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-13",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "sleep",
    "options": ["sleep", "sunny", "plate", "wide"],
    "explanation": "Sleep is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 13,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-14",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "catch",
    "options": ["catch", "cloud", "loud", "flat"],
    "explanation": "Catch is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 14,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-15",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "build",
    "options": ["build", "happy", "ice", "round"],
    "explanation": "Build is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 15,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-16",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "listen",
    "options": ["listen", "sharp", "bread", "early"],
    "explanation": "Listen is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 16,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-17",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "paint",
    "options": ["paint", "far", "school", "quietly"],
    "explanation": "Paint is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 17,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-18",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "jump",
    "options": ["jump", "bright", "stone", "softly"],
    "explanation": "Jump is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 18,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-19",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "hop",
    "options": ["hop", "smooth", "light", "cold"],
    "explanation": "Hop is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 19,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-20",
    "type": "multiple-choice",
    "content": "Which word is an action verb?",
    "correctAnswer": "walk",
    "options": ["walk", "loud", "mountain", "sweet"],
    "explanation": "Walk is an action verb because it shows an action someone can do.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 20,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-21",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"I ___ my homework every day.\"",
    "correctAnswer": "do",
    "options": ["do", "does", "did", "doing"],
    "explanation": "The correct present tense form is 'do'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 21,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-22",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"She ___ to piano lessons on Mondays.\"",
    "correctAnswer": "goes",
    "options": ["go", "goes", "went", "going"],
    "explanation": "The correct present tense form is 'goes'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 22,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-23",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"They ___ soccer after school.\"",
    "correctAnswer": "play",
    "options": ["play", "plays", "played", "playing"],
    "explanation": "The correct present tense form is 'play'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 23,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-24",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"Tom ___ early on weekdays.\"",
    "correctAnswer": "wakes",
    "options": ["wake", "wakes", "woke", "waking"],
    "explanation": "The correct present tense form is 'wakes'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 24,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-25",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"We ___ breakfast at 7 a.m.\"",
    "correctAnswer": "eat",
    "options": ["eat", "eats", "ate", "eating"],
    "explanation": "The correct present tense form is 'eat'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 25,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-26",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"The dog ___ loudly.\"",
    "correctAnswer": "barks",
    "options": ["bark", "barks", "barked", "barking"],
    "explanation": "The correct present tense form is 'barks'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 26,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-27",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"My dad ___ the car on Sundays.\"",
    "correctAnswer": "washes",
    "options": ["wash", "washes", "washed", "washing"],
    "explanation": "The correct present tense form is 'washes'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 27,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-28",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"The sun ___ in the east.\"",
    "correctAnswer": "rises",
    "options": ["rise", "rises", "rose", "rising"],
    "explanation": "The correct present tense form is 'rises'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 28,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-29",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"You ___ very fast.\"",
    "correctAnswer": "run",
    "options": ["run", "runs", "ran", "running"],
    "explanation": "The correct present tense form is 'run'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 29,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-30",
    "type": "multiple-choice",
    "content": "Choose the correct verb: \"It ___ often in April.\"",
    "correctAnswer": "rains",
    "options": ["rain", "rains", "rained", "raining"],
    "explanation": "The correct present tense form is 'rains'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 30,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-31",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"Yesterday, I ___ a book.\"",
    "correctAnswer": "read",
    "options": ["read", "reads", "reading", "readed"],
    "explanation": "'read' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 31,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-32",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"Last night, she ___ a cake.\"",
    "correctAnswer": "baked",
    "options": ["bake", "baked", "bakes", "baking"],
    "explanation": "'baked' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 32,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-33",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"We ___ to the park yesterday.\"",
    "correctAnswer": "walked",
    "options": ["walk", "walks", "walked", "walking"],
    "explanation": "'walked' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 33,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-34",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"He ___ his keys this morning.\"",
    "correctAnswer": "lost",
    "options": ["lose", "lost", "loses", "losing"],
    "explanation": "'lost' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 34,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-35",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"They ___ a movie last weekend.\"",
    "correctAnswer": "watched",
    "options": ["watch", "watched", "watches", "watching"],
    "explanation": "'watched' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 35,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-36",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"The bird ___ away moments ago.\"",
    "correctAnswer": "flew",
    "options": ["fly", "flew", "flies", "flying"],
    "explanation": "'flew' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 36,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-37",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"I ___ my lunch at noon.\"",
    "correctAnswer": "ate",
    "options": ["eat", "eats", "ate", "eating"],
    "explanation": "'ate' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 37,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-38",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"She ___ happy when she saw her gift.\"",
    "correctAnswer": "felt",
    "options": ["feel", "feels", "felt", "feeling"],
    "explanation": "'felt' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 38,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-39",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"We ___ a song together last night.\"",
    "correctAnswer": "sang",
    "options": ["sing", "sang", "sings", "singing"],
    "explanation": "'sang' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 39,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-40",
    "type": "multiple-choice",
    "content": "Choose the correct past tense verb: \"The cat ___ under the table yesterday.\"",
    "correctAnswer": "hid",
    "options": ["hide", "hides", "hid", "hiding"],
    "explanation": "'hid' is the correct past tense form.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 40,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-41",
    "type": "fill-in-blank",
    "content": "Every morning, I ____ (ride) my bike to school.",
    "correctAnswer": "ride",
    "options": [],
    "explanation": "The correct verb is 'ride'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 41,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-42",
    "type": "fill-in-blank",
    "content": "She ____ (drink) milk every night.",
    "correctAnswer": "drinks",
    "options": [],
    "explanation": "The correct verb is 'drinks'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 42,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-43",
    "type": "fill-in-blank",
    "content": "They ____ (jump) over the puddles yesterday.",
    "correctAnswer": "jumped",
    "options": [],
    "explanation": "The correct verb is 'jumped'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 43,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-44",
    "type": "fill-in-blank",
    "content": "We ____ (be) excited about the trip last week.",
    "correctAnswer": "were",
    "options": [],
    "explanation": "The correct verb is 'were'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 44,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-45",
    "type": "fill-in-blank",
    "content": "Tom ____ (see) a rainbow yesterday.",
    "correctAnswer": "saw",
    "options": [],
    "explanation": "The correct verb is 'saw'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 45,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-46",
    "type": "fill-in-blank",
    "content": "I ____ (write) letters every month.",
    "correctAnswer": "write",
    "options": [],
    "explanation": "The correct verb is 'write'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 46,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-47",
    "type": "fill-in-blank",
    "content": "He ____ (run) to catch the bus every day.",
    "correctAnswer": "runs",
    "options": [],
    "explanation": "The correct verb is 'runs'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 47,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-48",
    "type": "fill-in-blank",
    "content": "The dog ____ (sleep) in its bed last night.",
    "correctAnswer": "slept",
    "options": [],
    "explanation": "The correct verb is 'slept'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 48,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-49",
    "type": "correction",
    "content": "Correct the sentence: 'She go to school every day.'",
    "correctAnswer": "She goes to school every day.",
    "options": [],
    "explanation": "'Goes' matches the singular subject 'She'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 49,
    "points": 10,
    "difficulty": "beginner"
  },
  {
    "id": "mercury-1-50",
    "type": "correction",
    "content": "Correct the sentence: 'Yesterday we swimmed in the pool.'",
    "correctAnswer": "Yesterday we swam in the pool.",
    "options": [],
    "explanation": "The past tense of 'swim' is 'swam', not 'swimmed'.",
    "planet": "mercury",
    "level": 1,
    "questionNumber": 50,
    "points": 10,
    "difficulty": "beginner"
  }
];

// Helper function to get questions for a specific planet and level
export const getQuestionsForLevel = (planet: Planet | string, level: number): Exercise[] => {
  if (planet === 'earth' && level === 1) {
    return [
      {
        id: 'earth-1-1',
        type: 'multiple-choice',
        content: 'What is the past tense of "walk"?',
        correctAnswer: 'walked',
        options: ['walked', 'walken', 'walkt', 'walking'],
        explanation: 'Regular verbs in past tense add -ed to the base form.',
        planet: 'earth',
        level: 1,
        questionNumber: 1,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-2',
        type: 'multiple-choice',
        content: 'What is the past participle of "write"?',
        correctAnswer: 'written',
        options: ['wrote', 'written', 'writed', 'writing'],
        explanation: 'The past participle of "write" is "written".',
        planet: 'earth',
        level: 1,
        questionNumber: 2,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-3',
        type: 'multiple-choice',
        content: 'What is the past tense of "eat"?',
        correctAnswer: 'ate',
        options: ['eaten', 'ate', 'eated', 'eating'],
        explanation: 'The past tense of "eat" is "ate".',
        planet: 'earth',
        level: 1,
        questionNumber: 3,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-4',
        type: 'multiple-choice',
        content: 'What is the past participle of "go"?',
        correctAnswer: 'gone',
        options: ['went', 'gone', 'goed', 'going'],
        explanation: 'The past participle of "go" is "gone".',
        planet: 'earth',
        level: 1,
        questionNumber: 4,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-5',
        type: 'multiple-choice',
        content: 'What is the past tense of "play"?',
        correctAnswer: 'played',
        options: ['played', 'playen', 'playt', 'playing'],
        explanation: 'Regular verbs in past tense add -ed to the base form.',
        planet: 'earth',
        level: 1,
        questionNumber: 5,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-6',
        type: 'multiple-choice',
        content: 'What is the past participle of "see"?',
        correctAnswer: 'seen',
        options: ['saw', 'seen', 'seed', 'seeing'],
        explanation: 'The past participle of "see" is "seen".',
        planet: 'earth',
        level: 1,
        questionNumber: 6,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-7',
        type: 'multiple-choice',
        content: 'What is the past tense of "run"?',
        correctAnswer: 'ran',
        options: ['run', 'ran', 'runned', 'running'],
        explanation: 'The past tense of "run" is "ran".',
        planet: 'earth',
        level: 1,
        questionNumber: 7,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-8',
        type: 'multiple-choice',
        content: 'What is the past participle of "take"?',
        correctAnswer: 'taken',
        options: ['took', 'taken', 'taked', 'taking'],
        explanation: 'The past participle of "take" is "taken".',
        planet: 'earth',
        level: 1,
        questionNumber: 8,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-9',
        type: 'multiple-choice',
        content: 'What is the past tense of "jump"?',
        correctAnswer: 'jumped',
        options: ['jumped', 'jumpen', 'jumpt', 'jumping'],
        explanation: 'Regular verbs in past tense add -ed to the base form.',
        planet: 'earth',
        level: 1,
        questionNumber: 9,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-10',
        type: 'multiple-choice',
        content: 'What is the past participle of "break"?',
        correctAnswer: 'broken',
        options: ['broke', 'broken', 'breaked', 'breaking'],
        explanation: 'The past participle of "break" is "broken".',
        planet: 'earth',
        level: 1,
        questionNumber: 10,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-11',
        type: 'multiple-choice',
        content: 'What is the past tense of "sing"?',
        correctAnswer: 'sang',
        options: ['sang', 'sung', 'singed', 'singing'],
        explanation: 'The past tense of "sing" is "sang".',
        planet: 'earth',
        level: 1,
        questionNumber: 11,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-12',
        type: 'multiple-choice',
        content: 'What is the past participle of "drink"?',
        correctAnswer: 'drunk',
        options: ['drank', 'drunk', 'drinked', 'drinking'],
        explanation: 'The past participle of "drink" is "drunk".',
        planet: 'earth',
        level: 1,
        questionNumber: 12,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-13',
        type: 'multiple-choice',
        content: 'What is the past tense of "dance"?',
        correctAnswer: 'danced',
        options: ['danced', 'dancen', 'dancet', 'dancing'],
        explanation: 'Regular verbs in past tense add -ed to the base form.',
        planet: 'earth',
        level: 1,
        questionNumber: 13,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-14',
        type: 'multiple-choice',
        content: 'What is the past participle of "swim"?',
        correctAnswer: 'swum',
        options: ['swam', 'swum', 'swimmed', 'swimming'],
        explanation: 'The past participle of "swim" is "swum".',
        planet: 'earth',
        level: 1,
        questionNumber: 14,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-15',
        type: 'multiple-choice',
        content: 'What is the past tense of "sleep"?',
        correctAnswer: 'slept',
        options: ['slept', 'sleeped', 'slepen', 'sleeping'],
        explanation: 'The past tense of "sleep" is "slept".',
        planet: 'earth',
        level: 1,
        questionNumber: 15,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-16',
        type: 'multiple-choice',
        content: 'What is the past participle of "give"?',
        correctAnswer: 'given',
        options: ['gave', 'given', 'gived', 'giving'],
        explanation: 'The past participle of "give" is "given".',
        planet: 'earth',
        level: 1,
        questionNumber: 16,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-17',
        type: 'multiple-choice',
        content: 'What is the past tense of "laugh"?',
        correctAnswer: 'laughed',
        options: ['laughed', 'laughn', 'laught', 'laughing'],
        explanation: 'Regular verbs in past tense add -ed to the base form.',
        planet: 'earth',
        level: 1,
        questionNumber: 17,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-18',
        type: 'multiple-choice',
        content: 'What is the past participle of "ride"?',
        correctAnswer: 'ridden',
        options: ['rode', 'ridden', 'rided', 'riding'],
        explanation: 'The past participle of "ride" is "ridden".',
        planet: 'earth',
        level: 1,
        questionNumber: 18,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-19',
        type: 'multiple-choice',
        content: 'What is the past tense of "cry"?',
        correctAnswer: 'cried',
        options: ['cried', 'cryed', 'crien', 'crying'],
        explanation: 'For verbs ending in -y, change -y to -i and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 19,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-20',
        type: 'multiple-choice',
        content: 'What is the past participle of "speak"?',
        correctAnswer: 'spoken',
        options: ['spoke', 'spoken', 'speaked', 'speaking'],
        explanation: 'The past participle of "speak" is "spoken".',
        planet: 'earth',
        level: 1,
        questionNumber: 20,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-21',
        type: 'multiple-choice',
        content: 'What is the past tense of "stop"?',
        correctAnswer: 'stopped',
        options: ['stopped', 'stoped', 'stopen', 'stopping'],
        explanation: 'For verbs ending in consonant-vowel-consonant, double the final consonant and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 21,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-22',
        type: 'multiple-choice',
        content: 'What is the past participle of "choose"?',
        correctAnswer: 'chosen',
        options: ['chose', 'chosen', 'choosed', 'choosing'],
        explanation: 'The past participle of "choose" is "chosen".',
        planet: 'earth',
        level: 1,
        questionNumber: 22,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-23',
        type: 'multiple-choice',
        content: 'What is the past tense of "begin"?',
        correctAnswer: 'began',
        options: ['began', 'begun', 'begined', 'beginning'],
        explanation: 'The past tense of "begin" is "began".',
        planet: 'earth',
        level: 1,
        questionNumber: 23,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-24',
        type: 'multiple-choice',
        content: 'What is the past participle of "forget"?',
        correctAnswer: 'forgotten',
        options: ['forgot', 'forgotten', 'forgeted', 'forgetting'],
        explanation: 'The past participle of "forget" is "forgotten".',
        planet: 'earth',
        level: 1,
        questionNumber: 24,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-25',
        type: 'multiple-choice',
        content: 'What is the past tense of "study"?',
        correctAnswer: 'studied',
        options: ['studied', 'studyed', 'studien', 'studying'],
        explanation: 'For verbs ending in -y, change -y to -i and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 25,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-26',
        type: 'multiple-choice',
        content: 'What is the past participle of "know"?',
        correctAnswer: 'known',
        options: ['knew', 'known', 'knowed', 'knowing'],
        explanation: 'The past participle of "know" is "known".',
        planet: 'earth',
        level: 1,
        questionNumber: 26,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-27',
        type: 'multiple-choice',
        content: 'What is the past tense of "plan"?',
        correctAnswer: 'planned',
        options: ['planned', 'planed', 'planen', 'planning'],
        explanation: 'For verbs ending in consonant-vowel-consonant, double the final consonant and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 27,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-28',
        type: 'multiple-choice',
        content: 'What is the past participle of "throw"?',
        correctAnswer: 'thrown',
        options: ['threw', 'thrown', 'throwed', 'throwing'],
        explanation: 'The past participle of "throw" is "thrown".',
        planet: 'earth',
        level: 1,
        questionNumber: 28,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-29',
        type: 'multiple-choice',
        content: 'What is the past tense of "carry"?',
        correctAnswer: 'carried',
        options: ['carried', 'carryed', 'carrien', 'carrying'],
        explanation: 'For verbs ending in -y, change -y to -i and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 29,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-30',
        type: 'multiple-choice',
        content: 'What is the past participle of "grow"?',
        correctAnswer: 'grown',
        options: ['grew', 'grown', 'growed', 'growing'],
        explanation: 'The past participle of "grow" is "grown".',
        planet: 'earth',
        level: 1,
        questionNumber: 30,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-31',
        type: 'multiple-choice',
        content: 'What is the past tense of "try"?',
        correctAnswer: 'tried',
        options: ['tried', 'tryed', 'trien', 'trying'],
        explanation: 'For verbs ending in -y, change -y to -i and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 31,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-32',
        type: 'multiple-choice',
        content: 'What is the past participle of "wear"?',
        correctAnswer: 'worn',
        options: ['wore', 'worn', 'weared', 'wearing'],
        explanation: 'The past participle of "wear" is "worn".',
        planet: 'earth',
        level: 1,
        questionNumber: 32,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-33',
        type: 'multiple-choice',
        content: 'What is the past tense of "drop"?',
        correctAnswer: 'dropped',
        options: ['dropped', 'droped', 'dropen', 'dropping'],
        explanation: 'For verbs ending in consonant-vowel-consonant, double the final consonant and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 33,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-34',
        type: 'multiple-choice',
        content: 'What is the past participle of "tear"?',
        correctAnswer: 'torn',
        options: ['tore', 'torn', 'teared', 'tearing'],
        explanation: 'The past participle of "tear" is "torn".',
        planet: 'earth',
        level: 1,
        questionNumber: 34,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-35',
        type: 'multiple-choice',
        content: 'What is the past tense of "copy"?',
        correctAnswer: 'copied',
        options: ['copied', 'copyed', 'copien', 'copying'],
        explanation: 'For verbs ending in -y, change -y to -i and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 35,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-36',
        type: 'multiple-choice',
        content: 'What is the past participle of "steal"?',
        correctAnswer: 'stolen',
        options: ['stole', 'stolen', 'stealed', 'stealing'],
        explanation: 'The past participle of "steal" is "stolen".',
        planet: 'earth',
        level: 1,
        questionNumber: 36,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-37',
        type: 'multiple-choice',
        content: 'What is the past tense of "hop"?',
        correctAnswer: 'hopped',
        options: ['hopped', 'hoped', 'hopen', 'hopping'],
        explanation: 'For verbs ending in consonant-vowel-consonant, double the final consonant and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 37,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-38',
        type: 'multiple-choice',
        content: 'What is the past participle of "freeze"?',
        correctAnswer: 'frozen',
        options: ['froze', 'frozen', 'freezed', 'freezing'],
        explanation: 'The past participle of "freeze" is "frozen".',
        planet: 'earth',
        level: 1,
        questionNumber: 38,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-39',
        type: 'multiple-choice',
        content: 'What is the past tense of "marry"?',
        correctAnswer: 'married',
        options: ['married', 'marryed', 'marrien', 'marrying'],
        explanation: 'For verbs ending in -y, change -y to -i and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 39,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-40',
        type: 'multiple-choice',
        content: 'What is the past participle of "shake"?',
        correctAnswer: 'shaken',
        options: ['shook', 'shaken', 'shaked', 'shaking'],
        explanation: 'The past participle of "shake" is "shaken".',
        planet: 'earth',
        level: 1,
        questionNumber: 40,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-41',
        type: 'multiple-choice',
        content: 'What is the past tense of "rub"?',
        correctAnswer: 'rubbed',
        options: ['rubbed', 'rubed', 'ruben', 'rubbing'],
        explanation: 'For verbs ending in consonant-vowel-consonant, double the final consonant and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 41,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-42',
        type: 'multiple-choice',
        content: 'What is the past participle of "wake"?',
        correctAnswer: 'woken',
        options: ['woke', 'woken', 'waked', 'waking'],
        explanation: 'The past participle of "wake" is "woken".',
        planet: 'earth',
        level: 1,
        questionNumber: 42,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-43',
        type: 'multiple-choice',
        content: 'What is the past tense of "worry"?',
        correctAnswer: 'worried',
        options: ['worried', 'worryed', 'worrien', 'worrying'],
        explanation: 'For verbs ending in -y, change -y to -i and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 43,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-44',
        type: 'multiple-choice',
        content: 'What is the past participle of "draw"?',
        correctAnswer: 'drawn',
        options: ['drew', 'drawn', 'drawed', 'drawing'],
        explanation: 'The past participle of "draw" is "drawn".',
        planet: 'earth',
        level: 1,
        questionNumber: 44,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-45',
        type: 'multiple-choice',
        content: 'What is the past tense of "clap"?',
        correctAnswer: 'clapped',
        options: ['clapped', 'claped', 'clapen', 'clapping'],
        explanation: 'For verbs ending in consonant-vowel-consonant, double the final consonant and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 45,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-46',
        type: 'multiple-choice',
        content: 'What is the past participle of "blow"?',
        correctAnswer: 'blown',
        options: ['blew', 'blown', 'blowed', 'blowing'],
        explanation: 'The past participle of "blow" is "blown".',
        planet: 'earth',
        level: 1,
        questionNumber: 46,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-47',
        type: 'multiple-choice',
        content: 'What is the past tense of "reply"?',
        correctAnswer: 'replied',
        options: ['replied', 'replyed', 'replien', 'replying'],
        explanation: 'For verbs ending in -y, change -y to -i and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 47,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-48',
        type: 'multiple-choice',
        content: 'What is the past participle of "fly"?',
        correctAnswer: 'flown',
        options: ['flew', 'flown', 'flyed', 'flying'],
        explanation: 'The past participle of "fly" is "flown".',
        planet: 'earth',
        level: 1,
        questionNumber: 48,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-49',
        type: 'multiple-choice',
        content: 'What is the past tense of "nod"?',
        correctAnswer: 'nodded',
        options: ['nodded', 'noded', 'noden', 'nodding'],
        explanation: 'For verbs ending in consonant-vowel-consonant, double the final consonant and add -ed.',
        planet: 'earth',
        level: 1,
        questionNumber: 49,
        points: 10,
        difficulty: 'beginner'
      },
      {
        id: 'earth-1-50',
        type: 'multiple-choice',
        content: 'What is the past participle of "know"?',
        correctAnswer: 'known',
        options: ['knew', 'known', 'knowed', 'knowing'],
        explanation: 'The past participle of "know" is "known".',
        planet: 'earth',
        level: 1,
        questionNumber: 50,
        points: 10,
        difficulty: 'beginner'
      }
    ];
  }
  return allQuestions.filter(q => q.planet === planet && q.level === level);
};

// Helper function to get a specific question
export const getQuestionById = (id: string): Exercise | undefined => {
  return allQuestions.find(q => q.id === id);
}; 